export interface DiagnosticMetric {
  readonly slug: string;
  readonly nameRu: string;
  readonly nameEn: string;
  readonly category: 'network' | 'screen' | 'hardware' | 'browser' | 'battery' | 'os';
  readonly descriptionRu: string;
  readonly descriptionEn: string;
}

export const DIAGNOSTIC_METRICS: readonly DiagnosticMetric[] = [
  // ── Network (12) ──
  {
    slug: 'ip',
    nameRu: 'Внешний IP-адрес',
    nameEn: 'Public IP Address',
    category: 'network',
    descriptionRu: 'Определение публичного IP-адреса интернет-соединения в реальном времени.',
    descriptionEn: 'Real-time detection of your public Internet IP address.',
  },
  {
    slug: 'ipv4',
    nameRu: 'IPv4-адрес',
    nameEn: 'IPv4 Address',
    category: 'network',
    descriptionRu: 'Проверка доступности и адреса по протоколу IPv4.',
    descriptionEn: 'Check availability and address for IPv4 protocol.',
  },
  {
    slug: 'ipv6',
    nameRu: 'IPv6-адрес',
    nameEn: 'IPv6 Address',
    category: 'network',
    descriptionRu: 'Проверка поддержки и адреса новейшего сетевого протокола IPv6.',
    descriptionEn: 'Check support and address for the modern IPv6 protocol.',
  },
  {
    slug: 'local-ip',
    nameRu: 'Локальный IP-адрес',
    nameEn: 'Local IP Address',
    category: 'network',
    descriptionRu: 'Определение частного локального сетевого адреса в вашей подсети.',
    descriptionEn: 'Detection of private local network IP in your subnet.',
  },
  {
    slug: 'webrtc',
    nameRu: 'Тест утечки WebRTC (STUN)',
    nameEn: 'WebRTC Leak Test',
    category: 'network',
    descriptionRu: 'Диагностика потенциальных утечек реального локального и внешнего IP через WebRTC API.',
    descriptionEn: 'Diagnostic test for IP leak vulnerabilities via WebRTC STUN.',
  },
  {
    slug: 'isp',
    nameRu: 'Интернет-провайдер (ISP)',
    nameEn: 'Internet Service Provider (ISP)',
    category: 'network',
    descriptionRu: 'Определение организации и провайдера, предоставляющего доступ в интернет.',
    descriptionEn: 'Identify the Internet Service Provider serving your connection.',
  },
  {
    slug: 'asn',
    nameRu: 'Автономная система (ASN)',
    nameEn: 'Autonomous System Number (ASN)',
    category: 'network',
    descriptionRu: 'Номер и маршрутная информация автономной системы BGP.',
    descriptionEn: 'BGP routing and Autonomous System Number information.',
  },
  {
    slug: 'ping-latency',
    nameRu: 'Сетевая задержка (Ping)',
    nameEn: 'Network Latency (Ping)',
    category: 'network',
    descriptionRu: 'Измерение времени отклика (RTT) до ближайших веб-серверов в миллисекундах.',
    descriptionEn: 'Round-trip response time measurement in milliseconds.',
  },
  {
    slug: 'http-protocol',
    nameRu: 'Протокол передачи (HTTP/2 / HTTP/3)',
    nameEn: 'HTTP Protocol Version',
    category: 'network',
    descriptionRu: 'Определение версии прикладного протокола HTTP при подключении.',
    descriptionEn: 'Identification of active HTTP protocol version (HTTP/2, HTTP/3 QUIC).',
  },
  {
    slug: 'dns-leak',
    nameRu: 'Проверка утечки DNS',
    nameEn: 'DNS Leak Test',
    category: 'network',
    descriptionRu: 'Проверка резолверов DNS на предмет перехвата запросов и утечки приватности.',
    descriptionEn: 'Check DNS resolvers to ensure queries are not being leaked.',
  },
  {
    slug: 'proxy-detected',
    nameRu: 'Детекция Proxy / VPN',
    nameEn: 'Proxy & VPN Detection',
    category: 'network',
    descriptionRu: 'Анализ сетевых заголовков на наличие анонимайзеров и прокси.',
    descriptionEn: 'Header and MTU heuristics to detect anonymizing proxies or VPNs.',
  },
  {
    slug: 'ssl-tls',
    nameRu: 'Версия SSL / TLS шифрования',
    nameEn: 'SSL / TLS Security Cipher',
    category: 'network',
    descriptionRu: 'Проверка версии криптографического протокола TLS и стойкости шифра.',
    descriptionEn: 'Verification of active TLS encryption version and cryptographic cipher.',
  },

  // ── Screen & Display (15) ──
  {
    slug: 'screen-resolution',
    nameRu: 'Физическое разрешение экрана',
    nameEn: 'Physical Screen Resolution',
    category: 'screen',
    descriptionRu: 'Реальное число физических пикселей дисплея устройства по ширине и высоте.',
    descriptionEn: 'Total physical hardware pixels available on your display.',
  },
  {
    slug: 'logical-resolution',
    nameRu: 'Логическое разрешение (CSS)',
    nameEn: 'Logical CSS Resolution',
    category: 'screen',
    descriptionRu: 'Размер рабочей области страницы в CSS-пикселях с учетом масштабирования.',
    descriptionEn: 'Viewport rendering area in scalable CSS pixels.',
  },
  {
    slug: 'viewport-size',
    nameRu: 'Размер окна браузера (Viewport)',
    nameEn: 'Browser Viewport Size',
    category: 'screen',
    descriptionRu: 'Текущие внутренние размеры видимого окна браузера (window.innerWidth/Height).',
    descriptionEn: 'Current inner width and height of browser document window.',
  },
  {
    slug: 'dpr',
    nameRu: 'Коэффициент пикселей (Device Pixel Ratio)',
    nameEn: 'Device Pixel Ratio (DPR)',
    category: 'screen',
    descriptionRu: 'Соотношение физических пикселей дисплея к CSS-пикселям (HiDPI / Retina).',
    descriptionEn: 'Ratio between hardware pixels and logical CSS pixels.',
  },
  {
    slug: 'color-depth',
    nameRu: 'Глубина цвета экрана',
    nameEn: 'Color Depth (Bits Per Pixel)',
    category: 'screen',
    descriptionRu: 'Количество бит, используемых для кодирования цвета каждого пикселя.',
    descriptionEn: 'Bit depth used to represent color for each pixel on screen.',
  },
  {
    slug: 'pixel-depth',
    nameRu: 'Глубина пикселей (Pixel Depth)',
    nameEn: 'Pixel Depth',
    category: 'screen',
    descriptionRu: 'Глубина буфера кадра графической подсистемы устройства.',
    descriptionEn: 'Color buffer resolution in bits per pixel.',
  },
  {
    slug: 'refresh-rate',
    nameRu: 'Частота обновления экрана (Гц)',
    nameEn: 'Screen Refresh Rate (Hz)',
    category: 'screen',
    descriptionRu: 'Измерение кадровой частоты дисплея (60Hz, 120Hz ProMotion, 144Hz, 240Hz).',
    descriptionEn: 'Measurement of hardware display frame refresh frequency.',
  },
  {
    slug: 'color-gamut',
    nameRu: 'Цветовой охват (sRGB / Display P3)',
    nameEn: 'Color Gamut (DCI-P3 / sRGB)',
    category: 'screen',
    descriptionRu: 'Диапазон поддерживаемых монитором цветов (sRGB, P3, Rec. 2020).',
    descriptionEn: 'Evaluation of wide color gamut support (Display P3, Rec2020).',
  },
  {
    slug: 'hdr-support',
    nameRu: 'Поддержка HDR (High Dynamic Range)',
    nameEn: 'HDR Display Support',
    category: 'screen',
    descriptionRu: 'Проверка возможности дисплея отображать контент с расширенным динамическим диапазоном.',
    descriptionEn: 'Detection of high dynamic range playback capabilities.',
  },
  {
    slug: 'orientation',
    nameRu: 'Ориентация дисплея',
    nameEn: 'Screen Orientation',
    category: 'screen',
    descriptionRu: 'Альбомная или портретная ориентация экрана (ScreenOrientation API).',
    descriptionEn: 'Landscape or portrait screen orientation status.',
  },
  {
    slug: 'aspect-ratio',
    nameRu: 'Соотношение сторон экрана',
    nameEn: 'Display Aspect Ratio',
    category: 'screen',
    descriptionRu: 'Математическое соотношение ширины и высоты матрицы (16:9, 16:10, 21:9).',
    descriptionEn: 'Geometric aspect ratio of width to height for active screen.',
  },
  {
    slug: 'touch-screen',
    nameRu: 'Сенсорный ввод (Touch Support)',
    nameEn: 'Touch Screen Capability',
    category: 'screen',
    descriptionRu: 'Определение поддержки сенсорных жестов и мультитач.',
    descriptionEn: 'Detection of capacitive touch screen sensors.',
  },
  {
    slug: 'max-touch-points',
    nameRu: 'Количество точек касания (Multi-touch)',
    nameEn: 'Max Touch Points',
    category: 'screen',
    descriptionRu: 'Максимальное число одновременно регистрируемых пальцев (touch points).',
    descriptionEn: 'Maximum number of simultaneous touch contact points supported.',
  },
  {
    slug: 'pointer-type',
    nameRu: 'Тип указателя (Мышь / Палец / Стилус)',
    nameEn: 'Primary Pointer Type',
    category: 'screen',
    descriptionRu: 'Определение основного манипулятора (fine: мышь, coarse: палец, stylus).',
    descriptionEn: 'Identification of primary input device precision.',
  },
  {
    slug: 'zoom-level',
    nameRu: 'Уровень масштабирования страницы',
    nameEn: 'Page Zoom Level',
    category: 'screen',
    descriptionRu: 'Вычисление текущего пользовательского зума страницы в браузере.',
    descriptionEn: 'Calculation of browser zoom factor in percentages.',
  },

  // ── Hardware & CPU/GPU (12) ──
  {
    slug: 'cpu',
    nameRu: 'Процессор устройства',
    nameEn: 'Processor (CPU)',
    category: 'hardware',
    descriptionRu: 'Диагностика вычислительного процессора и параллельных потоков.',
    descriptionEn: 'General overview of host computing processor and threads.',
  },
  {
    slug: 'cpu-cores',
    nameRu: 'Количество ядер процессора (Потоки)',
    nameEn: 'Logical CPU Cores',
    category: 'hardware',
    descriptionRu: 'Число логических потоков выполнения (hardwareConcurrency).',
    descriptionEn: 'Number of logical processing execution units available.',
  },
  {
    slug: 'cpu-architecture',
    nameRu: 'Архитектура процессора (ARM / x86_64)',
    nameEn: 'CPU Architecture',
    category: 'hardware',
    descriptionRu: 'Определение архитектуры команд процессора (x86_64, ARM64, Apple Silicon).',
    descriptionEn: 'Instruction set architecture detection for host processor.',
  },
  {
    slug: 'ram-memory',
    nameRu: 'Оперативная память (RAM)',
    nameEn: 'Device RAM Memory',
    category: 'hardware',
    descriptionRu: 'Приблизительный объем оперативной памяти устройства (DeviceMemory API).',
    descriptionEn: 'Approximated physical RAM available to user agent.',
  },
  {
    slug: 'hardware-concurrency',
    nameRu: 'Аппаратная многопоточность',
    nameEn: 'Hardware Concurrency',
    category: 'hardware',
    descriptionRu: 'Количество параллельных Web Worker потоков, поддерживаемых без блокировок.',
    descriptionEn: 'Available background concurrency threads for Web Workers.',
  },
  {
    slug: 'device-memory',
    nameRu: 'Квота памяти устройства (GB)',
    nameEn: 'Device Memory Tier (GB)',
    category: 'hardware',
    descriptionRu: 'Классификатор объема памяти по шкале W3C Device Memory.',
    descriptionEn: 'Memory tier rating according to W3C specification.',
  },
  {
    slug: 'gpu',
    nameRu: 'Видеокарта (GPU)',
    nameEn: 'Graphics Card (GPU)',
    category: 'hardware',
    descriptionRu: 'Определение модели графического ускорителя через WebGL API.',
    descriptionEn: 'Detection of dedicated or integrated graphics accelerator model.',
  },
  {
    slug: 'gpu-vendor',
    nameRu: 'Производитель GPU (NVIDIA / Apple / AMD / Intel)',
    nameEn: 'GPU Hardware Vendor',
    category: 'hardware',
    descriptionRu: 'Производитель чипсета видеокарты по данным UNMASKED_VENDOR_WEBGL.',
    descriptionEn: 'Graphics processing unit hardware vendor identification.',
  },
  {
    slug: 'gpu-renderer',
    nameRu: 'Рендерер видеокарты (WebGL Renderer)',
    nameEn: 'WebGL GPU Renderer',
    category: 'hardware',
    descriptionRu: 'Полная строка графического драйвера и рендерера WebGL.',
    descriptionEn: 'Complete unmasked graphics driver renderer string.',
  },
  {
    slug: 'webgl-version',
    nameRu: 'Версия WebGL (1.0 / 2.0)',
    nameEn: 'Supported WebGL Version',
    category: 'hardware',
    descriptionRu: 'Проверка поддержки аппаратного ускорения 3D графики в браузере.',
    descriptionEn: 'Support check for 3D hardware-accelerated WebGL APIs.',
  },
  {
    slug: 'webgpu-support',
    nameRu: 'Поддержка WebGPU',
    nameEn: 'WebGPU Next-Gen API Support',
    category: 'hardware',
    descriptionRu: 'Проверка доступности современного стандарта низкоуровневых вычислений WebGPU.',
    descriptionEn: 'Verification of modern low-overhead WebGPU API availability.',
  },
  {
    slug: 'max-texture-size',
    nameRu: 'Максимальный размер текстуры GPU',
    nameEn: 'Maximum WebGL Texture Size',
    category: 'hardware',
    descriptionRu: 'Предельное разрешение текстуры в пикселях (4096, 8192, 16384).',
    descriptionEn: 'Upper bound on dimensions for 2D GPU textures.',
  },

  // ── Browser & Client (14) ──
  {
    slug: 'my-browser',
    nameRu: 'Мой веб-браузер',
    nameEn: 'My Web Browser',
    category: 'browser',
    descriptionRu: 'Точное определение используемого браузера (Chrome, Safari, Firefox, Edge).',
    descriptionEn: 'Accurate identification of active web browser software.',
  },
  {
    slug: 'browser-version',
    nameRu: 'Версия браузера',
    nameEn: 'Browser Version',
    category: 'browser',
    descriptionRu: 'Мажорная и минорная версии клиентского веб-обозревателя.',
    descriptionEn: 'Detailed release and build version of client browser.',
  },
  {
    slug: 'user-agent',
    nameRu: 'Строка User-Agent',
    nameEn: 'User-Agent String',
    category: 'browser',
    descriptionRu: 'Полная сигнатура User-Agent, передаваемая веб-серверам.',
    descriptionEn: 'Full HTTP user-agent header string transmitted to servers.',
  },
  {
    slug: 'cookies-enabled',
    nameRu: 'Статус поддержки Cookies',
    nameEn: 'Cookies Enabled Status',
    category: 'browser',
    descriptionRu: 'Проверка разрешения записи и чтения файлов cookie.',
    descriptionEn: 'Verification whether persistent HTTP cookies are allowed.',
  },
  {
    slug: 'local-storage',
    nameRu: 'Поддержка LocalStorage',
    nameEn: 'LocalStorage Availability',
    category: 'browser',
    descriptionRu: 'Проверка доступности локального постоянного хранилища данных.',
    descriptionEn: 'Check availability of client-side key-value Web Storage.',
  },
  {
    slug: 'session-storage',
    nameRu: 'Поддержка SessionStorage',
    nameEn: 'SessionStorage Availability',
    category: 'browser',
    descriptionRu: 'Проверка доступности сессионного хранилища данных вкладки.',
    descriptionEn: 'Check availability of tab-scoped session storage.',
  },
  {
    slug: 'indexeddb',
    nameRu: 'База данных IndexedDB',
    nameEn: 'IndexedDB Database Support',
    category: 'browser',
    descriptionRu: 'Проверка работоспособности встроенной NoSQL базы данных IndexedDB.',
    descriptionEn: 'Verification of embedded transactional client-side database.',
  },
  {
    slug: 'service-worker',
    nameRu: 'Поддержка Service Workers (PWA)',
    nameEn: 'Service Worker & PWA Support',
    category: 'browser',
    descriptionRu: 'Возможность фоновой синхронизации и оффлайн-работы веб-приложений.',
    descriptionEn: 'Support check for background scripts and offline progressive web app features.',
  },
  {
    slug: 'web-assembly',
    nameRu: 'Поддержка WebAssembly (WASM)',
    nameEn: 'WebAssembly (WASM) Support',
    category: 'browser',
    descriptionRu: 'Проверка поддержки бинарного байт-кода WebAssembly и многопоточности.',
    descriptionEn: 'Detection of fast binary WebAssembly execution engine.',
  },
  {
    slug: 'do-not-track',
    nameRu: 'Флаг приватности (Do Not Track / GPC)',
    nameEn: 'Do Not Track (DNT) / GPC Status',
    category: 'browser',
    descriptionRu: 'Статус клиентского запроса на запрет отслеживания активности.',
    descriptionEn: 'User privacy preference signal regarding third-party tracking.',
  },
  {
    slug: 'pdf-viewer',
    nameRu: 'Встроенный просмотрщик PDF',
    nameEn: 'Native PDF Viewer Support',
    category: 'browser',
    descriptionRu: 'Проверка наличия встроенного модуля визуализации документов PDF.',
    descriptionEn: 'Capability check for direct browser PDF document rendering.',
  },
  {
    slug: 'timezone',
    nameRu: 'Часовой пояс системы (IANA)',
    nameEn: 'System Timezone (IANA)',
    category: 'browser',
    descriptionRu: 'Определение системного часового пояса и смещения относительно UTC.',
    descriptionEn: 'Device local timezone identifier and standard offset from UTC.',
  },
  {
    slug: 'system-language',
    nameRu: 'Основной язык системы',
    nameEn: 'Primary System Language',
    category: 'browser',
    descriptionRu: 'Язык интерфейса операционной системы и браузера по умолчанию.',
    descriptionEn: 'Default language preference of client operating system.',
  },
  {
    slug: 'preferred-languages',
    nameRu: 'Предпочитаемые языки (Accept-Language)',
    nameEn: 'Preferred Languages List',
    category: 'browser',
    descriptionRu: 'Приоритетный список языков пользователя из настроек системы.',
    descriptionEn: 'Prioritized list of accepted human languages for content negotiation.',
  },

  // ── Battery & Power (6) ──
  {
    slug: 'battery',
    nameRu: 'Состояние аккумулятора',
    nameEn: 'Battery & Power Status',
    category: 'battery',
    descriptionRu: 'Комплексный статус аккумулятора и параметров питания устройства.',
    descriptionEn: 'Overall health, level, and power source telemetry for battery.',
  },
  {
    slug: 'battery-level',
    nameRu: 'Уровень заряда батареи (%)',
    nameEn: 'Battery Charge Level (%)',
    category: 'battery',
    descriptionRu: 'Точный процент оставшегося заряда аккумулятора в реальном времени.',
    descriptionEn: 'Real-time remaining percentage of battery capacity.',
  },
  {
    slug: 'battery-charging',
    nameRu: 'Статус подключения к сети (Зарядка)',
    nameEn: 'Battery Charging State',
    category: 'battery',
    descriptionRu: 'Определение подключения кабеля питания или беспроводной зарядки.',
    descriptionEn: 'Indication whether the device is currently drawing power from an external source.',
  },
  {
    slug: 'charging-time',
    nameRu: 'Время до полной зарядки',
    nameEn: 'Time Until Full Charge',
    category: 'battery',
    descriptionRu: 'Расчетное время в минутах до достижения 100% уровня заряда.',
    descriptionEn: 'Estimated time required until battery is completely replenished.',
  },
  {
    slug: 'discharging-time',
    nameRu: 'Расчетное время автономной работы',
    nameEn: 'Estimated Remaining Battery Time',
    category: 'battery',
    descriptionRu: 'Оставшееся время автономной работы при текущей нагрузке.',
    descriptionEn: 'Calculated remaining battery runtime under current energy profile.',
  },
  {
    slug: 'power-saver-mode',
    nameRu: 'Режим энергосбережения',
    nameEn: 'Power Saver / Low Power Mode',
    category: 'battery',
    descriptionRu: 'Проверка активации режима экономии заряда аккумулятора.',
    descriptionEn: 'Heuristic check for low power / battery saver operating state.',
  },

  // ── Operating System (6) ──
  {
    slug: 'operating-system',
    nameRu: 'Операционная система (ОС)',
    nameEn: 'Operating System (OS)',
    category: 'os',
    descriptionRu: 'Определение платформы (Windows, macOS, Linux, iOS, Android).',
    descriptionEn: 'Identification of host operating system environment.',
  },
  {
    slug: 'os-version',
    nameRu: 'Версия операционной системы',
    nameEn: 'OS Build & Release Version',
    category: 'os',
    descriptionRu: 'Детальная сборка и версия ОС по данным Client Hints API.',
    descriptionEn: 'Granular release number and build identifier for host OS.',
  },
  {
    slug: 'platform',
    nameRu: 'Платформа устройства (navigator.platform)',
    nameEn: 'Host Device Platform',
    category: 'os',
    descriptionRu: 'Системный идентификатор платформы (Win32, MacIntel, Linux x86_64).',
    descriptionEn: 'Hardware architecture descriptor string from navigator.platform.',
  },
  {
    slug: 'architecture',
    nameRu: 'Разрядность системы (32-bit / 64-bit)',
    nameEn: 'System Bit Depth (32/64-bit)',
    category: 'os',
    descriptionRu: 'Разрядность адресного пространства операционной системы.',
    descriptionEn: 'Memory address width and architecture bitness of host system.',
  },
  {
    slug: 'dark-mode',
    nameRu: 'Системная темная тема (prefers-color-scheme)',
    nameEn: 'Dark Mode System Preference',
    category: 'os',
    descriptionRu: 'Статус предпочтения темной или светлой темы в оформлении ОС.',
    descriptionEn: 'Evaluation of system-level light or dark color scheme preference.',
  },
  {
    slug: 'reduced-motion',
    nameRu: 'Режим уменьшения анимаций (prefers-reduced-motion)',
    nameEn: 'Reduced Motion Accessibility Preference',
    category: 'os',
    descriptionRu: 'Проверка настройки специальных возможностей для минимизации анимаций.',
    descriptionEn: 'Accessibility preference requesting reduced interface motion and transitions.',
  },
];

export const DIAGNOSTIC_ALIASES: Record<string, string> = {
  webgl: 'webgl-version',
  screen: 'screen-resolution',
  browser: 'my-browser',
  resolution: 'screen-resolution',
  display: 'screen-resolution',
  os: 'operating-system',
  ram: 'ram-memory',
  storage: 'local-storage',
  dns: 'dns-leak',
  vpn: 'proxy-detected',
  touch: 'touch-screen',
};

export const DIAGNOSTIC_SLUGS = [
  ...DIAGNOSTIC_METRICS.map((m) => m.slug),
  ...Object.keys(DIAGNOSTIC_ALIASES),
];

export function getDiagnosticMetric(slug: string): DiagnosticMetric | undefined {
  const normalized = DIAGNOSTIC_ALIASES[slug] || slug;
  return DIAGNOSTIC_METRICS.find((m) => m.slug === normalized);
}
