version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      next-stack:
        patterns:
          - next
          - eslint-config-next
          - "@next/*"
      react-stack:
        patterns:
          - react
          - react-dom
          - "@types/react*"
      radix-ui:
        patterns:
          - "@radix-ui/*"
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
