import type { ComponentMap } from "../../types";

export const components: ComponentMap = {
  "image/compress": () => import("./Compress"),
  "image/resize": () => import("./Resize"),
  "image/convert": () => import("./Convert"),
  "image/crop": () => import("./Crop"),
  "image/orient": () => import("./Orient"),
  "image/filters": () => import("./Filters"),
  "image/censor": () => import("./Censor"),
  "image/watermark": () => import("./Watermark"),
  "image/add-text": () => import("./AddText"),
  "image/collage": () => import("./Collage"),
  "image/split": () => import("./Split"),
  "image/decorate": () => import("./Decorate"),
  "image/exif": () => import("./Exif"),
  "image/dpi": () => import("./Dpi"),
  "image/to-base64": () => import("./ToBase64"),
  "image/base64-to-image": () => import("./Base64ToImage"),
  "image/favicon": () => import("./Favicon"),
  "image/colors": () => import("./Colors"),
  "image/gif-maker": () => import("./GifMaker"),
  "image/gif-frames": () => import("./GifFrames"),
  "image/svg": () => import("./Svg"),
  "image/pixel-art": () => import("./PixelArt"),
  "image/compare": () => import("./Compare"),
  "image/passport": () => import("./PassportPhoto"),
  "image/id-copy": () => import("./IdCopy"),
};
