import type { SchemaType } from "../lib/jsonld";
import type { FieldSpec, L } from "../ui/kit";

export const SCHEMA_NAME: Record<SchemaType, L> = {
  article: { ru: "Статья (Article)", en: "Article" },
  product: { ru: "Товар (Product)", en: "Product" },
  faq: { ru: "Вопросы и ответы (FAQPage)", en: "FAQ (FAQPage)" },
  organization: { ru: "Организация (Organization)", en: "Organization" },
  localBusiness: { ru: "Компания на карте (LocalBusiness)", en: "Local business" },
  breadcrumbs: { ru: "Хлебные крошки (BreadcrumbList)", en: "Breadcrumbs (BreadcrumbList)" },
  event: { ru: "Мероприятие (Event)", en: "Event" },
  recipe: { ru: "Рецепт (Recipe)", en: "Recipe" },
  person: { ru: "Человек (Person)", en: "Person" },
  video: { ru: "Видео (VideoObject)", en: "Video (VideoObject)" },
  jobPosting: { ru: "Вакансия (JobPosting)", en: "Job posting" },
  softwareApp: { ru: "Приложение (SoftwareApplication)", en: "Software app" },
};

const CURRENCIES: [string, string][] = ["RUB", "KZT", "USD", "EUR", "BYN", "UZS", "KGS", "UAH", "GBP", "CNY", "TRY", "AED"].map((c) => [c, c]);

const img: FieldSpec = { key: "image", kind: "textarea", label: { ru: "Картинки — URL, по одному на строку", en: "Images — URLs, one per line" }, rows: 2, mono: true };
const url = (more = false): FieldSpec => ({ key: "url", kind: "text", label: { ru: "Адрес страницы", en: "Page URL" }, inputMode: "url", mono: true, half: true, more });
const addr = (more = false): FieldSpec[] => [
  { key: "street", kind: "text", label: { ru: "Улица, дом", en: "Street address" }, more },
  { key: "city", kind: "text", label: { ru: "Город", en: "City" }, half: true, more },
  { key: "region", kind: "text", label: { ru: "Регион", en: "Region / state" }, half: true, more: true },
  { key: "zip", kind: "text", label: { ru: "Индекс", en: "Postcode" }, half: true, more: true },
  { key: "country", kind: "text", label: { ru: "Страна (код: RU, KZ…)", en: "Country (code: US, GB…)" }, half: true, more },
];

export const SCHEMA_FIELDS: Record<SchemaType, FieldSpec[]> = {
  article: [
    { key: "headline", kind: "text", label: { ru: "Заголовок (headline)", en: "Headline" } },
    { key: "author", kind: "text", label: { ru: "Автор", en: "Author" }, half: true },
    { key: "published", kind: "datetime", label: { ru: "Опубликовано", en: "Published" }, half: true },
    img,
    { key: "kind", kind: "select", label: { ru: "Тип", en: "Type" }, options: [["Article", "Article"], ["NewsArticle", "NewsArticle"], ["BlogPosting", "BlogPosting"]], half: true, more: true },
    { key: "modified", kind: "datetime", label: { ru: "Обновлено", en: "Modified" }, half: true, more: true },
    { key: "authorUrl", kind: "text", label: { ru: "Страница автора", en: "Author URL" }, inputMode: "url", mono: true, half: true, more: true },
    { key: "authorType", kind: "select", label: { ru: "Автор — это", en: "Author is" }, options: [["Person", { ru: "человек", en: "a person" }], ["Organization", { ru: "организация", en: "an organization" }]], half: true, more: true },
    { key: "publisher", kind: "text", label: { ru: "Издатель", en: "Publisher" }, half: true, more: true },
    { key: "logo", kind: "text", label: { ru: "Логотип издателя (URL)", en: "Publisher logo URL" }, inputMode: "url", mono: true, half: true, more: true },
    { key: "description", kind: "textarea", label: { ru: "Описание", en: "Description" }, more: true },
    url(true),
  ],
  product: [
    { key: "name", kind: "text", label: { ru: "Название товара", en: "Product name" } },
    { key: "price", kind: "text", label: { ru: "Цена", en: "Price" }, inputMode: "decimal", half: true },
    { key: "currency", kind: "select", label: { ru: "Валюта", en: "Currency" }, options: CURRENCIES, half: true },
    img,
    {
      key: "availability",
      kind: "select",
      label: { ru: "Наличие", en: "Availability" },
      options: [
        ["InStock", { ru: "в наличии", en: "in stock" }],
        ["OutOfStock", { ru: "нет в наличии", en: "out of stock" }],
        ["PreOrder", { ru: "предзаказ", en: "pre-order" }],
        ["BackOrder", { ru: "под заказ", en: "back order" }],
        ["Discontinued", { ru: "снят с производства", en: "discontinued" }],
      ],
      half: true,
    },
    { key: "brand", kind: "text", label: { ru: "Бренд", en: "Brand" }, half: true },
    { key: "description", kind: "textarea", label: { ru: "Описание", en: "Description" }, more: true },
    { key: "sku", kind: "text", label: { ru: "Артикул (SKU)", en: "SKU" }, half: true, more: true, mono: true },
    { key: "gtin", kind: "text", label: { ru: "Штрихкод GTIN/EAN", en: "GTIN / EAN" }, half: true, more: true, mono: true, inputMode: "numeric" },
    {
      key: "condition",
      kind: "select",
      label: { ru: "Состояние", en: "Condition" },
      options: [
        ["", { ru: "не указывать", en: "omit" }],
        ["NewCondition", { ru: "новый", en: "new" }],
        ["UsedCondition", { ru: "б/у", en: "used" }],
        ["RefurbishedCondition", { ru: "восстановленный", en: "refurbished" }],
      ],
      half: true,
      more: true,
    },
    { key: "validUntil", kind: "date", label: { ru: "Цена действует до", en: "Price valid until" }, half: true, more: true },
    { key: "rating", kind: "text", label: { ru: "Средняя оценка (например 4.7)", en: "Average rating (e.g. 4.7)" }, inputMode: "decimal", half: true, more: true },
    { key: "reviews", kind: "text", label: { ru: "Число отзывов", en: "Review count" }, inputMode: "numeric", half: true, more: true },
    url(true),
  ],
  faq: [
    {
      key: "qa",
      kind: "textarea",
      label: { ru: "Вопросы и ответы: вопрос на первой строке, ответ ниже, пары разделены пустой строкой", en: "Questions and answers: question on the first line, answer below, pairs separated by a blank line" },
      rows: 10,
      placeholder: "Сколько идёт доставка?\nОт 1 до 3 дней по городу.\n\nМожно ли вернуть товар?\nДа, в течение 14 дней.",
    },
  ],
  organization: [
    { key: "name", kind: "text", label: { ru: "Название", en: "Name" }, half: true },
    { key: "url", kind: "text", label: { ru: "Сайт", en: "Website" }, inputMode: "url", mono: true, half: true },
    { key: "logo", kind: "text", label: { ru: "Логотип (URL)", en: "Logo URL" }, inputMode: "url", mono: true },
    { key: "sameAs", kind: "textarea", label: { ru: "Профили в соцсетях и справочниках — по одному на строку", en: "Social and directory profiles — one per line" }, rows: 3, mono: true },
    { key: "kind", kind: "select", label: { ru: "Тип", en: "Type" }, options: [["Organization", "Organization"], ["Corporation", "Corporation"], ["NGO", "NGO"], ["EducationalOrganization", "EducationalOrganization"], ["OnlineStore", "OnlineStore"]], half: true, more: true },
    { key: "phone", kind: "text", label: { ru: "Телефон", en: "Phone" }, inputMode: "tel", half: true, more: true },
    { key: "email", kind: "text", label: { ru: "Email", en: "Email" }, inputMode: "email", half: true, more: true },
    { key: "description", kind: "textarea", label: { ru: "Описание", en: "Description" }, more: true },
  ],
  localBusiness: [
    { key: "name", kind: "text", label: { ru: "Название", en: "Name" }, half: true },
    {
      key: "kind",
      kind: "select",
      label: { ru: "Вид бизнеса", en: "Business type" },
      options: [
        ["LocalBusiness", { ru: "общий (LocalBusiness)", en: "generic (LocalBusiness)" }],
        ["Restaurant", { ru: "ресторан, кафе", en: "restaurant, café" }],
        ["Store", { ru: "магазин", en: "store" }],
        ["BeautySalon", { ru: "салон красоты", en: "beauty salon" }],
        ["Dentist", { ru: "стоматология", en: "dentist" }],
        ["MedicalClinic", { ru: "клиника", en: "medical clinic" }],
        ["AutoRepair", { ru: "автосервис", en: "auto repair" }],
        ["Hotel", { ru: "гостиница", en: "hotel" }],
        ["LegalService", { ru: "юридические услуги", en: "legal service" }],
      ],
      half: true,
    },
    ...addr(),
    { key: "phone", kind: "text", label: { ru: "Телефон", en: "Phone" }, inputMode: "tel", half: true },
    { key: "hours", kind: "textarea", label: { ru: "Часы работы — строки вида «Пн-Пт 9:00-18:00»", en: "Opening hours — lines like “Mo-Fr 09:00-18:00”" }, rows: 2, mono: true },
    { key: "url", kind: "text", label: { ru: "Сайт", en: "Website" }, inputMode: "url", mono: true, half: true, more: true },
    { key: "geo", kind: "text", label: { ru: "Координаты (широта, долгота)", en: "Coordinates (lat, lng)" }, mono: true, half: true, more: true },
    { key: "priceRange", kind: "text", label: { ru: "Уровень цен (₽₽, $$)", en: "Price range ($$)" }, half: true, more: true },
    { ...img, more: true },
  ],
  breadcrumbs: [
    {
      key: "items",
      kind: "textarea",
      label: { ru: "Цепочка: «Название | URL» на строку, от главной к текущей странице", en: "Trail: “Name | URL” per line, from the home page to the current page" },
      rows: 5,
      mono: true,
      placeholder: "Главная | https://example.com/\nКаталог | https://example.com/catalog/\nНоутбуки | https://example.com/catalog/laptops/",
    },
  ],
  event: [
    { key: "name", kind: "text", label: { ru: "Название", en: "Name" } },
    { key: "start", kind: "datetime", label: { ru: "Начало", en: "Starts" }, half: true },
    { key: "end", kind: "datetime", label: { ru: "Окончание", en: "Ends" }, half: true },
    { key: "place", kind: "text", label: { ru: "Площадка", en: "Venue" }, half: true },
    { key: "city", kind: "text", label: { ru: "Город", en: "City" }, half: true },
    { key: "street", kind: "text", label: { ru: "Адрес", en: "Street address" }, half: true },
    { key: "country", kind: "text", label: { ru: "Страна (код)", en: "Country (code)" }, half: true },
    {
      key: "mode",
      kind: "select",
      label: { ru: "Формат", en: "Attendance" },
      options: [
        ["OfflineEventAttendanceMode", { ru: "офлайн", en: "in person" }],
        ["OnlineEventAttendanceMode", { ru: "онлайн", en: "online" }],
        ["MixedEventAttendanceMode", { ru: "смешанный", en: "mixed" }],
      ],
      half: true,
      more: true,
    },
    { key: "onlineUrl", kind: "text", label: { ru: "Ссылка на трансляцию", en: "Stream URL" }, inputMode: "url", mono: true, half: true, more: true },
    {
      key: "status",
      kind: "select",
      label: { ru: "Статус", en: "Status" },
      options: [
        ["EventScheduled", { ru: "по плану", en: "scheduled" }],
        ["EventRescheduled", { ru: "перенесено", en: "rescheduled" }],
        ["EventPostponed", { ru: "отложено", en: "postponed" }],
        ["EventCancelled", { ru: "отменено", en: "cancelled" }],
        ["EventMovedOnline", { ru: "перенесено в онлайн", en: "moved online" }],
      ],
      half: true,
      more: true,
    },
    { key: "price", kind: "text", label: { ru: "Цена билета", en: "Ticket price" }, inputMode: "decimal", half: true, more: true },
    { key: "currency", kind: "select", label: { ru: "Валюта", en: "Currency" }, options: CURRENCIES, half: true, more: true },
    { key: "ticketUrl", kind: "text", label: { ru: "Где купить билет", en: "Ticket URL" }, inputMode: "url", mono: true, half: true, more: true },
    { key: "organizer", kind: "text", label: { ru: "Организатор", en: "Organizer" }, half: true, more: true },
    { key: "description", kind: "textarea", label: { ru: "Описание", en: "Description" }, more: true },
    { ...img, more: true },
  ],
  recipe: [
    { key: "name", kind: "text", label: { ru: "Название блюда", en: "Dish name" } },
    img,
    { key: "prep", kind: "text", label: { ru: "Подготовка, мин", en: "Prep time, min" }, inputMode: "numeric", half: true },
    { key: "cook", kind: "text", label: { ru: "Приготовление, мин", en: "Cook time, min" }, inputMode: "numeric", half: true },
    { key: "ingredients", kind: "textarea", label: { ru: "Ингредиенты — по одному на строку", en: "Ingredients — one per line" }, rows: 4 },
    { key: "steps", kind: "textarea", label: { ru: "Шаги приготовления — по одному на строку", en: "Steps — one per line" }, rows: 4 },
    { key: "yield", kind: "text", label: { ru: "Порций", en: "Servings" }, half: true, more: true },
    { key: "calories", kind: "text", label: { ru: "Калорий на порцию", en: "Calories per serving" }, inputMode: "numeric", half: true, more: true },
    { key: "category", kind: "text", label: { ru: "Категория (десерт, суп…)", en: "Category (dessert, soup…)" }, half: true, more: true },
    { key: "cuisine", kind: "text", label: { ru: "Кухня", en: "Cuisine" }, half: true, more: true },
    { key: "author", kind: "text", label: { ru: "Автор", en: "Author" }, half: true, more: true },
    { key: "description", kind: "textarea", label: { ru: "Описание", en: "Description" }, more: true },
  ],
  person: [
    { key: "name", kind: "text", label: { ru: "Имя и фамилия", en: "Full name" }, half: true },
    { key: "jobTitle", kind: "text", label: { ru: "Должность", en: "Job title" }, half: true },
    { key: "worksFor", kind: "text", label: { ru: "Компания", en: "Works for" }, half: true },
    { key: "url", kind: "text", label: { ru: "Личная страница", en: "Personal page" }, inputMode: "url", mono: true, half: true },
    { key: "sameAs", kind: "textarea", label: { ru: "Профили — по одному на строку", en: "Profiles — one per line" }, rows: 3, mono: true },
    { key: "image", kind: "text", label: { ru: "Фото (URL)", en: "Photo URL" }, inputMode: "url", mono: true, more: true },
  ],
  video: [
    { key: "name", kind: "text", label: { ru: "Название видео", en: "Video title" } },
    { key: "description", kind: "textarea", label: { ru: "Описание", en: "Description" }, rows: 2 },
    { key: "thumbnail", kind: "text", label: { ru: "Превью (URL картинки)", en: "Thumbnail URL" }, inputMode: "url", mono: true },
    { key: "uploaded", kind: "datetime", label: { ru: "Дата загрузки", en: "Upload date" }, half: true },
    { key: "duration", kind: "text", label: { ru: "Длительность (мм:сс)", en: "Duration (mm:ss)" }, placeholder: "4:35", half: true },
    { key: "contentUrl", kind: "text", label: { ru: "Файл видео (URL)", en: "Video file URL" }, inputMode: "url", mono: true, half: true, more: true },
    { key: "embedUrl", kind: "text", label: { ru: "Плеер для встраивания (URL)", en: "Embed URL" }, inputMode: "url", mono: true, half: true, more: true },
  ],
  jobPosting: [
    { key: "title", kind: "text", label: { ru: "Должность", en: "Job title" } },
    { key: "org", kind: "text", label: { ru: "Компания", en: "Company" }, half: true },
    { key: "posted", kind: "date", label: { ru: "Дата публикации", en: "Date posted" }, half: true },
    { key: "description", kind: "textarea", label: { ru: "Описание вакансии", en: "Job description" }, rows: 4 },
    { key: "city", kind: "text", label: { ru: "Город", en: "City" }, half: true },
    { key: "country", kind: "text", label: { ru: "Страна (код)", en: "Country (code)" }, half: true },
    { key: "remote", kind: "checkbox", label: { ru: "Удалённая работа", en: "Remote job" }, half: true },
    {
      key: "employment",
      kind: "select",
      label: { ru: "Занятость", en: "Employment type" },
      options: [
        ["FULL_TIME", { ru: "полная", en: "full-time" }],
        ["PART_TIME", { ru: "частичная", en: "part-time" }],
        ["CONTRACTOR", { ru: "подряд", en: "contractor" }],
        ["TEMPORARY", { ru: "временная", en: "temporary" }],
        ["INTERN", { ru: "стажировка", en: "internship" }],
      ],
      half: true,
    },
    { key: "salaryMin", kind: "text", label: { ru: "Зарплата от", en: "Salary from" }, inputMode: "numeric", half: true, more: true },
    { key: "salaryMax", kind: "text", label: { ru: "Зарплата до", en: "Salary to" }, inputMode: "numeric", half: true, more: true },
    { key: "currency", kind: "select", label: { ru: "Валюта", en: "Currency" }, options: CURRENCIES, half: true, more: true },
    {
      key: "unit",
      kind: "select",
      label: { ru: "За период", en: "Per" },
      options: [
        ["MONTH", { ru: "месяц", en: "month" }],
        ["YEAR", { ru: "год", en: "year" }],
        ["HOUR", { ru: "час", en: "hour" }],
        ["DAY", { ru: "день", en: "day" }],
        ["WEEK", { ru: "неделю", en: "week" }],
      ],
      half: true,
      more: true,
    },
    { key: "validThrough", kind: "date", label: { ru: "Актуальна до", en: "Valid through" }, half: true, more: true },
    { key: "street", kind: "text", label: { ru: "Адрес офиса", en: "Office address" }, half: true, more: true },
    { key: "orgUrl", kind: "text", label: { ru: "Сайт компании", en: "Company website" }, inputMode: "url", mono: true, half: true, more: true },
    { key: "orgLogo", kind: "text", label: { ru: "Логотип компании (URL)", en: "Company logo URL" }, inputMode: "url", mono: true, half: true, more: true },
  ],
  softwareApp: [
    { key: "name", kind: "text", label: { ru: "Название", en: "Name" }, half: true },
    { key: "os", kind: "text", label: { ru: "Платформа (Android, iOS, Windows…)", en: "Operating system (Android, iOS…)" }, half: true },
    {
      key: "category",
      kind: "select",
      label: { ru: "Категория", en: "Category" },
      options: [
        ["BusinessApplication", "BusinessApplication"],
        ["GameApplication", "GameApplication"],
        ["FinanceApplication", "FinanceApplication"],
        ["EducationalApplication", "EducationalApplication"],
        ["UtilitiesApplication", "UtilitiesApplication"],
        ["LifestyleApplication", "LifestyleApplication"],
        ["MultimediaApplication", "MultimediaApplication"],
        ["DeveloperApplication", "DeveloperApplication"],
      ],
      half: true,
    },
    { key: "price", kind: "text", label: { ru: "Цена (0 — бесплатно)", en: "Price (0 = free)" }, inputMode: "decimal", half: true },
    { key: "currency", kind: "select", label: { ru: "Валюта", en: "Currency" }, options: CURRENCIES, half: true },
    { key: "rating", kind: "text", label: { ru: "Средняя оценка", en: "Average rating" }, inputMode: "decimal", half: true, more: true },
    { key: "ratingCount", kind: "text", label: { ru: "Число оценок", en: "Rating count" }, inputMode: "numeric", half: true, more: true },
    { ...url(true), label: { ru: "Страница приложения", en: "App page URL" } },
  ],
};
