import type { L10n } from "@/i18n/config";

/**
 * Human names of emoji groups and subgroups. Emojibase ships machine-translated
 * Russian labels ("mлекопитающих", "ошибки" for bugs…), so they are written here by hand.
 */
export const GROUPS: Record<string, { name: L10n; glyph: string }> = {
  "smileys-emotion": { name: { ru: "Смайлики и эмоции", en: "Smileys & Emotion" }, glyph: "😀" },
  "people-body": { name: { ru: "Люди и тело", en: "People & Body" }, glyph: "👋" },
  "animals-nature": { name: { ru: "Животные и природа", en: "Animals & Nature" }, glyph: "🐶" },
  "food-drink": { name: { ru: "Еда и напитки", en: "Food & Drink" }, glyph: "🍔" },
  "travel-places": { name: { ru: "Путешествия и места", en: "Travel & Places" }, glyph: "✈️" },
  activities: { name: { ru: "Досуг и праздники", en: "Activities & Events" }, glyph: "⚽" },
  objects: { name: { ru: "Предметы", en: "Objects" }, glyph: "💡" },
  symbols: { name: { ru: "Символы и знаки", en: "Symbols & Signs" }, glyph: "🔣" },
  flags: { name: { ru: "Флаги", en: "Flags" }, glyph: "🏁" },
};

export const SUBGROUPS: Record<string, L10n> = {
  "face-smiling": { ru: "Улыбающиеся лица", en: "Smiling faces" },
  "face-affection": { ru: "Влюблённые лица и поцелуи", en: "Affectionate faces" },
  "face-tongue": { ru: "Лица с языком", en: "Faces with tongue" },
  "face-hand": { ru: "Лица с руками", en: "Faces with hands" },
  "face-neutral-skeptical": { ru: "Нейтральные и скептические лица", en: "Neutral & skeptical faces" },
  "face-sleepy": { ru: "Сонные лица", en: "Sleepy faces" },
  "face-unwell": { ru: "Больные лица", en: "Unwell faces" },
  "face-hat": { ru: "Лица в шляпах", en: "Faces with hats" },
  "face-glasses": { ru: "Лица в очках", en: "Faces with glasses" },
  "face-concerned": { ru: "Встревоженные и грустные лица", en: "Concerned & sad faces" },
  "face-negative": { ru: "Злые лица", en: "Angry faces" },
  "face-costume": { ru: "Маски и существа", en: "Costume faces & creatures" },
  "cat-face": { ru: "Кошачьи мордочки", en: "Cat faces" },
  "monkey-face": { ru: "Три обезьянки", en: "Monkey faces" },
  heart: { ru: "Сердечки", en: "Hearts" },
  emotion: { ru: "Символы эмоций", en: "Emotion symbols" },
  "hand-fingers-open": { ru: "Открытые ладони", en: "Open hands" },
  "hand-fingers-partial": { ru: "Жесты пальцами", en: "Finger gestures" },
  "hand-single-finger": { ru: "Указывающие пальцы", en: "Pointing fingers" },
  "hand-fingers-closed": { ru: "Кулаки и сжатые руки", en: "Closed hands" },
  hands: { ru: "Жесты двумя руками", en: "Two-hand gestures" },
  "hand-prop": { ru: "Руки с предметами", en: "Hands with props" },
  "body-parts": { ru: "Части тела", en: "Body parts" },
  person: { ru: "Люди", en: "People" },
  "person-gesture": { ru: "Люди с жестами", en: "Person gestures" },
  "person-role": { ru: "Профессии и роли", en: "Professions & roles" },
  "person-fantasy": { ru: "Сказочные персонажи", en: "Fantasy characters" },
  "person-activity": { ru: "Занятия людей", en: "Person activities" },
  "person-sport": { ru: "Спортсмены", en: "Athletes" },
  "person-resting": { ru: "Отдыхающие люди", en: "Resting people" },
  family: { ru: "Пары и семьи", en: "Couples & families" },
  "person-symbol": { ru: "Силуэты и следы", en: "Person symbols" },
  "animal-mammal": { ru: "Млекопитающие", en: "Mammals" },
  "animal-bird": { ru: "Птицы", en: "Birds" },
  "animal-amphibian": { ru: "Земноводные", en: "Amphibians" },
  "animal-reptile": { ru: "Рептилии", en: "Reptiles" },
  "animal-marine": { ru: "Морские животные", en: "Marine animals" },
  "animal-bug": { ru: "Насекомые и жуки", en: "Bugs & insects" },
  "plant-flower": { ru: "Цветы", en: "Flowers" },
  "plant-other": { ru: "Растения", en: "Plants" },
  "food-fruit": { ru: "Фрукты и ягоды", en: "Fruits" },
  "food-vegetable": { ru: "Овощи", en: "Vegetables" },
  "food-prepared": { ru: "Готовая еда", en: "Prepared food" },
  "food-asian": { ru: "Азиатская кухня", en: "Asian food" },
  "food-marine": { ru: "Морепродукты", en: "Seafood" },
  "food-sweet": { ru: "Сладости и десерты", en: "Sweets & desserts" },
  drink: { ru: "Напитки", en: "Drinks" },
  dishware: { ru: "Посуда", en: "Dishware" },
  "place-map": { ru: "Глобусы и карты", en: "Globes & maps" },
  "place-geographic": { ru: "Горы, пляжи и парки", en: "Geographic places" },
  "place-building": { ru: "Здания", en: "Buildings" },
  "place-religious": { ru: "Храмы", en: "Religious buildings" },
  "place-other": { ru: "Городские виды", en: "City scenes" },
  "transport-ground": { ru: "Наземный транспорт", en: "Ground transport" },
  "transport-water": { ru: "Водный транспорт", en: "Water transport" },
  "transport-air": { ru: "Авиация и космос", en: "Air & space transport" },
  hotel: { ru: "Гостиница", en: "Hotel" },
  time: { ru: "Часы и время", en: "Clocks & time" },
  "sky-weather": { ru: "Небо и погода", en: "Sky & weather" },
  event: { ru: "Праздники и события", en: "Events & celebrations" },
  "award-medal": { ru: "Награды и медали", en: "Awards & medals" },
  sport: { ru: "Спортивный инвентарь", en: "Sports equipment" },
  game: { ru: "Игры", en: "Games" },
  "arts-crafts": { ru: "Искусство и рукоделие", en: "Arts & crafts" },
  clothing: { ru: "Одежда и аксессуары", en: "Clothing & accessories" },
  sound: { ru: "Звук", en: "Sound" },
  music: { ru: "Ноты, микрофоны и наушники", en: "Notes & audio gear" },
  "musical-instrument": { ru: "Музыкальные инструменты", en: "Musical instruments" },
  phone: { ru: "Телефоны", en: "Phones" },
  computer: { ru: "Компьютеры и техника", en: "Computers & devices" },
  "light-video": { ru: "Свет, фото и видео", en: "Light, photo & video" },
  "book-paper": { ru: "Книги и бумага", en: "Books & paper" },
  money: { ru: "Купюры и монеты", en: "Banknotes & coins" },
  mail: { ru: "Почта", en: "Mail" },
  writing: { ru: "Письменные принадлежности", en: "Writing" },
  office: { ru: "Канцелярия", en: "Office supplies" },
  lock: { ru: "Замки и ключи", en: "Locks & keys" },
  tool: { ru: "Инструменты", en: "Tools" },
  science: { ru: "Наука", en: "Science" },
  medical: { ru: "Медицина", en: "Medical" },
  household: { ru: "Бытовые предметы", en: "Household" },
  "other-object": { ru: "Другие предметы", en: "Other objects" },
  "transport-sign": { ru: "Транспортные знаки", en: "Transport signs" },
  warning: { ru: "Предупреждающие знаки", en: "Warning signs" },
  arrow: { ru: "Стрелки", en: "Arrows" },
  religion: { ru: "Религиозные символы", en: "Religious symbols" },
  zodiac: { ru: "Знаки зодиака", en: "Zodiac signs" },
  "av-symbol": { ru: "Кнопки плеера", en: "Audio & video buttons" },
  gender: { ru: "Гендерные символы", en: "Gender symbols" },
  math: { ru: "Математические знаки", en: "Math signs" },
  punctuation: { ru: "Знаки препинания", en: "Punctuation" },
  currency: { ru: "Валюта", en: "Currency" },
  "other-symbol": { ru: "Галочки, значки и прочее", en: "Check marks & other symbols" },
  keycap: { ru: "Цифры на клавишах", en: "Keycaps" },
  alphanum: { ru: "Буквы и надписи", en: "Letters & labels" },
  geometric: { ru: "Цветные фигуры", en: "Colored shapes" },
  flag: { ru: "Флажки", en: "Flag symbols" },
  "country-flag": { ru: "Флаги стран", en: "Country flags" },
  "subdivision-flag": { ru: "Флаги Англии, Шотландии и Уэльса", en: "UK nation flags" },
};

/** Emoji version → [Unicode version, year]. Versions 0.6/0.7 are the retroactive emoji sets of Unicode 6.0 and 7.0. */
export const VERSIONS: Record<string, [string, number]> = {
  "0.6": ["6.0", 2010],
  "0.7": ["7.0", 2014],
  "1": ["8.0", 2015],
  "2": ["8.0", 2015],
  "3": ["9.0", 2016],
  "4": ["9.0", 2016],
  "5": ["10.0", 2017],
  "11": ["11.0", 2018],
  "12": ["12.0", 2019],
  "12.1": ["12.1", 2019],
  "13": ["13.0", 2020],
  "13.1": ["13.0", 2020],
  "14": ["14.0", 2021],
  "15": ["15.0", 2022],
  "15.1": ["15.1", 2023],
  "16": ["16.0", 2024],
};

export const HAIR_NAMES: Record<string, L10n> = {
  red: { ru: "рыжие волосы", en: "red hair" },
  curly: { ru: "кудрявые волосы", en: "curly hair" },
  white: { ru: "седые волосы", en: "white hair" },
  bald: { ru: "без волос", en: "bald" },
};

export const CONTINENTS: Record<string, L10n> = {
  europe: { ru: "Европа", en: "Europe" },
  asia: { ru: "Азия", en: "Asia" },
  africa: { ru: "Африка", en: "Africa" },
  americas: { ru: "Америка", en: "Americas" },
  oceania: { ru: "Океания", en: "Oceania" },
};
