import type { Locale } from "@/i18n/config";
import { plural } from "@/i18n/format";

/** Strings shared by all image tools. Tool-specific strings live in each tool. */
const ru = {
  dropMany: "Перетащите изображения сюда, вставьте Ctrl+V или нажмите, чтобы выбрать",
  dropOne: "Перетащите изображение сюда, вставьте Ctrl+V или нажмите, чтобы выбрать",
  dropHint: "JPG, PNG, WebP, AVIF, HEIC, GIF, BMP, TIFF, SVG, ICO · файлы не покидают устройство",
  addMore: "Добавить ещё",
  files: ["файл", "файла", "файлов"],
  download: "Скачать",
  downloadAll: "Скачать всё (ZIP)",
  zipping: "Упаковка ZIP…",
  remove: "Убрать",
  removeFile: "Убрать файл",
  clear: "Очистить список",
  cancel: "Отменить",
  retry: "Повторить",
  compare: "Сравнить",
  hideCompare: "Скрыть сравнение",
  before: "До",
  after: "После",
  fit: "Вписать",
  actual: "100 %",
  zoomIn: "Увеличить",
  zoomOut: "Уменьшить",
  zoom: "Масштаб",
  queued: "В очереди",
  reading: "Чтение…",
  working: "Обработка…",
  done: "Готово",
  error: "Ошибка",
  original: "Оригинал",
  result: "Результат",
  saved: "меньше",
  grew: "больше",
  keptOriginal: "Оригинал уже меньше — оставлен без изменений",
  animatedWarn: "Анимация: используется только первый кадр",
  limitedWarn: "Изображение меньше заданного размера — увеличение выключено",
  missedTarget: "Даже при минимальном качестве не удалось уложиться в размер",
  outputFormat: "Формат",
  sameFormat: "Как у исходного",
  quality: "Качество",
  background: "Фон",
  backgroundHint: "Для JPG: заливка прозрачных областей",
  settings: "Настройки",
  total: "Итого",
  preview: "Предпросмотр",
  width: "Ширина",
  height: "Высота",
  px: "px",
  color: "Цвет",
  hexInvalid: "Введите цвет в формате #RRGGBB",
  processingIn: "Обработка в браузере",
  errors: {
    UNSUPPORTED: "Формат не распознан — это не изображение или формат не поддерживается",
    PDF: "Это PDF — откройте его в разделе PDF",
    PSD: "PSD (Photoshop) не поддерживается — сохраните файл как PNG или JPG",
    JXL: "JPEG XL пока не поддерживается",
    EMPTY: "Пустой файл",
    SVG_INVALID: "SVG содержит ошибки разметки и не может быть отображён",
    DECODE_FAILED: "Не удалось прочитать изображение — файл повреждён или формат не поддерживается этим браузером",
    NEEDS_MAIN: "Не удалось прочитать изображение",
    TOO_LARGE: "Слишком большое изображение для этого браузера (более 268 Мп или стороны больше 32 767 px)",
    WORKER_CRASHED: "Не хватило памяти браузера — попробуйте изображение поменьше или закройте другие вкладки",
    ENCODE_FAILED: "Браузер не смог сохранить изображение в этом формате",
    CANVAS_UNAVAILABLE: "Браузер не дал доступ к canvas",
    GENERIC: "Не удалось обработать файл",
  } as Record<string, string>,
};

type Dict = { [K in keyof typeof ru]: (typeof ru)[K] extends readonly string[] ? readonly string[] : (typeof ru)[K] };

const en: Dict = {
  dropMany: "Drop images here, paste with Ctrl+V or click to choose",
  dropOne: "Drop an image here, paste with Ctrl+V or click to choose",
  dropHint: "JPG, PNG, WebP, AVIF, HEIC, GIF, BMP, TIFF, SVG, ICO · files never leave your device",
  addMore: "Add more",
  files: ["file", "files"],
  download: "Download",
  downloadAll: "Download all (ZIP)",
  zipping: "Packing ZIP…",
  remove: "Remove",
  removeFile: "Remove file",
  clear: "Clear list",
  cancel: "Cancel",
  retry: "Retry",
  compare: "Compare",
  hideCompare: "Hide comparison",
  before: "Before",
  after: "After",
  fit: "Fit",
  actual: "100%",
  zoomIn: "Zoom in",
  zoomOut: "Zoom out",
  zoom: "Zoom",
  queued: "Queued",
  reading: "Reading…",
  working: "Processing…",
  done: "Done",
  error: "Error",
  original: "Original",
  result: "Result",
  saved: "smaller",
  grew: "larger",
  keptOriginal: "The original is already smaller — kept unchanged",
  animatedWarn: "Animated: only the first frame is used",
  limitedWarn: "The image is smaller than the requested size — enlarging is off",
  missedTarget: "Couldn't reach the size even at minimum quality",
  outputFormat: "Format",
  sameFormat: "Same as source",
  quality: "Quality",
  background: "Background",
  backgroundHint: "For JPG: fills transparent areas",
  settings: "Settings",
  total: "Total",
  preview: "Preview",
  width: "Width",
  height: "Height",
  px: "px",
  color: "Colour",
  hexInvalid: "Enter a colour as #RRGGBB",
  processingIn: "Processed in your browser",
  errors: {
    UNSUPPORTED: "Unknown format — not an image or not supported",
    PDF: "This is a PDF — use the PDF tools instead",
    PSD: "PSD (Photoshop) isn't supported — save it as PNG or JPG",
    JXL: "JPEG XL isn't supported yet",
    EMPTY: "Empty file",
    SVG_INVALID: "The SVG has markup errors and can't be rendered",
    DECODE_FAILED: "Couldn't read the image — the file is damaged or this browser can't decode the format",
    NEEDS_MAIN: "Couldn't read the image",
    TOO_LARGE: "Image too large for this browser (over 268 MP or a side over 32,767 px)",
    WORKER_CRASHED: "The browser ran out of memory — try a smaller image or close other tabs",
    ENCODE_FAILED: "The browser couldn't save the image in this format",
    CANVAS_UNAVAILABLE: "The browser denied canvas access",
    GENERIC: "Couldn't process the file",
  },
};

const DICTS: Record<Locale, Dict> = { ru, en };

export function S(locale: Locale): Dict {
  return DICTS[locale];
}

export function errorText(locale: Locale, e: unknown): string {
  const d = DICTS[locale].errors;
  const code = e instanceof Error ? ((e as Error & { code?: string }).code ?? e.message) : String(e);
  return d[code] ?? d.GENERIC;
}

export function filesCount(locale: Locale, n: number): string {
  return `${n} ${plural(locale, n, DICTS[locale].files)}`;
}
