/**
 * Tool Component Registry
 * Extracted from app/tools/[slug]/ToolPage.tsx
 * Single source of truth for all dynamic tool imports
 * Improves maintainability and reduces code duplication
 */

'use client';

import React from 'react';

type ToolLoaderFn = () => Promise<{ default: React.ComponentType }>;
const dyn = (fn: ToolLoaderFn) => fn;

// ============================================================================
// Tool Component Dynamic Imports (183 canonical public tools)
// ============================================================================

export const toolComponents: Record<string, ToolLoaderFn> = {
  'file-converter': dyn(() => import('@/src/tools/converters/FileConverter')),
  'age-calculator': dyn(() => import('@/src/tools/datetime/AgeCalculator')),
  'angle-converter': dyn(() => import('@/src/tools/converters/AngleConverter')),
  'area-converter': dyn(() => import('@/src/tools/converters/AreaConverter')),
  'avatar-generator': dyn(() => import('@/src/tools/generators/AvatarGenerator')),
  'barcode-gen': dyn(() => import('@/src/tools/qrbarcode/BarcodeGen')),
  'base64-encoder': dyn(() => import('@/src/tools/encoding/Base64Encoder')),
  'binary-text': dyn(() => import('@/src/tools/encoding/BinaryText')),
  // bmi-calc → merged into body-metrics
  // body-fat → merged into body-metrics
  'body-metrics': dyn(() => import('@/src/tools/health/BodyMetrics')),
  'box-shadow': dyn(() => import('@/src/tools/developers/BoxShadowGenerator')),
  'budget-planner': dyn(() => import('@/src/tools/finance/BudgetPlanner')),
  'calendar': dyn(() => import('@/src/tools/datetime/Calendar')),
  // calorie-calc → merged into body-metrics
  'case-converter': dyn(() => import('@/src/tools/text/CaseConverter')),
  'checksum-calc': dyn(() => import('@/src/tools/security/ChecksumCalc')),
  'chmod-calc': dyn(() => import('@/src/tools/developers/ChmodCalculator')),
  'clothing-size': dyn(() => import('@/src/tools/units/ClothingSize')),
  // coin-flip → merged into random-picker
  'color-blender': dyn(() => import('@/src/tools/color/ColorBlender')),
  'color-converter': dyn(() => import('@/src/tools/converters/ColorConverter')),
  'palette-generator': dyn(() => import('@/src/tools/generators/ColorPalette')),
  'color-picker': dyn(() => import('@/src/tools/developers/ColorPicker')),
  'color-wheel': dyn(() => import('@/src/tools/color/ColorWheel')),
  'compound-interest': dyn(() => import('@/src/tools/calculators/CompoundInterest')),
  'contrast-checker': dyn(() => import('@/src/tools/color/ContrastChecker')),
  'cooking-converter': dyn(() => import('@/src/tools/units/CookingConverter')),
  'coordinate-converter': dyn(() => import('@/src/tools/converters/CoordinateConverter')),
  'countdown': dyn(() => import('@/src/tools/entertainment/Countdown')),
  'cron-generator': dyn(() => import('@/src/tools/developers/CronGenerator')),
  'css-animation': dyn(() => import('@/src/tools/developers/CssAnimationBuilder')),
  'css-minifier': dyn(() => import('@/src/tools/developers/CssMinifier')),
  'data-converter': dyn(() => import('@/src/tools/converters/DataConverter')),
  'date-difference': dyn(() => import('@/src/tools/datetime/DateDifference')),
  // decision-maker → merged into random-picker
  'deposit-calc': dyn(() => import('@/src/tools/finance/DepositCalc')),
  // dice-roller → merged into random-picker
  'diff-checker': dyn(() => import('@/src/tools/developers/DiffChecker')),
  'discount-calc': dyn(() => import('@/src/tools/calculators/DiscountCalc')),
  'email-validator': dyn(() => import('@/src/tools/security/EmailValidator')),
  'energy-converter': dyn(() => import('@/src/tools/converters/EnergyConverter')),
  'equation-solver': dyn(() => import('@/src/tools/math/EquationSolver')),
  'factorial-calc': dyn(() => import('@/src/tools/math/FactorialCalc')),
  'favicon-generator': dyn(() => import('@/src/tools/images/FaviconGenerator')),
  'flexbox-playground': dyn(() => import('@/src/tools/developers/FlexboxPlayground')),
  'fraction-calc': dyn(() => import('@/src/tools/math/FractionCalc')),
  'fuel-converter': dyn(() => import('@/src/tools/converters/FuelConverter')),
  'gcd-lcm': dyn(() => import('@/src/tools/math/GcdLcm')),
  'github-readme': dyn(() => import('@/src/tools/developers/GithubReadme')),
  'gradient-generator': dyn(() => import('@/src/tools/generators/GradientGenerator')),
  'graph-plotter': dyn(() => import('@/src/tools/math/GraphPlotter')),
  'grid-playground': dyn(() => import('@/src/tools/developers/GridPlayground')),
  'hash-generator': dyn(() => import('@/src/tools/generators/HashGenerator')),
  'heart-rate-zone': dyn(() => import('@/src/tools/health/HeartRateZone')),
  'html-encoder': dyn(() => import('@/src/tools/encoding/HtmlEncoder')),
  'html-formatter': dyn(() => import('@/src/tools/developers/HtmlFormatter')),
  'http-status': dyn(() => import('@/src/tools/developers/HttpStatus')),
  'iban-validator': dyn(() => import('@/src/tools/security/IbanValidator')),
  // ideal-weight → merged into body-metrics
  'image-colors': dyn(() => import('@/src/tools/color/ImageColors')),
  'image-compressor': dyn(() => import('@/src/tools/images/ImageCompressor')),
  'image-converter': dyn(() => import('@/src/tools/images/ImageConverter')),
  'image-crop': dyn(() => import('@/src/tools/images/ImageCrop')),
  'image-filters': dyn(() => import('@/src/tools/images/ImageFilters')),
  'image-resizer': dyn(() => import('@/src/tools/images/ImageResizer')),
  'image-rotate': dyn(() => import('@/src/tools/images/ImageRotate')),
  'image-to-base64': dyn(() => import('@/src/tools/images/ImageToBase64')),
  'inflation-calc': dyn(() => import('@/src/tools/finance/InflationCalc')),
  'investment-calc': dyn(() => import('@/src/tools/finance/InvestmentCalc')),
  'ip-calculator': dyn(() => import('@/src/tools/network/IpCalculator')),
  'ip-validator': dyn(() => import('@/src/tools/security/IpValidator')),
  'js-beautifier': dyn(() => import('@/src/tools/developers/JsBeautifier')),
  'json-data-gen': dyn(() => import('@/src/tools/security/JsonDataGen')),
  'json-csv': dyn(() => import('@/src/tools/developers/JsonCsvConverter')),
  'json-formatter': dyn(() => import('@/src/tools/developers/JsonFormatter')),
  'jwt-decoder': dyn(() => import('@/src/tools/developers/JwtDecoder')),
  'keyword-density': dyn(() => import('@/src/tools/seo/KeywordDensity')),
  'length-converter': dyn(() => import('@/src/tools/converters/LengthConverter')),
  'loan-calc': dyn(() => import('@/src/tools/calculators/LoanCalc')),
  'lorem-ipsum': dyn(() => import('@/src/tools/text/LoremGenerator')),
  'mac-lookup': dyn(() => import('@/src/tools/network/MacLookup')),
  'markdown-preview': dyn(() => import('@/src/tools/text/MarkdownPreview')),
  'material-colors': dyn(() => import('@/src/tools/color/MaterialColors')),
  'matrix-calc': dyn(() => import('@/src/tools/math/MatrixCalc')),
  'meme-generator': dyn(() => import('@/src/tools/images/MemeGenerator')),
  'metronome': dyn(() => import('@/src/tools/media/Metronome')),
  'mime-types': dyn(() => import('@/src/tools/developers/MimeTypes')),
  'mockdata-generator': dyn(() => import('@/src/tools/generators/MockdataGenerator')),
  'morse-code': dyn(() => import('@/src/tools/encoding/MorseCode')),
  'mortgage-calc': dyn(() => import('@/src/tools/calculators/MortgageCalc')),
  'noise-generator': dyn(() => import('@/src/tools/media/NoiseGenerator')),
  'notes': dyn(() => import('@/src/tools/productivity/Notes')),
  'number-system': dyn(() => import('@/src/tools/converters/NumberSystem')),
  'seo-meta-tool': dyn(() => import('@/src/tools/seo/SeoMetaTool')),
  'paper-size': dyn(() => import('@/src/tools/units/PaperSize')),
  'password-generator': dyn(() => import('@/src/tools/generators/PasswordGenerator')),
  'password-strength': dyn(() => import('@/src/tools/security/PasswordStrength')),
  'percentage-calc': dyn(() => import('@/src/tools/calculators/PercentageCalc')),
  'phone-validator': dyn(() => import('@/src/tools/security/PhoneValidator')),
  'iin-validator': dyn(() => import('@/src/tools/security/IinValidator')),
  'kz-phone-formatter': dyn(() => import('@/src/tools/security/KzPhoneFormatter')),
  'bin-validator': dyn(() => import('@/src/tools/security/BinValidator')),
  'kz-salary-calc': dyn(() => import('@/src/tools/finance/KzSalaryCalculator')),
  'kz-iban-validator': dyn(() => import('@/src/tools/security/KzIbanValidator')),
  'kz-holidays': dyn(() => import('@/src/tools/datetime/KzHolidays')),
  'kz-postal-code': dyn(() => import('@/src/tools/security/KzPostalCode')),
  'kz-address-format': dyn(() => import('@/src/tools/security/KzAddressFormat')),
  'pixel-art': dyn(() => import('@/src/tools/images/PixelArt')),
  'pomodoro': dyn(() => import('@/src/tools/productivity/PomodoroTimer')),
  'port-list': dyn(() => import('@/src/tools/network/PortList')),
  'power-converter': dyn(() => import('@/src/tools/converters/PowerConverter')),
  'pregnancy-calc': dyn(() => import('@/src/tools/health/PregnancyCalc')),
  'pressure-converter': dyn(() => import('@/src/tools/converters/PressureConverter')),
  'prime-checker': dyn(() => import('@/src/tools/math/PrimeChecker')),
  'proportion-calc': dyn(() => import('@/src/tools/math/ProportionCalc')),
  'qr-code-gen': dyn(() => import('@/src/tools/qrbarcode/QrCodeGen')),
  'random-color': dyn(() => import('@/src/tools/entertainment/RandomColor')),
  'random-name': dyn(() => import('@/src/tools/generators/RandomName')),
  'random-number': dyn(() => import('@/src/tools/generators/RandomNumber')),
  'random-picker': dyn(() => import('@/src/tools/entertainment/RandomPicker')),
  // reading-time → merged into text-analyzer
  'regex-library': dyn(() => import('@/src/tools/developers/RegexLibrary')),
  'regex-tester': dyn(() => import('@/src/tools/developers/RegexTester')),
  'remove-duplicates': dyn(() => import('@/src/tools/text/RemoveDuplicates')),
  'retirement-calc': dyn(() => import('@/src/tools/finance/RetirementCalc')),
  'robots-generator': dyn(() => import('@/src/tools/seo/RobotsGenerator')),
  'roman-numerals': dyn(() => import('@/src/tools/math/RomanNumerals')),
  'salary-calc': dyn(() => import('@/src/tools/calculators/SalaryCalc')),
  'scientific-calc': dyn(() => import('@/src/tools/calculators/ScientificCalc')),
  'screen-resolution': dyn(() => import('@/src/tools/units/ScreenResolution')),
  'shoe-size': dyn(() => import('@/src/tools/units/ShoeSize')),
  'sitemap-generator': dyn(() => import('@/src/tools/seo/SitemapGenerator')),
  'sleep-calc': dyn(() => import('@/src/tools/health/SleepCalc')),
  'slug-generator': dyn(() => import('@/src/tools/generators/SlugGenerator')),
  'speaker-dryer': dyn(() => import('@/src/tools/media/SpeakerDryer')),
  'symbol-catalog': dyn(() => import('@/src/tools/symbols/SymbolCatalog')),
  // symbols-animals..typography → merged into symbol-catalog
  'speed-converter': dyn(() => import('@/src/tools/converters/SpeedConverter')),
  'sql-formatter': dyn(() => import('@/src/tools/developers/SqlFormatter')),
  'statistics-calc': dyn(() => import('@/src/tools/math/StatisticsCalc')),
  'string-extractor': dyn(() => import('@/src/tools/text/StringExtractor')),
  'subnet-calc': dyn(() => import('@/src/tools/network/SubnetCalc')),
  'svg-editor': dyn(() => import('@/src/tools/images/SvgEditor')),
  'text-analyzer': dyn(() => import('@/src/tools/text/TextAnalyzer')),
  'tailwind-colors': dyn(() => import('@/src/tools/color/TailwindColors')),
  'tax-calc': dyn(() => import('@/src/tools/calculators/TaxCalc')),
  'team-generator': dyn(() => import('@/src/tools/entertainment/TeamGenerator')),
  'text-extractor': dyn(() => import('@/src/tools/seo/TextExtractor')),
  'temperature-converter': dyn(() => import('@/src/tools/converters/TemperatureConverter')),
  'text-cleaner': dyn(() => import('@/src/tools/text/TextCleaner')),
  // text-diff → merged into diff-checker
  'text-formatter': dyn(() => import('@/src/tools/text/TextFormatter')),
  'text-replace': dyn(() => import('@/src/tools/text/TextReplace')),
  'text-reverse': dyn(() => import('@/src/tools/text/TextReverse')),
  'text-sort': dyn(() => import('@/src/tools/text/TextSort')),
  'text-to-speech': dyn(() => import('@/src/tools/text/TextToSpeech')),
  'timer': dyn(() => import('@/src/tools/datetime/Timer')),
  'timezone-converter': dyn(() => import('@/src/tools/datetime/TimezoneConverter')),
  'tip-calc': dyn(() => import('@/src/tools/calculators/TipCalculator')),
  'todo-list': dyn(() => import('@/src/tools/productivity/TodoList')),
  // token-counter → merged into text-analyzer
  // tone-generator → merged into noise-generator
  'transliteration': dyn(() => import('@/src/tools/text/Transliteration')),
  'typing-speed': dyn(() => import('@/src/tools/productivity/TypingSpeed')),
  'unicode-lookup': dyn(() => import('@/src/tools/symbols/UnicodeLookup')),
  'unix-timestamp': dyn(() => import('@/src/tools/datetime/UnixTimestamp')),
  'url-encoder': dyn(() => import('@/src/tools/encoding/UrlEncoder')),
  'url-validator': dyn(() => import('@/src/tools/security/UrlValidator')),
  'user-agent-parser': dyn(() => import('@/src/tools/network/UserAgentParser')),
  'uuid-generator': dyn(() => import('@/src/tools/generators/UuidGenerator')),
  'video-aspect': dyn(() => import('@/src/tools/media/VideoAspect')),
  'volume-converter': dyn(() => import('@/src/tools/converters/VolumeConverter')),
  'water-intake': dyn(() => import('@/src/tools/health/WaterIntake')),
  'week-number': dyn(() => import('@/src/tools/datetime/WeekNumber')),
  'weight-converter': dyn(() => import('@/src/tools/converters/WeightConverter')),
  // wheel-spinner → merged into random-picker
  // word-counter → merged into text-analyzer
  'world-clock': dyn(() => import('@/src/tools/datetime/WorldClock')),
  'xml-formatter': dyn(() => import('@/src/tools/developers/XmlFormatter')),
  'yaml-json': dyn(() => import('@/src/tools/developers/YamlJson')),
  // PDF tools
  'pdf-studio': dyn(() => import('@/src/tools/pdf/PdfStudio')),
  'compress-pdf': dyn(() => import('@/src/tools/pdf/CompressPdf')),
  'merge-pdf': dyn(() => import('@/src/tools/pdf/MergePdf')),
  'split-pdf': dyn(() => import('@/src/tools/pdf/SplitPdf')),
  'rotate-pdf': dyn(() => import('@/src/tools/pdf/RotatePdf')),
  // remove-pages-pdf → merged into split-pdf
  'watermark-pdf': dyn(() => import('@/src/tools/pdf/WatermarkPdf')),
  // esign-pdf → merged into pdf-studio
  'pdf-metadata': dyn(() => import('@/src/tools/pdf/PdfMetadata')),
  'protect-pdf': dyn(() => import('@/src/tools/pdf/ProtectPdf')),
  'jpg-to-pdf': dyn(() => import('@/src/tools/pdf/JpgToPdf')),
  'word-to-pdf': dyn(() => import('@/src/tools/pdf/WordToPdf')),
  // pdf-to-jpg → merged into pdf-to-image
  'pdf-to-word': dyn(() => import('@/src/tools/pdf/PdfToWord')),
  'pdf-to-text': dyn(() => import('@/src/tools/pdf/PdfToText')),
  'pdf-to-image': dyn(() => import('@/src/tools/pdf/PdfToImage')),
  // pdf-to-png → merged into pdf-to-image
  // New image tools
  // blur-image → merged into image-filters
  'watermark-image': dyn(() => import('@/src/tools/images/WatermarkImage')),
  'html-to-image': dyn(() => import('@/src/tools/images/HtmlToImage')),
  'youtube-thumbnail': dyn(() => import('@/src/tools/images/YoutubeThumbnail')),
};
