/**
 * Library of ready regular expressions. Every example is verified by
 * tests/unit/regex-library.test.ts. "full" patterns validate a whole string (anchored);
 * "find" patterns search inside text.
 */

type L = { ru: string; en: string };

export type Category = "web" | "numbers" | "datetime" | "text" | "ru-kz" | "id" | "code";

export interface LibPattern {
  slug: string;
  name: L;
  category: Category;
  pattern: string;
  flags: string;
  mode: "full" | "find";
  what: L;
  limits: L;
  match: string[];
  noMatch: string[];
}

const IPV4 = "(?:(?:25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)\\.){3}(?:25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)";
const H = "[0-9A-Fa-f]{1,4}";
const IPV6 = [
  `(?:${H}:){7}${H}`,
  `(?:${H}:){1,7}:`,
  `(?:${H}:){1,6}:${H}`,
  `(?:${H}:){1,5}(?::${H}){1,2}`,
  `(?:${H}:){1,4}(?::${H}){1,3}`,
  `(?:${H}:){1,3}(?::${H}){1,4}`,
  `(?:${H}:){1,2}(?::${H}){1,5}`,
  `${H}:(?::${H}){1,6}`,
  `:(?:(?::${H}){1,7}|:)`,
  `(?:${H}:){6}${IPV4}`,
  `::(?:[Ff]{4}(?::0{1,4})?:)?${IPV4}`,
  `(?:${H}:){1,4}:${IPV4}`,
].join("|");
const RGB = "(?:25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)";
const LABEL = "[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?";
const TLD = "(?:[A-Za-z]{2,63}|xn--[A-Za-z0-9-]{2,59})";
const KZ_LETTERS = "А-ЯЁа-яёӘәҒғҚқҢңӨөҰұҮүҺһІі";
const PLATE = "АВЕКМНОРСТУХ";

export const LIBRARY: LibPattern[] = [
  /* ───────────── web ───────────── */
  {
    slug: "email",
    name: { ru: "E-mail", en: "Email" },
    category: "web",
    pattern: `^(?!\\.)(?!.*\\.\\.)[A-Za-z0-9._%+-]+(?<!\\.)@${LABEL}(?:\\.${LABEL})*\\.${TLD}$`,
    flags: "",
    mode: "full",
    what: { ru: "адрес электронной почты: имя, @, домен с точкой и зоной (в том числе xn--)", en: "an email address: local part, @, a dotted domain with a TLD (xn-- included)" },
    limits: { ru: "Это практичное подмножество RFC 5322: кавычки, IP-адреса в скобках и кириллица в имени не поддерживаются. Существует ли ящик, регулярное выражение не проверит.", en: "A practical subset of RFC 5322: quoted local parts, IP literals and non-ASCII local parts aren't supported. It can't tell whether the mailbox exists." },
    match: ["user@example.com", "first.last+tag@sub.domain.kz", "info@xn--e1afmkfd.xn--p1ai", "a_b-c%1@mail.ru"],
    noMatch: ["plainaddress", "user@", "user@domain", ".user@example.com", "user..name@example.com", "user@-example.com"],
  },
  {
    slug: "url",
    name: { ru: "URL (ссылка)", en: "URL" },
    category: "web",
    pattern: `^https?:\\/\\/(?:${LABEL}\\.)+${TLD}(?::\\d{1,5})?(?:[/?#][^\\s]*)?$`,
    flags: "i",
    mode: "full",
    what: { ru: "ссылка http или https с доменом, необязательным портом, путём, параметрами и якорем", en: "an http or https link with a domain, optional port, path, query and fragment" },
    limits: { ru: "IP-адреса, localhost и домены на кириллице (без Punycode) не принимаются. Для полной проверки используйте new URL() в коде.", en: "IP addresses, localhost and non-ASCII domains (not in Punycode) aren't accepted. Use new URL() for full validation." },
    match: ["https://example.com", "http://sub.example.co.uk/path?q=1#top", "https://xn--e1afmkfd.xn--p1ai/", "https://example.com:8080/a/b"],
    noMatch: ["example.com", "ftp://example.com", "https://", "http://exa mple.com", "https://-bad.com"],
  },
  {
    slug: "domain",
    name: { ru: "Доменное имя (с .рф и .қаз)", en: "Domain name (incl. IDN)" },
    category: "web",
    pattern: "^(?=.{1,253}$)(?:(?!-)[\\p{L}\\p{N}-]{1,63}(?<!-)\\.)+(?:\\p{L}{2,63}|xn--[a-z0-9-]{2,59})$",
    flags: "iu",
    mode: "full",
    what: { ru: "домен из меток до 63 символов, включая кириллические (пример.рф, сайт.қаз) и Punycode", en: "a domain of labels up to 63 characters, including Unicode (IDN) and Punycode labels" },
    limits: { ru: "Не проверяет, существует ли домен и разрешены ли символы в конкретной зоне; метки не должны начинаться и заканчиваться дефисом.", en: "It doesn't check whether the domain exists or which characters a zone allows; labels can't start or end with a hyphen." },
    match: ["example.com", "sub.example.kz", "пример.рф", "сайт.қаз", "xn--e1afmkfd.xn--p1ai"],
    noMatch: ["-example.com", "example-.com", "example", "exa_mple.com", `${"a".repeat(64)}.com`],
  },
  {
    slug: "ipv4",
    name: { ru: "IPv4-адрес", en: "IPv4 address" },
    category: "web",
    pattern: `^${IPV4}$`,
    flags: "",
    mode: "full",
    what: { ru: "четыре числа от 0 до 255 через точку, без ведущих нулей", en: "four numbers 0–255 separated by dots, without leading zeros" },
    limits: { ru: "Ведущие нули (192.168.01.1) отклоняются: многие программы читают их как восьмеричные числа.", en: "Leading zeros (192.168.01.1) are rejected: many programs read them as octal." },
    match: ["192.168.1.1", "0.0.0.0", "255.255.255.255", "10.0.0.254"],
    noMatch: ["256.1.1.1", "192.168.01.1", "1.2.3", "1.2.3.4.5", "192.168.1."],
  },
  {
    slug: "ipv6",
    name: { ru: "IPv6-адрес", en: "IPv6 address" },
    category: "web",
    pattern: `^(?:${IPV6})$`,
    flags: "",
    mode: "full",
    what: { ru: "IPv6 во всех сокращённых формах (::, ::1, 2001:db8::1) и с IPv4 в конце (::ffff:192.0.2.1)", en: "IPv6 in every compressed form (::, ::1, 2001:db8::1) and with an embedded IPv4 (::ffff:192.0.2.1)" },
    limits: { ru: "Идентификатор зоны (%eth0) и квадратные скобки URL не принимаются — отделите их заранее.", en: "Zone IDs (%eth0) and URL brackets aren't accepted — strip them first." },
    match: ["2001:db8::1", "::1", "::", "fe80::1ff:fe23:4567:890a", "2001:0db8:85a3:0000:0000:8a2e:0370:7334", "::ffff:192.0.2.128", "1::"],
    noMatch: ["2001:db8::1::1", "12345::1", "2001:db8:::1", "fe80::1%eth0", "1:2:3:4:5:6:7:8:9", ":1"],
  },
  {
    slug: "ipv4-cidr",
    name: { ru: "IPv4-подсеть (CIDR)", en: "IPv4 CIDR block" },
    category: "web",
    pattern: `^${IPV4}\\/(?:3[0-2]|[12]?\\d)$`,
    flags: "",
    mode: "full",
    what: { ru: "адрес IPv4 и длина маски от 0 до 32 через косую черту", en: "an IPv4 address and a prefix length 0–32 after a slash" },
    limits: { ru: "Не проверяет, что адрес — начало сети (10.0.0.5/8 тоже подходит).", en: "It doesn't check that the address is the network start (10.0.0.5/8 matches too)." },
    match: ["10.0.0.0/8", "192.168.1.0/24", "0.0.0.0/0", "172.16.0.0/12"],
    noMatch: ["10.0.0.0/33", "10.0.0.0", "256.0.0.0/8", "10.0.0.0/-1"],
  },
  {
    slug: "mac-address",
    name: { ru: "MAC-адрес", en: "MAC address" },
    category: "web",
    pattern: "^[0-9A-Fa-f]{2}([:-])(?:[0-9A-Fa-f]{2}\\1){4}[0-9A-Fa-f]{2}$|^[0-9A-Fa-f]{4}\\.[0-9A-Fa-f]{4}\\.[0-9A-Fa-f]{4}$",
    flags: "",
    mode: "full",
    what: { ru: "шесть байт через двоеточие или дефис (один и тот же разделитель) либо формат Cisco 0000.0000.0000", en: "six bytes separated by colons or hyphens (consistently) or the Cisco 0000.0000.0000 form" },
    limits: { ru: "Смешанные разделители отклоняются благодаря обратной ссылке \\1; запись без разделителей не поддерживается.", en: "Mixed separators are rejected thanks to the \\1 backreference; the separator-less form isn't supported." },
    match: ["00:1A:2B:3C:4D:5E", "00-1a-2b-3c-4d-5e", "001a.2b3c.4d5e", "ff:ff:ff:ff:ff:ff"],
    noMatch: ["00:1A:2B:3C:4D", "00:1A-2B:3C:4D:5E", "00:1G:2B:3C:4D:5E", "001A2B3C4D5E"],
  },
  {
    slug: "port-number",
    name: { ru: "Номер порта", en: "Port number" },
    category: "web",
    pattern: "^(?:6553[0-5]|655[0-2]\\d|65[0-4]\\d{2}|6[0-4]\\d{3}|[1-5]\\d{4}|[1-9]\\d{0,3}|0)$",
    flags: "",
    mode: "full",
    what: { ru: "число от 0 до 65535 без ведущих нулей", en: "a number from 0 to 65535 without leading zeros" },
    limits: { ru: "Порт 0 допустим синтаксически, но обычно означает «выбрать любой свободный».", en: "Port 0 is valid syntax but usually means “pick any free port”." },
    match: ["80", "443", "65535", "0"],
    noMatch: ["65536", "080", "-1", "99999"],
  },
  {
    slug: "hex-color",
    name: { ru: "HEX-цвет", en: "Hex color" },
    category: "web",
    pattern: "^#(?:[0-9A-Fa-f]{3,4}|[0-9A-Fa-f]{6}|[0-9A-Fa-f]{8})$",
    flags: "",
    mode: "full",
    what: { ru: "цвет CSS: # и 3, 4, 6 или 8 шестнадцатеричных цифр (с прозрачностью)", en: "a CSS color: # and 3, 4, 6 or 8 hex digits (with alpha)" },
    limits: { ru: "Имена цветов (red) и функции rgb() не принимаются.", en: "Color names (red) and rgb() functions aren't accepted." },
    match: ["#fff", "#FFAA00", "#ffaa0080", "#abcd"],
    noMatch: ["fff", "#ff", "#12345", "#ggg", "#1234567"],
  },
  {
    slug: "rgb-color",
    name: { ru: "Цвет rgb() / rgba()", en: "rgb() / rgba() color" },
    category: "web",
    pattern: `^rgba?\\(\\s*${RGB}\\s*,\\s*${RGB}\\s*,\\s*${RGB}\\s*(?:,\\s*(?:0|1|0?\\.\\d+)\\s*)?\\)$`,
    flags: "",
    mode: "full",
    what: { ru: "rgb(r, g, b) или rgba(r, g, b, a) с каналами 0–255 и прозрачностью от 0 до 1", en: "rgb(r, g, b) or rgba(r, g, b, a) with channels 0–255 and alpha 0–1" },
    limits: { ru: "Новая запись через пробелы и проценты (rgb(0 0 0 / 50%)) не поддерживается.", en: "The newer space syntax with percentages (rgb(0 0 0 / 50%)) isn't supported." },
    match: ["rgb(255, 0, 128)", "rgba(0,0,0,0.5)", "rgb(12,34,56)", "rgba(10, 20, 30, 1)"],
    noMatch: ["rgb(256,0,0)", "rgb(1,2)", "rgba(1,2,3,1.5)", "rgb 1,2,3"],
  },
  {
    slug: "slug",
    name: { ru: "Slug (ЧПУ)", en: "URL slug" },
    category: "web",
    pattern: "^[a-z0-9]+(?:-[a-z0-9]+)*$",
    flags: "",
    mode: "full",
    what: { ru: "строчные латинские буквы и цифры, слова через одинарный дефис", en: "lowercase letters and digits, words joined by single hyphens" },
    limits: { ru: "Кириллица, подчёркивания и заглавные буквы не допускаются — сначала сделайте транслитерацию.", en: "Uppercase letters, underscores and non-ASCII characters aren't allowed." },
    match: ["hello-world", "uuid-v7", "2025-report", "a"],
    noMatch: ["Hello-World", "hello--world", "-hello", "hello_world"],
  },
  {
    slug: "url-query-param",
    name: { ru: "Параметры строки запроса", en: "URL query parameters" },
    category: "web",
    pattern: "[?&]([^=&#\\s]+)=?([^&#\\s]*)",
    flags: "g",
    mode: "find",
    what: { ru: "пары «ключ=значение» после ? и &; группа 1 — ключ, группа 2 — значение", en: "key=value pairs after ? and &; group 1 is the key, group 2 the value" },
    limits: { ru: "Значения не раскодируются из %XX — для этого используйте URLSearchParams.", en: "Values aren't percent-decoded — use URLSearchParams for that." },
    match: ["https://x.com/?a=1", "?q=test&page=2", "/p?flag"],
    noMatch: ["https://x.com/path", "no query", "#anchor=1"],
  },
  {
    slug: "youtube-video-id",
    name: { ru: "ID видео YouTube", en: "YouTube video ID" },
    category: "web",
    pattern: "(?:youtube\\.com\\/(?:watch\\?(?:[^#\\s]*&)?v=|embed\\/|shorts\\/|live\\/)|youtu\\.be\\/)([A-Za-z0-9_-]{11})",
    flags: "g",
    mode: "find",
    what: { ru: "11-символьный ID из ссылок youtube.com/watch, youtu.be, /embed, /shorts и /live (группа 1)", en: "the 11-character ID from youtube.com/watch, youtu.be, /embed, /shorts and /live links (group 1)" },
    limits: { ru: "Не проверяет, существует ли видео.", en: "It doesn't check that the video exists." },
    match: ["https://www.youtube.com/watch?v=dQw4w9WgXcQ", "https://youtu.be/dQw4w9WgXcQ?t=42", "https://www.youtube.com/shorts/abcdefghijk", "https://youtube.com/embed/dQw4w9WgXcQ"],
    noMatch: ["https://vimeo.com/123456", "https://youtube.com/watch?v=short", "https://example.com/watch?v=dQw4w9WgXcQ"],
  },
  /* ───────────── identifiers ───────────── */
  {
    slug: "uuid",
    name: { ru: "UUID", en: "UUID" },
    category: "id",
    pattern: "^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$",
    flags: "i",
    mode: "full",
    what: { ru: "UUID версий 1–8 с вариантом RFC 9562 в записи 8-4-4-4-12", en: "a UUID of versions 1–8 with the RFC 9562 variant in 8-4-4-4-12 form" },
    limits: { ru: "Nil и Max UUID (все нули или все f) сюда не проходят; запись без дефисов тоже.", en: "The Nil and Max UUIDs (all zeros / all f) don't match, nor does the dash-less form." },
    match: ["017f22e2-79b0-7cc3-98c4-dc0c0c07398f", "C232AB00-9414-11EC-B3C8-9F6BDECED846", "2ed6657d-e927-568b-95e1-2665a8aea6a2", "f47ac10b-58cc-4372-a567-0e02b2c3d479"],
    noMatch: ["00000000-0000-0000-0000-000000000000", "f47ac10b58cc4372a5670e02b2c3d479", "f47ac10b-58cc-4372-c567-0e02b2c3d479", "f47ac10b-58cc-4372-a567-0e02b2c3d47"],
  },
  {
    slug: "username",
    name: { ru: "Имя пользователя (логин)", en: "Username" },
    category: "id",
    pattern: "^(?=.{3,20}$)[A-Za-z](?:[A-Za-z0-9]|[._](?![._]))*[A-Za-z0-9]$",
    flags: "",
    mode: "full",
    what: { ru: "3–20 символов: начинается с буквы, содержит латиницу, цифры, точки и подчёркивания без повторов подряд и не заканчивается ими", en: "3–20 characters: starts with a letter; letters, digits, dots and underscores, no doubled separators, not at the end" },
    limits: { ru: "Правила логина у каждого сервиса свои — меняйте длину и набор символов под себя.", en: "Every service has its own rules — adjust the length and characters." },
    match: ["john_doe", "alice.smith", "user123", "Bob"],
    noMatch: ["1user", "ab", "user.", "us..er", "_user", "averyveryverylongusername1"],
  },
  {
    slug: "telegram-username",
    name: { ru: "Username в Telegram", en: "Telegram username" },
    category: "id",
    pattern: "^@?[a-zA-Z](?:[a-zA-Z0-9]|_(?!_)){3,30}[a-zA-Z0-9]$",
    flags: "",
    mode: "full",
    what: { ru: "5–32 символа: латиница, цифры и подчёркивания, начинается с буквы, @ в начале необязателен", en: "5–32 characters: letters, digits and underscores, starting with a letter; the leading @ is optional" },
    limits: { ru: "Занят ли ник, проверить регулярным выражением нельзя.", en: "Whether the name is taken can't be checked with a regex." },
    match: ["@durov", "telegram_bot", "@Some_User1", "abcde"],
    noMatch: ["@abc", "_user", "user_", "1user"],
  },
  {
    slug: "mention",
    name: { ru: "Упоминание @username", en: "@mention" },
    category: "id",
    pattern: "(?<![\\p{L}\\p{N}_.@])@[A-Za-z0-9_]{1,32}(?![A-Za-z0-9_])",
    flags: "gu",
    mode: "find",
    what: { ru: "упоминания вида @username в тексте, но не адреса почты", en: "@username mentions in text, but not e-mail addresses" },
    limits: { ru: "Длина ника зависит от сервиса: в X (Twitter) до 15 символов, в Telegram — от 5 до 32.", en: "Username length depends on the service: up to 15 on X (Twitter), 5–32 on Telegram." },
    match: ["hi @john_doe", "@alice", "cc @bob123 please"],
    noMatch: ["user@example.com", "@ alone", "no mentions"],
  },
  {
    slug: "hashtag",
    name: { ru: "Хэштег", en: "Hashtag" },
    category: "text",
    pattern: "(?<![\\p{L}\\p{N}_])#[\\p{L}\\p{N}_]+",
    flags: "gu",
    mode: "find",
    what: { ru: "хэштеги на любом языке: #казахстан, #tbt, #2025", en: "hashtags in any language: #tbt, #2025, #казахстан" },
    limits: { ru: "Правила соцсетей отличаются: например, хэштег только из цифр в Instagram не работает.", en: "Networks differ: a digits-only hashtag, for example, doesn't work on Instagram." },
    match: ["Привет #казахстан", "#tbt photo", "go #2025"],
    noMatch: ["email#fragment", "# space", "no tags here"],
  },
  {
    slug: "jwt",
    name: { ru: "JWT-токен", en: "JWT token" },
    category: "id",
    pattern: "^[A-Za-z0-9_-]{2,}\\.[A-Za-z0-9_-]{2,}\\.[A-Za-z0-9_-]*$",
    flags: "",
    mode: "full",
    what: { ru: "три части в Base64url через точку; подпись может быть пустой (alg: none)", en: "three dot-separated Base64url parts; the signature may be empty (alg: none)" },
    limits: { ru: "Проверяет только форму. Раскодируйте токен и проверьте подпись в JWT-декодере.", en: "It only checks the shape. Decode it and verify the signature with a JWT decoder." },
    match: ["eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c", "eyJhbGciOiJub25lIn0.eyJzdWIiOiIxIn0.", "ab.cd.ef"],
    noMatch: ["abc.def", "eyJ.eyJ.sig.extra", "eyJ hbGc.x.y", "a+b.c.d"],
  },
  {
    slug: "base64",
    name: { ru: "Строка Base64", en: "Base64 string" },
    category: "code",
    pattern: "^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$",
    flags: "",
    mode: "full",
    what: { ru: "Base64 со стандартным алфавитом и правильным дополнением =", en: "standard-alphabet Base64 with correct = padding" },
    limits: { ru: "Пустая строка тоже подходит. URL-safe Base64 (- и _) и строки без = не проходят.", en: "An empty string matches too. URL-safe Base64 (- and _) and unpadded strings don't." },
    match: ["TWFu", "TWE=", "TQ==", "SGVsbG8gd29ybGQ="],
    noMatch: ["TWF", "TWE==", "T===", "SGVs bG8=", "-_8="],
  },
  {
    slug: "semver",
    name: { ru: "Версия SemVer", en: "Semantic version" },
    category: "code",
    pattern: "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$",
    flags: "",
    mode: "full",
    what: { ru: "версия MAJOR.MINOR.PATCH с пререлизом и метаданными — официальное выражение с semver.org", en: "MAJOR.MINOR.PATCH with pre-release and build metadata — the official semver.org pattern" },
    limits: { ru: "Префикс v (v1.2.3) не входит в SemVer — уберите его перед проверкой.", en: "A v prefix (v1.2.3) isn't part of SemVer — strip it first." },
    match: ["1.0.0", "2.10.3-beta.1", "1.0.0-alpha+001", "0.0.1"],
    noMatch: ["1.0", "01.0.0", "1.0.0-", "v1.0.0", "1.0.0-01"],
  },
  {
    slug: "html-tag",
    name: { ru: "HTML-тег", en: "HTML tag" },
    category: "code",
    pattern: "<\\/?[A-Za-z][A-Za-z0-9-]*(?:\\s+[^\\s\"'>/=]+(?:\\s*=\\s*(?:\"[^\"]*\"|'[^']*'|[^\\s\"'=<>`]+))?)*\\s*\\/?>",
    flags: "g",
    mode: "find",
    what: { ru: "открывающие, закрывающие и самозакрывающиеся теги с атрибутами", en: "opening, closing and self-closing tags with attributes" },
    limits: { ru: "HTML нельзя надёжно разобрать регулярными выражениями: комментарии, скрипты и вложенность требуют настоящего парсера.", en: "HTML can't be reliably parsed with regex: comments, scripts and nesting need a real parser." },
    match: ["<div>", '<a href="x">', "</p>", "<br/>", "<input disabled>"],
    noMatch: ["a < b", "<>", "< div>", "plain text"],
  },
  {
    slug: "html-attribute",
    name: { ru: "HTML-атрибут", en: "HTML attribute" },
    category: "code",
    pattern: "([A-Za-z_:][-A-Za-z0-9_:.]*)\\s*=\\s*(\"[^\"]*\"|'[^']*'|[^\\s\"'=<>`]+)",
    flags: "g",
    mode: "find",
    what: { ru: "атрибуты вида имя=\"значение\": группа 1 — имя, группа 2 — значение с кавычками", en: "name=\"value\" attributes: group 1 is the name, group 2 the quoted value" },
    limits: { ru: "Атрибуты без значения (disabled) не находятся.", en: "Value-less attributes (disabled) aren't found." },
    match: ['href="x"', "class='a b'", "width=100", 'data-id = "5"'],
    noMatch: ["href", "= value", "plain"],
  },
  {
    slug: "html-comment",
    name: { ru: "HTML-комментарий", en: "HTML comment" },
    category: "code",
    pattern: "<!--[\\s\\S]*?-->",
    flags: "g",
    mode: "find",
    what: { ru: "комментарии <!-- … -->, в том числе многострочные", en: "<!-- … --> comments, including multi-line ones" },
    limits: { ru: "Внутри <script> и строк JavaScript такие последовательности тоже будут найдены.", en: "Such sequences inside <script> or JavaScript strings are found too." },
    match: ["<!-- note -->", "a<!---->b", "<!--\nmulti\n-->"],
    noMatch: ["<!- x ->", "<!-- open", "text"],
  },
  {
    slug: "markdown-link",
    name: { ru: "Ссылка Markdown", en: "Markdown link" },
    category: "code",
    pattern: '(?<!!)\\[([^\\]]+)\\]\\(([^\\s)]+)(?:\\s+"([^"]*)")?\\)',
    flags: "g",
    mode: "find",
    what: { ru: "ссылки [текст](адрес \"заголовок\"): группа 1 — текст, 2 — адрес, 3 — заголовок; картинки ![]() пропускаются", en: "[text](url \"title\") links: group 1 text, 2 URL, 3 title; ![]() images are skipped" },
    limits: { ru: "Ссылки-сноски [текст][1] и адреса с пробелами в <…> не распознаются.", en: "Reference links [text][1] and <…>-wrapped URLs with spaces aren't recognized." },
    match: ["[site](https://example.com)", 'see [docs](/docs "Docs")', "[a](b)"],
    noMatch: ["[text]", "(https://x)", "[text] (url)", "![alt](img.png)"],
  },
  {
    slug: "emoji",
    name: { ru: "Эмодзи", en: "Emoji" },
    category: "text",
    pattern: "(?:\\p{Extended_Pictographic}|\\p{Regional_Indicator}{2})(?:\\uFE0F|\\p{Emoji_Modifier})*(?:\\u200D\\p{Extended_Pictographic}(?:\\uFE0F|\\p{Emoji_Modifier})*)*",
    flags: "gu",
    mode: "find",
    what: { ru: "эмодзи целиком — с оттенком кожи, флаги 🇰🇿 и составные вроде 👨‍👩‍👧", en: "whole emoji — skin tones, flags like 🇰🇿 and ZWJ sequences like 👨‍👩‍👧" },
    limits: { ru: "Символы © и ® Unicode тоже относит к пиктограммам. Нужен флаг u (или v).", en: "Unicode also counts © and ® as pictographic. Requires the u (or v) flag." },
    match: ["hi 😀", "flag 🇰🇿", "👍🏽 ok", "👨‍👩‍👧 family", "❤️"],
    noMatch: ["plain text", ":)", "123 # *"],
  },
  /* ───────────── text ───────────── */
  {
    slug: "cyrillic-only",
    name: { ru: "Только кириллица", en: "Cyrillic only" },
    category: "text",
    pattern: "^[А-ЯЁа-яё]+(?:[ -][А-ЯЁа-яё]+)*$",
    flags: "",
    mode: "full",
    what: { ru: "русские буквы (включая Ё), слова через пробел или дефис", en: "Russian letters (Ё included), words separated by a space or hyphen" },
    limits: { ru: "Казахские буквы (Ә, Қ, Ң…) сюда не входят — для них есть отдельный шаблон.", en: "Kazakh letters (Ә, Қ, Ң…) aren't included — there's a separate pattern for them." },
    match: ["Привет", "Ёлка", "Санкт-Петербург", "Иван Петров"],
    noMatch: ["Hello", "Привет!", "Привет1", "Алматы Almaty"],
  },
  {
    slug: "kazakh-cyrillic",
    name: { ru: "Казахская кириллица", en: "Kazakh Cyrillic" },
    category: "ru-kz",
    pattern: `^[${KZ_LETTERS}]+(?:[ -][${KZ_LETTERS}]+)*$`,
    flags: "",
    mode: "full",
    what: { ru: "все 42 буквы казахского кириллического алфавита, включая Ә Ғ Қ Ң Ө Ұ Ү Һ І", en: "all 42 letters of the Kazakh Cyrillic alphabet, including Ә Ғ Қ Ң Ө Ұ Ү Һ І" },
    limits: { ru: "Казахская латиница (Qazaqstan) сюда не проходит.", en: "Kazakh Latin script (Qazaqstan) doesn't match." },
    match: ["Қазақстан", "Өскемен", "Әлем", "Алматы"],
    noMatch: ["Qazaqstan", "Қазақ1", "Hello"],
  },
  {
    slug: "latin-only",
    name: { ru: "Только латиница", en: "Latin letters only" },
    category: "text",
    pattern: "^[A-Za-z]+(?:[ '-][A-Za-z]+)*$",
    flags: "",
    mode: "full",
    what: { ru: "английские буквы, слова через пробел, дефис или апостроф (O'Brien)", en: "English letters, words joined by a space, hyphen or apostrophe (O'Brien)" },
    limits: { ru: "Буквы с диакритикой (é, ü) не входят.", en: "Accented letters (é, ü) aren't included." },
    match: ["Hello", "John Smith", "O'Brien", "Jean-Luc"],
    noMatch: ["Привет", "Hello1", "Hello!", "Café"],
  },
  {
    slug: "digits-only",
    name: { ru: "Только цифры", en: "Digits only" },
    category: "numbers",
    pattern: "^\\d+$",
    flags: "",
    mode: "full",
    what: { ru: "одна или больше цифр 0–9, ведущие нули разрешены", en: "one or more digits 0–9, leading zeros allowed" },
    limits: { ru: "В JavaScript \\d — только ASCII-цифры: арабские и другие цифры не проходят.", en: "In JavaScript \\d is ASCII only: Arabic-Indic and other digits don't match." },
    match: ["0", "123", "0042"],
    noMatch: ["12a", "1 2", "-1", "١٢٣"],
  },
  {
    slug: "integer",
    name: { ru: "Целое число", en: "Integer" },
    category: "numbers",
    pattern: "^[+-]?(?:0|[1-9]\\d*)$",
    flags: "",
    mode: "full",
    what: { ru: "целое число со знаком или без, без ведущих нулей", en: "a signed or unsigned integer without leading zeros" },
    limits: { ru: "Диапазон (например, не больше 2³¹) регулярным выражением проверять неудобно — сравните число в коде.", en: "Ranges (e.g. up to 2³¹) are awkward in regex — compare the number in code." },
    match: ["0", "-42", "+7", "1000"],
    noMatch: ["01", "1.5", "--1", "1e3"],
  },
  {
    slug: "decimal-number",
    name: { ru: "Десятичное число (точка или запятая)", en: "Decimal number" },
    category: "numbers",
    pattern: "^[+-]?(?:\\d+(?:[.,]\\d+)?|[.,]\\d+)$",
    flags: "",
    mode: "full",
    what: { ru: "число с дробной частью через точку или запятую — как пишут в России и Казахстане", en: "a number with a fractional part after a dot or a comma" },
    limits: { ru: "Разделители разрядов (1 000,5) и экспонента (1e5) не поддерживаются.", en: "Thousands separators (1,000.5) and exponents (1e5) aren't supported." },
    match: ["3.14", "-0,5", ".5", "42"],
    noMatch: ["1.", "1,000.5", "1.2.3", "abc", "1e5"],
  },
  {
    slug: "whitespace-trim",
    name: { ru: "Пробелы в начале и конце", en: "Leading and trailing whitespace" },
    category: "text",
    pattern: "^\\s+|\\s+$",
    flags: "g",
    mode: "find",
    what: { ru: "пробелы, табуляции и переводы строк в начале и в конце — замените на пустую строку, чтобы обрезать", en: "spaces, tabs and newlines at the start and end — replace with an empty string to trim" },
    limits: { ru: "С флагом m выражение обрезает каждую строку отдельно. В коде проще вызвать trim().", en: "With the m flag it trims every line. In code, trim() is simpler." },
    match: ["  hi", "hi  ", "\thi"],
    noMatch: ["hi", "a b", "trimmed text"],
  },
  {
    slug: "multiple-spaces",
    name: { ru: "Двойные пробелы", en: "Multiple spaces" },
    category: "text",
    pattern: " {2,}",
    flags: "g",
    mode: "find",
    what: { ru: "два и более пробела подряд — замените на один пробел", en: "two or more spaces in a row — replace them with a single space" },
    limits: { ru: "Табуляции и неразрывные пробелы не учитываются; для них используйте [ \\t\\u00A0]{2,}.", en: "Tabs and non-breaking spaces aren't included; use [ \\t\\u00A0]{2,} for them." },
    match: ["a  b", "   ", "x   y"],
    noMatch: ["a b", "ab", "a\tb"],
  },
  {
    slug: "empty-lines",
    name: { ru: "Пустые строки", en: "Empty lines" },
    category: "text",
    pattern: "^[ \\t]*$",
    flags: "gm",
    mode: "find",
    what: { ru: "пустые строки и строки из одних пробелов (с флагом m)", en: "empty and whitespace-only lines (with the m flag)" },
    limits: { ru: "Чтобы удалить их вместе с переводами строк, ищите ^[ \\t]*\\r?\\n.", en: "To delete them with their line breaks, search for ^[ \\t]*\\r?\\n." },
    match: ["a\n\nb", "x\n  \ny", "\n"],
    noMatch: ["a\nb", "text", "a\n b"],
  },
  {
    slug: "duplicate-words",
    name: { ru: "Повторяющиеся слова", en: "Duplicate words" },
    category: "text",
    pattern: "(?<![\\p{L}\\p{N}_])([\\p{L}\\p{N}_]+)\\s+\\1(?![\\p{L}\\p{N}_])",
    flags: "giu",
    mode: "find",
    what: { ru: "одно и то же слово два раза подряд («это это»), без учёта регистра и на любом языке", en: "the same word twice in a row (“the the”), case-insensitive and in any language" },
    limits: { ru: "Повторы через знак препинания («да, да») не ищутся — это часто норма.", en: "Repeats separated by punctuation (“yes, yes”) aren't matched — they're often intended." },
    match: ["the the", "Это это", "go go go", "в в"],
    noMatch: ["the then", "это эта", "one two"],
  },
  {
    slug: "file-extension",
    name: { ru: "Имя файла с расширением", en: "File name with extension" },
    category: "code",
    pattern: "^[^\\\\/:*?\"<>|\\r\\n]+\\.([A-Za-z0-9]{1,10})$",
    flags: "",
    mode: "full",
    what: { ru: "имя файла без запрещённых в Windows символов и расширение до 10 символов (группа 1)", en: "a file name without Windows-forbidden characters and an extension of up to 10 characters (group 1)" },
    limits: { ru: "Для составных расширений (.tar.gz) группа вернёт только последнее — gz.", en: "For double extensions (.tar.gz) the group returns only the last one — gz." },
    match: ["report.pdf", "archive.tar.gz", "photo.JPEG", "my file.docx"],
    noMatch: ["noextension", ".bashrc", "file.", "dir/file.txt", "file.toolongextension"],
  },
  {
    slug: "windows-path",
    name: { ru: "Путь Windows", en: "Windows path" },
    category: "code",
    pattern: "^(?:[A-Za-z]:\\\\|\\\\\\\\[^\\\\/:*?\"<>|\\r\\n]+\\\\[^\\\\/:*?\"<>|\\r\\n]+\\\\?)(?:[^\\\\/:*?\"<>|\\r\\n]+\\\\?)*$",
    flags: "",
    mode: "full",
    what: { ru: "абсолютный путь с буквой диска (C:\\…) или сетевой UNC-путь (\\\\сервер\\папка)", en: "an absolute path with a drive letter (C:\\…) or a UNC network path (\\\\server\\share)" },
    limits: { ru: "Не проверяет зарезервированные имена (CON, NUL) и ограничение длины 260 символов.", en: "It doesn't check reserved names (CON, NUL) or the 260-character limit." },
    match: ["C:\\Windows\\System32", "D:\\", "\\\\server\\share\\file.txt", "C:\\Program Files\\App\\app.exe"],
    noMatch: ["C:/Windows", "/usr/bin", "C:\\bad|name", "Windows\\System32"],
  },
  {
    slug: "unix-path",
    name: { ru: "Путь Unix / Linux", en: "Unix path" },
    category: "code",
    pattern: "^\\/(?:[^\\/\\0\\r\\n]+\\/?)*$",
    flags: "",
    mode: "full",
    what: { ru: "абсолютный путь от корня /, без двойных косых черт", en: "an absolute path from the root /, without double slashes" },
    limits: { ru: "Относительные пути (./, ../, ~) не принимаются.", en: "Relative paths (./, ../, ~) aren't accepted." },
    match: ["/", "/usr/local/bin", "/home/user/file.txt", "/var/log/"],
    noMatch: ["usr/bin", "C:\\Windows", "//double"],
  },
  /* ───────────── dates ───────────── */
  {
    slug: "date-yyyy-mm-dd",
    name: { ru: "Дата ГГГГ-ММ-ДД", en: "Date YYYY-MM-DD" },
    category: "datetime",
    pattern: "^\\d{4}-(?:0[1-9]|1[0-2])-(?:0[1-9]|[12]\\d|3[01])$",
    flags: "",
    mode: "full",
    what: { ru: "дата ISO 8601: год, месяц 01–12 и день 01–31 через дефис", en: "an ISO 8601 date: year, month 01–12 and day 01–31 separated by hyphens" },
    limits: { ru: "Проверяется формат, а не календарь: 2025-02-30 тоже подойдёт. Существование даты проверяйте в коде.", en: "It checks the format, not the calendar: 2025-02-30 matches too. Validate the date in code." },
    match: ["2025-01-31", "1999-12-01", "2024-02-29", "2000-10-10"],
    noMatch: ["2025-13-01", "2025-1-1", "25-01-01", "2025/01/31", "2025-00-10"],
  },
  {
    slug: "date-dd-mm-yyyy",
    name: { ru: "Дата ДД.ММ.ГГГГ", en: "Date DD.MM.YYYY" },
    category: "datetime",
    pattern: "^(?:0[1-9]|[12]\\d|3[01])([./-])(?:0[1-9]|1[0-2])\\1\\d{4}$",
    flags: "",
    mode: "full",
    what: { ru: "дата в привычном формате: день, месяц и год через точку, косую черту или дефис (один и тот же)", en: "a day-first date: day, month and year separated by the same dot, slash or hyphen" },
    limits: { ru: "31.02.2025 проходит: проверяется только формат.", en: "31.02.2025 matches: only the format is checked." },
    match: ["31.12.2025", "01/01/2000", "15-06-1990", "29.02.2024"],
    noMatch: ["32.01.2025", "1.1.2025", "31.12-2025", "2025.12.31"],
  },
  {
    slug: "time-24h",
    name: { ru: "Время 24 часа (ЧЧ:ММ)", en: "Time 24-hour" },
    category: "datetime",
    pattern: "^(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d)?$",
    flags: "",
    mode: "full",
    what: { ru: "время 00:00–23:59, секунды по желанию", en: "time 00:00–23:59, seconds optional" },
    limits: { ru: "Часы без ведущего нуля (9:30) не принимаются.", en: "Hours without a leading zero (9:30) aren't accepted." },
    match: ["00:00", "23:59", "09:30:15", "12:00"],
    noMatch: ["24:00", "9:30", "12:60", "12:30:60"],
  },
  {
    slug: "time-12h",
    name: { ru: "Время 12 часов (AM/PM)", en: "Time 12-hour (AM/PM)" },
    category: "datetime",
    pattern: "^(?:0?[1-9]|1[0-2]):[0-5]\\d\\s?[AaPp][Mm]$",
    flags: "",
    mode: "full",
    what: { ru: "американский формат времени: 1–12 часов и AM или PM", en: "US-style time: hours 1–12 and AM or PM" },
    limits: { ru: "Точки в a.m./p.m. не поддерживаются.", en: "Dotted a.m./p.m. isn't supported." },
    match: ["9:30 AM", "12:00pm", "01:15 PM", "11:59 am"],
    noMatch: ["13:00 PM", "0:30 AM", "9:30", "9:60 AM"],
  },
  {
    slug: "iso-8601",
    name: { ru: "Дата и время ISO 8601", en: "ISO 8601 date-time" },
    category: "datetime",
    pattern: "^\\d{4}-(?:0[1-9]|1[0-2])-(?:0[1-9]|[12]\\d|3[01])T(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d{1,9})?)?(?:Z|[+-](?:[01]\\d|2[0-3]):?[0-5]\\d)?$",
    flags: "",
    mode: "full",
    what: { ru: "дата и время через T, с долями секунды и часовым поясом (Z или ±чч:мм)", en: "date and time joined by T, with fractional seconds and a zone (Z or ±hh:mm)" },
    limits: { ru: "Недели (2025-W01) и порядковые дни (2025-032) не поддерживаются.", en: "Week dates (2025-W01) and ordinal dates (2025-032) aren't supported." },
    match: ["2025-06-01T12:30:00Z", "2025-06-01T12:30:00.123+05:00", "2025-06-01T12:30", "2025-06-01T23:59:59-0300"],
    noMatch: ["2025-06-01 12:30:00", "2025-06-01T24:00:00Z", "2025-06-01T12:30:00+5", "2025-6-1T12:30Z"],
  },
  /* ───────────── phones and codes ───────────── */
  {
    slug: "phone-ru",
    name: { ru: "Телефон России", en: "Russian phone number" },
    category: "ru-kz",
    pattern: "^(?:\\+7|8)[\\s-]?\\(?[3489]\\d{2}\\)?[\\s-]?\\d{3}[\\s-]?\\d{2}[\\s-]?\\d{2}$",
    flags: "",
    mode: "full",
    what: { ru: "номер +7 или 8 с кодом 3xx, 4xx, 8xx или 9xx в популярных записях со скобками, пробелами и дефисами", en: "a +7 or 8 number with a 3xx, 4xx, 8xx or 9xx code in common formats" },
    limits: { ru: "Коды 7xx принадлежат Казахстану, поэтому не проходят. Для строгой проверки используйте libphonenumber.", en: "7xx codes belong to Kazakhstan, so they don't match. Use libphonenumber for strict checks." },
    match: ["+7 (999) 123-45-67", "89991234567", "+7 495 123 45 67", "8-800-555-35-35"],
    noMatch: ["+7 (777) 123-45-67", "+8 999 123 45 67", "999 123 45 67", "+7 (999) 123-45-6"],
  },
  {
    slug: "phone-kz",
    name: { ru: "Телефон Казахстана", en: "Kazakhstan phone number" },
    category: "ru-kz",
    pattern: "^(?:\\+7|8)[\\s-]?\\(?7\\d{2}\\)?[\\s-]?\\d{3}[\\s-]?\\d{2}[\\s-]?\\d{2}$",
    flags: "",
    mode: "full",
    what: { ru: "казахстанский номер +7 или 8 с кодом 7xx: мобильные (700–778) и городские (727 — Алматы, 717 — Астана)", en: "a Kazakh +7 or 8 number with a 7xx code: mobile (700–778) and landline (727 Almaty, 717 Astana)" },
    limits: { ru: "Не проверяет, выделен ли код оператору; для этого нужна база номеров.", en: "It doesn't check whether the code is assigned to an operator — that needs a numbering database." },
    match: ["+7 (701) 123-45-67", "87771234567", "+7 727 250 00 00", "8 (747) 123 45 67"],
    noMatch: ["+7 (999) 123-45-67", "+7 701 123 45", "701 123 45 67", "+77 701 1234567"],
  },
  {
    slug: "phone-us",
    name: { ru: "Телефон США (NANP)", en: "US phone number" },
    category: "numbers",
    pattern: "^(?:\\+?1[\\s.-]?)?\\(?([2-9]\\d{2})\\)?[\\s.-]?([2-9]\\d{2})[\\s.-]?(\\d{4})$",
    flags: "",
    mode: "full",
    what: { ru: "номер Северной Америки: код региона и станции начинаются с 2–9, код страны +1 необязателен", en: "a North American number: area and exchange codes start with 2–9; +1 is optional" },
    limits: { ru: "Не проверяет специальные номера вроде 555-01XX.", en: "Special ranges such as 555-01XX aren't checked." },
    match: ["(415) 555-2671", "415-555-2671", "+1 415 555 2671", "4155552671"],
    noMatch: ["(115) 555-2671", "415-155-2671", "555-2671", "+44 20 7946 0958"],
  },
  {
    slug: "e164",
    name: { ru: "Номер в формате E.164", en: "E.164 phone number" },
    category: "numbers",
    pattern: "^\\+[1-9]\\d{1,14}$",
    flags: "",
    mode: "full",
    what: { ru: "международный номер: + и до 15 цифр без пробелов (+77011234567)", en: "an international number: + and up to 15 digits without spaces (+14155552671)" },
    limits: { ru: "Длину и код конкретной страны не проверяет.", en: "It doesn't check the length or code of a particular country." },
    match: ["+77011234567", "+14155552671", "+442071838750", "+12"],
    noMatch: ["77011234567", "+0123", "+1234567890123456", "+7 701 123 45 67"],
  },
  {
    slug: "postal-code-ru",
    name: { ru: "Почтовый индекс России", en: "Russian postal code" },
    category: "ru-kz",
    pattern: "^[1-6]\\d{5}$",
    flags: "",
    mode: "full",
    what: { ru: "шесть цифр, первая от 1 до 6 — так устроены индексы Почты России", en: "six digits with the first one 1–6, as Russian Post codes are" },
    limits: { ru: "Существует ли индекс, проверит только справочник Почты России.", en: "Only the Russian Post directory can confirm a code exists." },
    match: ["101000", "630099", "190000", "690091"],
    noMatch: ["012345", "12345", "1234567", "700000"],
  },
  {
    slug: "postal-code-kz",
    name: { ru: "Почтовый индекс Казахстана", en: "Kazakhstan postal code" },
    category: "ru-kz",
    pattern: "^(?:0[1-9]|1[0-6])\\d{4}$",
    flags: "",
    mode: "full",
    what: { ru: "классический шестизначный индекс Казпочты: первые две цифры 01–16 — область (05 — Алматы, 01 — Астана)", en: "the classic six-digit Kazpost code: the first two digits 01–16 are the region (05 Almaty, 01 Astana)" },
    limits: { ru: "Новые буквенно-цифровые индексы Казпочты этим шаблоном не проверяются.", en: "Kazpost's newer alphanumeric codes aren't covered by this pattern." },
    match: ["050000", "010000", "160000", "100008"],
    noMatch: ["000000", "170000", "50000", "0500001"],
  },
  {
    slug: "postal-code-us",
    name: { ru: "Индекс США (ZIP)", en: "US ZIP code" },
    category: "numbers",
    pattern: "^\\d{5}(?:-\\d{4})?$",
    flags: "",
    mode: "full",
    what: { ru: "ZIP из 5 цифр или ZIP+4 (12345-6789)", en: "a 5-digit ZIP or ZIP+4 (12345-6789)" },
    limits: { ru: "Не проверяет, выдан ли индекс.", en: "It doesn't check whether the ZIP exists." },
    match: ["90210", "10001-1234", "00501", "12345"],
    noMatch: ["1234", "123456", "12345-123", "ABCDE"],
  },
  {
    slug: "credit-card",
    name: { ru: "Номер банковской карты", en: "Credit card number" },
    category: "numbers",
    pattern: "^(?:4\\d{12}(?:\\d{3}){0,2}|5[1-5]\\d{14}|2(?:2[2-9][1-9]|2[3-9]\\d|[3-6]\\d{2}|7[01]\\d|720)\\d{12}|220[0-4]\\d{12}|3[47]\\d{13}|6(?:011|5\\d{2})\\d{12})$",
    flags: "",
    mode: "full",
    what: { ru: "номера Visa, Mastercard (51–55 и 2221–2720), МИР (2200–2204), American Express и Discover без пробелов", en: "Visa, Mastercard (51–55 and 2221–2720), Mir (2200–2204), American Express and Discover numbers without spaces" },
    limits: { ru: "Проверяет только префикс и длину. Контрольную сумму Луна регулярное выражение проверить не может — пробелы уберите заранее.", en: "It checks only the prefix and length. A regex can't verify the Luhn checksum — strip spaces first." },
    match: ["4111111111111111", "5500005555555559", "378282246310005", "2200000000000004", "6011111111111117"],
    noMatch: ["1234567890123456", "411111111111", "4111 1111 1111 1111", "37828224631000"],
  },
  {
    slug: "iban",
    name: { ru: "IBAN", en: "IBAN" },
    category: "numbers",
    pattern: "^[A-Z]{2}\\d{2}[A-Z0-9]{11,30}$",
    flags: "",
    mode: "full",
    what: { ru: "международный номер счёта: код страны, две контрольные цифры и 11–30 символов (казахстанский IBAN — 20 символов)", en: "an international account number: country code, two check digits and 11–30 characters (a Kazakh IBAN has 20)" },
    limits: { ru: "Контрольную сумму mod 97 и длину для каждой страны регулярное выражение не проверяет. Пробелы уберите заранее.", en: "The mod-97 checksum and per-country lengths aren't checked. Remove spaces first." },
    match: ["KZ86125KZT5004100100", "DE89370400440532013000", "GB82WEST12345698765432", "FR1420041010050500013M02606"],
    noMatch: ["KZ86 125K ZT50 0410 0100", "kz86125KZT5004100100", "DE8937040044", "1234567890123456"],
  },
  {
    slug: "inn-ru",
    name: { ru: "ИНН (Россия)", en: "Russian INN" },
    category: "ru-kz",
    pattern: "^(?:\\d{10}|\\d{12})$",
    flags: "",
    mode: "full",
    what: { ru: "ИНН организации (10 цифр) или физического лица (12 цифр)", en: "a company INN (10 digits) or an individual's INN (12 digits)" },
    limits: { ru: "Контрольные цифры ИНН регулярным выражением не проверить — нужен расчёт в коде.", en: "INN check digits can't be verified with a regex — compute them in code." },
    match: ["7707083893", "500100732259", "1234567890", "123456789012"],
    noMatch: ["770708389", "12345678901", "1234567890123", "abcdefghij"],
  },
  {
    slug: "snils",
    name: { ru: "СНИЛС", en: "Russian SNILS" },
    category: "ru-kz",
    pattern: "^\\d{3}-?\\d{3}-?\\d{3}[ -]?\\d{2}$",
    flags: "",
    mode: "full",
    what: { ru: "СНИЛС в виде XXX-XXX-XXX YY или 11 цифр подряд", en: "a SNILS as XXX-XXX-XXX YY or 11 digits in a row" },
    limits: { ru: "Контрольное число (последние две цифры) проверяется только расчётом в коде.", en: "The check number (last two digits) can only be verified in code." },
    match: ["112-233-445 95", "11223344595", "123-456-789 01", "123-456-789-01"],
    noMatch: ["112-233-44595x", "11-223-344 595", "112 233 445 95", "1122334459"],
  },
  {
    slug: "iin-kz",
    name: { ru: "ИИН (Казахстан)", en: "Kazakhstan IIN" },
    category: "ru-kz",
    pattern: "^\\d{2}(?:0[1-9]|1[0-2])(?:0[1-9]|[12]\\d|3[01])[0-6]\\d{5}$",
    flags: "",
    mode: "full",
    what: { ru: "12 цифр ИИН: дата рождения ГГММДД, цифра века и пола (0–6) и порядковый номер", en: "the 12-digit IIN: birth date YYMMDD, a century/sex digit (0–6) and a serial number" },
    limits: { ru: "Контрольный разряд (12-я цифра) и реальность даты регулярное выражение не проверяет.", en: "The check digit (12th) and whether the date exists aren't checked." },
    match: ["850315400056", "010203500987", "990101300001", "750630100200"],
    noMatch: ["851315400056", "850332400056", "85031540005", "850315700056"],
  },
  {
    slug: "passport-ru",
    name: { ru: "Паспорт РФ (серия и номер)", en: "Russian passport number" },
    category: "ru-kz",
    pattern: "^\\d{2}\\s?\\d{2}\\s?\\d{6}$",
    flags: "",
    mode: "full",
    what: { ru: "серия из 4 цифр (можно с пробелом посередине) и номер из 6 цифр", en: "a 4-digit series (optionally split by a space) and a 6-digit number" },
    limits: { ru: "Действительность паспорта проверяют только по базе МВД.", en: "Validity can only be checked against the official database." },
    match: ["4509 123456", "4509123456", "45 09 123456"],
    noMatch: ["4509 12345", "450912345", "4509-123456"],
  },
  {
    slug: "car-number-ru",
    name: { ru: "Госномер автомобиля РФ", en: "Russian car plate" },
    category: "ru-kz",
    pattern: `^[${PLATE}](?!000)\\d{3}[${PLATE}]{2}\\d{2,3}$`,
    flags: "i",
    mode: "full",
    what: { ru: "номер вида А123ВС77: только 12 кириллических букв, похожих на латинские, код региона из 2–3 цифр", en: "a plate like А123ВС77: only the 12 Cyrillic letters that look Latin, a 2–3 digit region code" },
    limits: { ru: "Латинские буквы-двойники (A, B, C) не принимаются — это частая ошибка ввода.", en: "Latin look-alike letters (A, B, C) aren't accepted — a common input mistake." },
    match: ["А123ВС77", "Е001КХ199", "М777ММ750", "Т456РУ02"],
    noMatch: ["Б123ВС77", "А000ВС77", "А123ВС7", "A123BC77"],
  },
  {
    slug: "strong-password",
    name: { ru: "Сложный пароль", en: "Strong password" },
    category: "text",
    pattern: "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[^A-Za-z\\d\\s]).{8,}$",
    flags: "",
    mode: "full",
    what: { ru: "не короче 8 символов, есть строчная и заглавная латинская буква, цифра и спецсимвол", en: "at least 8 characters with a lowercase and an uppercase letter, a digit and a symbol" },
    limits: { ru: "Правила состава не гарантируют надёжность: «Password1!» подходит, но легко угадывается. Длина важнее — лучше проверяйте пароль по словарю.", en: "Composition rules don't guarantee strength: “Password1!” matches but is easy to guess. Length matters more — check against a dictionary." },
    match: ["Passw0rd!", "Str0ng#Pass", "aB3$efgh"],
    noMatch: ["password", "PASSWORD1!", "Pass1!", "Password1", "password!1"],
  },
  {
    slug: "latitude-longitude",
    name: { ru: "Координаты (широта, долгота)", en: "Latitude and longitude" },
    category: "numbers",
    pattern: "^[-+]?(?:[1-8]?\\d(?:\\.\\d+)?|90(?:\\.0+)?),\\s*[-+]?(?:180(?:\\.0+)?|(?:1[0-7]\\d|[1-9]?\\d)(?:\\.\\d+)?)$",
    flags: "",
    mode: "full",
    what: { ru: "пара «широта, долгота» в десятичных градусах: −90…90 и −180…180 (43.238949, 76.889709 — Алматы)", en: "a “latitude, longitude” pair in decimal degrees: −90…90 and −180…180" },
    limits: { ru: "Градусы-минуты-секунды (43°14′20″) не поддерживаются.", en: "Degrees-minutes-seconds (43°14′20″) aren't supported." },
    match: ["43.238949, 76.889709", "51.1605,71.4704", "-33.8688, 151.2093", "90, 180"],
    noMatch: ["91, 0", "0, 181", "43.2 76.8", "abc, def"],
  },
  {
    slug: "isbn",
    name: { ru: "ISBN", en: "ISBN" },
    category: "numbers",
    pattern: "^(?:ISBN(?:-1[03])?:?\\s*)?(?:(?:\\d[- ]?){9}[\\dX]|97[89][- ]?(?:\\d[- ]?){9}\\d)$",
    flags: "",
    mode: "full",
    what: { ru: "ISBN-10 (10 знаков, последний может быть X) или ISBN-13 (978/979 и ещё 10 цифр) с дефисами или пробелами", en: "an ISBN-10 (10 characters, the last may be X) or an ISBN-13 (978/979 plus 10 digits), hyphens or spaces allowed" },
    limits: { ru: "Контрольную цифру и правильность деления на группы регулярное выражение не проверяет.", en: "The check digit and the grouping of hyphens aren't verified." },
    match: ["978-3-16-148410-0", "0-306-40615-2", "9783161484100", "ISBN 978-0-596-52068-7"],
    noMatch: ["978-3-16", "ISBN", "123456789", "978_3_16_148410_0"],
  },
];

export const CATEGORY_NAME: Record<Category, L> = {
  web: { ru: "Интернет и сеть", en: "Web and network" },
  id: { ru: "Идентификаторы", en: "Identifiers" },
  code: { ru: "Код и файлы", en: "Code and files" },
  text: { ru: "Текст", en: "Text" },
  numbers: { ru: "Числа и номера", en: "Numbers" },
  datetime: { ru: "Даты и время", en: "Dates and times" },
  "ru-kz": { ru: "Россия и Казахстан", en: "Russia and Kazakhstan" },
};

/** Flags to preload into the tester: full patterns are tested line by line. */
export function testerFlags(p: LibPattern): string {
  const base = new Set(p.flags.split(""));
  base.add("g");
  if (p.mode === "full") base.add("m");
  return ["d", "g", "i", "m", "s", "u", "v", "y"].filter((f) => base.has(f)).join("");
}

export function testerText(p: LibPattern): string {
  return [...p.match, ...p.noMatch].filter((x) => !x.includes("\n")).join("\n");
}
