import type { ComponentMap } from "../types";

export const components: ComponentMap = {
  "image/compress": () => import("./tools/Compress"),
  "image/resize": () => import("./tools/Resize"),
  "image/convert": () => import("./tools/Convert"),
  "image/crop": () => import("./tools/Crop"),
  "image/orient": () => import("./tools/Orient"),
  "image/filters": () => import("./tools/Filters"),
  "image/censor": () => import("./tools/Censor"),
  "image/watermark": () => import("./tools/Watermark"),
  "image/add-text": () => import("./tools/AddText"),
  "image/collage": () => import("./tools/Collage"),
  "image/split": () => import("./tools/Split"),
  "image/decorate": () => import("./tools/Decorate"),
  "image/exif": () => import("./tools/Exif"),
  "image/dpi": () => import("./tools/Dpi"),
  "image/to-base64": () => import("./tools/ToBase64"),
  "image/base64-to-image": () => import("./tools/Base64ToImage"),
  "image/favicon": () => import("./tools/Favicon"),
  "image/colors": () => import("./tools/Colors"),
  "image/gif-maker": () => import("./tools/GifMaker"),
  "image/gif-frames": () => import("./tools/GifFrames"),
  "image/svg": () => import("./tools/Svg"),
  "image/pixel-art": () => import("./tools/PixelArt"),
  "image/compare": () => import("./tools/Compare"),
  "image/passport": () => import("./tools/PassportPhoto"),
  "image/id-copy": () => import("./tools/IdCopy"),
};
