'use client';

/**
 * Phosphor icon mapping for tool.icon and group.icon string literals.
 *
 * Source data uses Material-style names (e.g. "PictureAsPdf"). This module maps
 * those legacy strings to Phosphor components. To add a new icon, only add a
 * map entry — no need to touch the data files.
 *
 * Use weight="duotone" for category-level emphasis, "regular" for inline UI.
 */
import {
  Alarm,
  AppWindow,
  ArrowClockwise,
  ArrowLeft,
  ArrowRight,
  ArrowsClockwise,
  ArrowsDownUp,
  ArrowsInLineHorizontal,
  ArrowsLeftRight,
  ArrowsOutSimple,
  Article,
  Atom,
  Baby,
  Bank,
  Barbell,
  BatteryHigh,
  Bed,
  BookOpen,
  BracketsCurly,
  Brain,
  Broom,
  Browser,
  Buildings,
  Cake,
  Calculator,
  Calendar,
  CalendarBlank,
  CalendarDots,
  CalendarPlus,
  Camera,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretUp,
  ChartBar,
  ChartLine,
  ChartLineUp,
  ChatCircle,
  ChatsCircle,
  ChatTeardropText,
  Check,
  CheckCircle,
  CheckSquare,
  CircleHalf,
  ClipboardText,
  Clock,
  ClockCounterClockwise,
  Cloud,
  CloudArrowDown,
  CloudArrowUp,
  Code,
  Coin,
  Compass,
  Copy,
  CreditCard,
  Crop,
  CurrencyDollarSimple,
  Database,
  DeviceMobile,
  DeviceMobileCamera,
  DotsThree,
  DotsThreeVertical,
  DownloadSimple,
  Drop,
  EnvelopeSimple,
  Eye,
  EyeSlash,
  File,
  FileCss,
  FileHtml,
  FileJs,
  FilePdf,
  FileText,
  Fingerprint,
  FlipHorizontal,
  ForkKnife,
  FrameCorners,
  Function,
  Funnel,
  GameController,
  GasPump,
  Gauge,
  Gear,
  GitDiff,
  Globe,
  GlobeHemisphereWest,
  GridFour,
  HardDrives,
  Hash,
  Heart,
  HeartStraight,
  Hourglass,
  House,
  IdentificationBadge,
  IdentificationCard,
  Image,
  Images,
  Info,
  Key,
  Leaf,
  Lightbulb,
  Lightning,
  Link,
  List,
  ListBullets,
  ListNumbers,
  Lock,
  LockOpen,
  MagicWand,
  MagnifyingGlass,
  MagnifyingGlassMinus,
  MagnifyingGlassPlus,
  MapPin,
  MapTrifold,
  Minus,
  MinusCircle,
  Money,
  Moon,
  MusicNote,
  Network,
  NewspaperClipping,
  Note,
  NotePencil,
  NumberCircleZero,
  Package,
  PaintBrush,
  PaintBrushHousehold,
  PaintBucket,
  Palette,
  PawPrint,
  PencilLine,
  PencilSimple,
  Percent,
  PersonSimple,
  PersonSimpleRun,
  Phone,
  PiggyBank,
  Plug,
  Plus,
  PresentationChart,
  PushPin,
  QrCode,
  Question,
  Quotes,
  Receipt,
  Resize,
  Robot,
  Rows,
  RssSimple,
  Ruler,
  Scales,
  ShieldCheck,
  ShoppingCart,
  SlidersHorizontal,
  Smiley,
  SmileyWink,
  SortAscending,
  Sparkle,
  SpeakerHigh,
  Square,
  SquaresFour,
  Star,
  Sun,
  Table,
  Tag,
  TextAa,
  TextT,
  Thermometer,
  Timer,
  Toolbox,
  Translate,
  TrashSimple,
  TrendUp,
  Trophy,
  Truck,
  UploadSimple,
  User,
  UserCircle,
  UserList,
  Wallet,
  Warning,
  WarningCircle,
  WaveSawtooth,
  WaveSine,
  WifiHigh,
  Wrench,
  X,
  type Icon as IconType,
  type IconProps,
} from '@phosphor-icons/react';

// Keep the legacy mapping below readable while allowing Next.js to rewrite
// every named import to the package's per-icon entry point.
const Ph = {
  Alarm,
  AppWindow,
  ArrowClockwise,
  ArrowLeft,
  ArrowRight,
  ArrowsClockwise,
  ArrowsDownUp,
  ArrowsInLineHorizontal,
  ArrowsLeftRight,
  ArrowsOutSimple,
  Article,
  Atom,
  Baby,
  Bank,
  Barbell,
  BatteryHigh,
  Bed,
  BookOpen,
  BracketsCurly,
  Brain,
  Broom,
  Browser,
  Buildings,
  Cake,
  Calculator,
  Calendar,
  CalendarBlank,
  CalendarDots,
  CalendarPlus,
  Camera,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretUp,
  ChartBar,
  ChartLine,
  ChartLineUp,
  ChatCircle,
  ChatsCircle,
  ChatTeardropText,
  Check,
  CheckCircle,
  CheckSquare,
  CircleHalf,
  ClipboardText,
  Clock,
  ClockCounterClockwise,
  Cloud,
  CloudArrowDown,
  CloudArrowUp,
  Code,
  Coin,
  Compass,
  Copy,
  CreditCard,
  Crop,
  CurrencyDollarSimple,
  Database,
  DeviceMobile,
  DeviceMobileCamera,
  DotsThree,
  DotsThreeVertical,
  DownloadSimple,
  Drop,
  EnvelopeSimple,
  Eye,
  EyeSlash,
  File,
  FileCss,
  FileHtml,
  FileJs,
  FilePdf,
  FileText,
  Fingerprint,
  FlipHorizontal,
  ForkKnife,
  FrameCorners,
  Function,
  Funnel,
  GameController,
  GasPump,
  Gauge,
  Gear,
  GitDiff,
  Globe,
  GlobeHemisphereWest,
  GridFour,
  HardDrives,
  Hash,
  Heart,
  HeartStraight,
  Hourglass,
  House,
  IdentificationBadge,
  IdentificationCard,
  Image,
  Images,
  Info,
  Key,
  Leaf,
  Lightbulb,
  Lightning,
  Link,
  List,
  ListBullets,
  ListNumbers,
  Lock,
  LockOpen,
  MagicWand,
  MagnifyingGlass,
  MagnifyingGlassMinus,
  MagnifyingGlassPlus,
  MapPin,
  MapTrifold,
  Minus,
  MinusCircle,
  Money,
  Moon,
  MusicNote,
  Network,
  NewspaperClipping,
  Note,
  NotePencil,
  NumberCircleZero,
  Package,
  PaintBrush,
  PaintBrushHousehold,
  PaintBucket,
  Palette,
  PawPrint,
  PencilLine,
  PencilSimple,
  Percent,
  PersonSimple,
  PersonSimpleRun,
  Phone,
  PiggyBank,
  Plug,
  Plus,
  PresentationChart,
  PushPin,
  QrCode,
  Question,
  Quotes,
  Receipt,
  Resize,
  Robot,
  Rows,
  RssSimple,
  Ruler,
  Scales,
  ShieldCheck,
  ShoppingCart,
  SlidersHorizontal,
  Smiley,
  SmileyWink,
  SortAscending,
  Sparkle,
  SpeakerHigh,
  Square,
  SquaresFour,
  Star,
  Sun,
  Table,
  Tag,
  TextAa,
  TextT,
  Thermometer,
  Timer,
  Toolbox,
  Translate,
  TrashSimple,
  TrendUp,
  Trophy,
  Truck,
  UploadSimple,
  User,
  UserCircle,
  UserList,
  Wallet,
  Warning,
  WarningCircle,
  WaveSawtooth,
  WaveSine,
  WifiHigh,
  Wrench,
  X,
} as const;

const ICON_MAP: Record<string, IconType> = {
  // Categories
  PictureAsPdf: Ph.FilePdf,
  Image: Ph.Image,
  TextFields: Ph.TextT,
  Code: Ph.Code,
  TravelExplore: Ph.MagnifyingGlass,
  SwapHoriz: Ph.ArrowsLeftRight,
  Calculate: Ph.Calculator,
  Palette: Ph.Palette,
  AutoAwesome: Ph.Sparkle,
  Schedule: Ph.Clock,
  EmojiSymbols: Ph.SmileyWink,
  LockOpen: Ph.LockOpen,
  Security: Ph.ShieldCheck,
  Functions: Ph.Function,
  AccountBalance: Ph.Bank,
  FitnessCenter: Ph.Barbell,
  Casino: Ph.GameController,
  MusicNote: Ph.MusicNote,
  Lan: Ph.Network,
  QrCode2: Ph.QrCode,
  Straighten: Ph.Ruler,
  TaskAlt: Ph.CheckSquare,

  // Tools — common
  ColorLens: Ph.PaintBrushHousehold,
  Transform: Ph.ArrowsClockwise,
  Thermostat: Ph.Thermometer,
  LocalDrink: Ph.Drop,
  Speed: Ph.Gauge,
  SquareFoot: Ph.Square,
  ElectricBolt: Ph.Lightning,
  Compress: Ph.ArrowsInLineHorizontal,
  Storage: Ph.Database,
  Architecture: Ph.Compass,
  Power: Ph.Plug,
  LocalGasStation: Ph.GasPump,
  MyLocation: Ph.MapPin,
  Language: Ph.Globe,
  PublicOff: Ph.GlobeHemisphereWest,
  DateRange: Ph.CalendarBlank,
  Timer: Ph.Timer,
  Cake: Ph.Cake,
  AccessTime: Ph.Clock,
  CalendarMonth: Ph.Calendar,
  ViewWeek: Ph.GridFour,
  Percent: Ph.Percent,
  House: Ph.House,
  CreditCard: Ph.CreditCard,
  Receipt: Ph.Receipt,
  RestaurantMenu: Ph.ForkKnife,
  LocalOffer: Ph.Tag,
  TrendingUp: Ph.TrendUp,
  Payments: Ph.Money,
  PhotoSizeSelectLarge: Ph.ArrowsOutSimple,
  PhotoSizeSelectActual: Ph.Resize,
  Crop: Ph.Crop,
  RotateRight: Ph.ArrowClockwise,
  AutoFixHigh: Ph.MagicWand,
  Web: Ph.Browser,
  SentimentVerySatisfied: Ph.Smiley,
  DataObject: Ph.BracketsCurly,
  GridOn: Ph.GridFour,
  Draw: Ph.PencilLine,
  FormatListNumbered: Ph.ListNumbers,
  TextFormat: Ph.TextAa,
  Article: Ph.Article,
  Compare: Ph.GitDiff,
  FlipToFront: Ph.FlipHorizontal,
  PlaylistRemove: Ph.MinusCircle,
  SortByAlpha: Ph.SortAscending,
  Edit: Ph.PencilSimple,
  FindReplace: Ph.MagnifyingGlassPlus,
  Translate: Ph.Translate,
  RecordVoiceOver: Ph.SpeakerHigh,
  ManageSearch: Ph.MagnifyingGlass,
  CleaningServices: Ph.Broom,
  Password: Ph.Key,
  Fingerprint: Ph.Fingerprint,
  Tag: Ph.Hash,
  Face: Ph.UserCircle,
  Gradient: Ph.PaintBucket,
  Person: Ph.User,
  DataArray: Ph.ListBullets,
  Link: Ph.Link,
  Css: Ph.FileCss,
  Javascript: Ph.FileJs,
  Html: Ph.FileHtml,
  TableView: Ph.Table,
  Http: Ph.Browser,
  InsertDriveFile: Ph.File,
  ViewQuilt: Ph.Rows,
  GridView: Ph.GridFour,
  VpnKey: Ph.Key,
  BadgeCheck: Ph.IdentificationBadge,
  IdentificationCard: Ph.IdentificationCard,
  PhoneAndroid: Ph.DeviceMobile,

  // Media tools
  GraphicEq: Ph.WaveSawtooth,
  WaterDrop: Ph.Drop,
  Waves: Ph.WaveSine,
  AspectRatio: Ph.FrameCorners,
  MonitorWeight: Ph.Scales,
  Scale: Ph.Scales,
  LocalDining: Ph.ForkKnife,
  Accessibility: Ph.PersonSimple,
  AccessibilityNew: Ph.PersonSimpleRun,

  // Image / photo
  BlurOn: Ph.CircleHalf,
  ImageSearch: Ph.MagnifyingGlassPlus,
  PhotoLibrary: Ph.Images,
  Brush: Ph.PaintBrush,
  Slideshow: Ph.PresentationChart,
  PhotoCamera: Ph.Camera,
  Crop75: Ph.Crop,

  // PDF
  DeleteSweep: Ph.TrashSimple,
  FilePresent: Ph.FileText,
  PictureInPicture: Ph.FrameCorners,
  TextSnippet: Ph.FileText,
  Description: Ph.FileText,
  AssignmentInd: Ph.UserList,
  PdfDocument: Ph.FilePdf,

  // Calculators
  Calculator: Ph.Calculator,
  Numbers: Ph.Hash,
  Pin: Ph.PushPin,
  Pi: Ph.NumberCircleZero,
  ShowChart: Ph.ChartLine,
  Insights: Ph.ChartBar,
  MultilineChart: Ph.ChartLineUp,

  // Health
  Favorite: Ph.Heart,
  MonitorHeart: Ph.HeartStraight,
  WaterDamage: Ph.Drop,
  Bedtime: Ph.Bed,
  PregnantWoman: Ph.Baby,
  ChildCare: Ph.Baby,

  // Finance
  AttachMoney: Ph.CurrencyDollarSimple,
  Savings: Ph.PiggyBank,
  AccountBalanceWallet: Ph.Wallet,
  RequestQuote: Ph.Receipt,

  // Productivity
  Note: Ph.Note,
  NoteAlt: Ph.NotePencil,
  Checklist: Ph.CheckSquare,
  AccessAlarm: Ph.Alarm,
  HourglassEmpty: Ph.Hourglass,
  Today: Ph.CalendarDots,
  EventNote: Ph.CalendarPlus,

  // Entertainment
  Cyclone: Ph.Atom,
  Toll: Ph.Coin,
  Psychology: Ph.Brain,
  Public: Ph.Globe,
  Pets: Ph.PawPrint,
  EmojiNature: Ph.Leaf,
  EmojiEvents: Ph.Trophy,
  EmojiObjects: Ph.Lightbulb,
  Mood: Ph.Smiley,
  Apps: Ph.AppWindow,

  // Symbols
  FormatQuote: Ph.Quotes,
  Category: Ph.SquaresFour,

  // Network / Dev
  Router: Ph.WifiHigh,
  Cloud: Ph.Cloud,
  CloudUpload: Ph.CloudArrowUp,
  CloudDownload: Ph.CloudArrowDown,
  Dns: Ph.HardDrives,
  Domain: Ph.Buildings,
  Public2: Ph.Globe,
  CalendarMonthIcon: Ph.Calendar,

  // Misc
  SmartToy: Ph.Robot,
  AutoStories: Ph.BookOpen,
  MenuBook: Ph.BookOpen,
  Book: Ph.BookOpen,
  ContentPaste: Ph.ClipboardText,
  Newspaper: Ph.NewspaperClipping,
  RssFeed: Ph.RssSimple,
  Map: Ph.MapTrifold,
  Forum: Ph.ChatsCircle,
  Chat: Ph.ChatCircle,
  Email: Ph.EnvelopeSimple,
  Sms: Ph.ChatTeardropText,
  Phone: Ph.Phone,
  PhoneIphone: Ph.DeviceMobileCamera,
  Wifi: Ph.WifiHigh,
  Battery: Ph.BatteryHigh,
  Lightbulb: Ph.Lightbulb,
  Visibility2: Ph.Eye,
  WatchLater: Ph.Clock,
  Update: Ph.ArrowsClockwise,
  Refresh: Ph.ArrowsClockwise,
  Sync: Ph.ArrowsClockwise,
  Build: Ph.Wrench,
  Handyman: Ph.Wrench,
  Engineering: Ph.Gear,
  Inventory: Ph.Package,
  ShoppingCart: Ph.ShoppingCart,
  LocalShipping: Ph.Truck,
  Restaurant: Ph.ForkKnife,

  // Catch-all fallbacks for any other Material-style names
  HelpOutline: Ph.Question,
  InfoOutline: Ph.Info,
  Tune: Ph.SlidersHorizontal,
  FilterAlt: Ph.Funnel,
  Sort: Ph.SortAscending,
  ImportExport: Ph.ArrowsDownUp,
  ZoomIn: Ph.MagnifyingGlassPlus,
  ZoomOut: Ph.MagnifyingGlassMinus,

  // Common fallbacks for various tools (extending as needed)
  ContentCopy: Ph.Copy,
  Download: Ph.DownloadSimple,
  Upload: Ph.UploadSimple,
  Settings: Ph.Gear,
  Search: Ph.MagnifyingGlass,
  Close: Ph.X,
  Check: Ph.Check,
  Add: Ph.Plus,
  Remove: Ph.Minus,
  ArrowForward: Ph.ArrowRight,
  ArrowBack: Ph.ArrowLeft,
  ExpandMore: Ph.CaretDown,
  ExpandLess: Ph.CaretUp,
  ChevronRight: Ph.CaretRight,
  ChevronLeft: Ph.CaretLeft,
  Home: Ph.House,
  Menu: Ph.List,
  MoreVert: Ph.DotsThreeVertical,
  MoreHoriz: Ph.DotsThree,
  Info: Ph.Info,
  Warning: Ph.Warning,
  Error: Ph.WarningCircle,
  CheckCircleOutline: Ph.CheckCircle,
  FavoriteBorder: Ph.Heart,
  Star: Ph.Star,
  StarBorder: Ph.Star,
  History: Ph.ClockCounterClockwise,
  DarkMode: Ph.Moon,
  LightMode: Ph.Sun,
  Construction: Ph.Wrench,
  NavigateNext: Ph.CaretRight,
  Visibility: Ph.Eye,
  VisibilityOff: Ph.EyeSlash,
  Lock: Ph.Lock,
};

const FALLBACK = Ph.Toolbox;

export type IconName = keyof typeof ICON_MAP | string;

export interface UltiIconProps extends Omit<IconProps, 'ref'> {
  name: IconName;
}

export function Icon({ name, weight = 'regular', size = 20, ...rest }: UltiIconProps) {
  const Component = (ICON_MAP[name as string] as IconType | undefined) ?? FALLBACK;
  return <Component weight={weight} size={size} {...rest} />;
}
