import type { Locale } from "@/i18n/config";
import type { ZalgoLevel } from "./styles";

/** UI strings of the fonts tool (client components). */
export const T = {
  ru: {
    input: "Ваш текст",
    clear: "Очистить",
    sampleHint: "Сейчас показан пример — напишите свой текст.",
    copy: "Копировать",
    copied: "Скопировано",
    clickToCopy: "Нажмите на строку, чтобы скопировать",
    allStyles: "Все стили",
    otherStyles: "Другие стили",
    goodFor: (p: string) => `Подходят для ${p}`,
    regenerate: "Заново",
    regenerateLabel: "Сгенерировать знаки заново",
    intensity: "Сила эффекта",
    zalgo: { light: "Слабо", medium: "Средне", heavy: "Сильно" } as Record<ZalgoLevel, string>,
    cyrOnly: "Только с кириллицей",
    badgeNone: "кириллица не меняется",
    badgePartial: "кириллица частично",
    noticeNone: (digits: boolean) => `Русские буквы останутся обычными: этот стиль меняет только латиницу${digits ? " и цифры" : ""}.`,
    noticePartial: "Часть русских букв останется без изменений: похожих символов для них в Unicode нет.",
    xCount: "по правилам X",
    copyCount: "Сколько символов копировать",
    unicodeLetter: "буква",
    unicodeSymbol: "символ",
    unicodeFormat: "служебный",
    unicodeSpace: "пробел",
    unicodeMark: "знак",
    width: "Ширина символа в вашем браузере — между скобками",
  },
  en: {
    input: "Your text",
    clear: "Clear",
    sampleHint: "A sample is shown — type your own text.",
    copy: "Copy",
    copied: "Copied",
    clickToCopy: "Click a row to copy it",
    allStyles: "All styles",
    otherStyles: "Other styles",
    goodFor: (p: string) => `Good for ${p}`,
    regenerate: "Again",
    regenerateLabel: "Regenerate the marks",
    intensity: "Intensity",
    zalgo: { light: "Light", medium: "Medium", heavy: "Heavy" } as Record<ZalgoLevel, string>,
    cyrOnly: "Cyrillic only",
    badgeNone: "Cyrillic unchanged",
    badgePartial: "Cyrillic partly",
    noticeNone: (digits: boolean) => `Cyrillic letters stay plain: this style only changes Latin letters${digits ? " and digits" : ""}.`,
    noticePartial: "Some Cyrillic letters stay unchanged: Unicode has no look-alikes for them.",
    xCount: "by X rules",
    copyCount: "How many to copy",
    unicodeLetter: "letter",
    unicodeSymbol: "symbol",
    unicodeFormat: "format",
    unicodeSpace: "space",
    unicodeMark: "mark",
    width: "The character's width in your browser — between the brackets",
  },
} as const;

export type Strings = (typeof T)[Locale];
