// Copies the Unicode name index (generated by scripts/data/gen-symbols.mjs) to public/vendor/symbols/.
import { cpSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const dest = join(root, "public", "vendor", "symbols");
mkdirSync(dest, { recursive: true });
cpSync(join(root, "src", "sections", "symbols", "data", "client"), dest, { recursive: true });
