// Copies the emoji search index (generated by scripts/data/gen-emoji.mjs) to public/vendor/emoji/.
import { cpSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const dest = join(root, "public", "vendor", "emoji");
mkdirSync(dest, { recursive: true });
cpSync(join(root, "src", "sections", "emoji", "data", "client"), dest, { recursive: true });
