export interface KzCity {
  slug: string;
  name: { ru: string; en: string };
  region: { ru: string; en: string };
  residentialTariff: number; // KZT per kWh
  commercialTariff: number; // KZT per kWh
  utility: string;
}

export const KZ_CITIES: readonly KzCity[] = [
  {
    slug: "almaty",
    name: { ru: "Алматы", en: "Almaty" },
    region: { ru: "г. Алматы", en: "Almaty City" },
    residentialTariff: 35.5,
    commercialTariff: 45.59,
    utility: "АлматыЭнергоСбыт",
  },
  {
    slug: "astana",
    name: { ru: "Астана", en: "Astana" },
    region: { ru: "г. Астана", en: "Astana City" },
    residentialTariff: 32.8,
    commercialTariff: 38.14,
    utility: "Астанаэнергосбыт",
  },
  {
    slug: "shymkent",
    name: { ru: "Шымкент", en: "Shymkent" },
    region: { ru: "г. Шымкент", en: "Shymkent City" },
    residentialTariff: 31.2,
    commercialTariff: 36.77,
    utility: "Энергопоток",
  },
  {
    slug: "karaganda",
    name: { ru: "Караганда", en: "Karaganda" },
    region: { ru: "Карагандинская обл.", en: "Karaganda Region" },
    residentialTariff: 26.4,
    commercialTariff: 38.87,
    utility: "КарагандаЖарык",
  },
  {
    slug: "atyrau",
    name: { ru: "Атырау", en: "Atyrau" },
    region: { ru: "Атырауская обл.", en: "Atyrau Region" },
    residentialTariff: 28.44,
    commercialTariff: 52.36,
    utility: "Атырау Энергосату",
  },
  {
    slug: "pavlodar",
    name: { ru: "Павлодар", en: "Pavlodar" },
    region: { ru: "Павлодарская обл.", en: "Pavlodar Region" },
    residentialTariff: 21.5,
    commercialTariff: 28.4,
    utility: "Павлодарэнергосбыт",
  },
  {
    slug: "aktobe",
    name: { ru: "Актобе", en: "Aktobe" },
    region: { ru: "Актюбинская обл.", en: "Aktobe Region" },
    residentialTariff: 24.2,
    commercialTariff: 31.6,
    utility: "Актобеэнергоснаб",
  },
  {
    slug: "ust-kamenogorsk",
    name: { ru: "Усть-Каменогорск", en: "Ust-Kamenogorsk" },
    region: { ru: "Восточно-Казахстанская обл.", en: "East Kazakhstan Region" },
    residentialTariff: 19.8,
    commercialTariff: 27.9,
    utility: "Шыгысэнерготрейд",
  },
  {
    slug: "semey",
    name: { ru: "Семей", en: "Semey" },
    region: { ru: "Абайская обл.", en: "Abai Region" },
    residentialTariff: 21.4,
    commercialTariff: 29.1,
    utility: "Шыгысэнерготрейд",
  },
  {
    slug: "kostanay",
    name: { ru: "Костанай", en: "Kostanay" },
    region: { ru: "Костанайская обл.", en: "Kostanay Region" },
    residentialTariff: 33.2,
    commercialTariff: 38.51,
    utility: "ЭПК-forfait",
  },
  {
    slug: "aktau",
    name: { ru: "Актау", en: "Aktau" },
    region: { ru: "Мангистауская обл.", en: "Mangystau Region" },
    residentialTariff: 26.5,
    commercialTariff: 34.2,
    utility: "Мангистау Жарык",
  },
  {
    slug: "uralsk",
    name: { ru: "Уральск", en: "Uralsk" },
    region: { ru: "Западно-Казахстанская обл.", en: "West Kazakhstan Region" },
    residentialTariff: 25.8,
    commercialTariff: 33.4,
    utility: "Батыс Энергоресурсы",
  },
  {
    slug: "taraz",
    name: { ru: "Тараз", en: "Taraz" },
    region: { ru: "Жамбылская обл.", en: "Zhambyl Region" },
    residentialTariff: 27.6,
    commercialTariff: 35.2,
    utility: "Жамбыл Жарык Сауда",
  },
  {
    slug: "kyzylorda",
    name: { ru: "Кызылорда", en: "Kyzylorda" },
    region: { ru: "Кызылординская обл.", en: "Kyzylorda Region" },
    residentialTariff: 25.1,
    commercialTariff: 32.8,
    utility: "Кызылордаэнергоцентр",
  },
  {
    slug: "petropavlovsk",
    name: { ru: "Петропавловск", en: "Petropavlovsk" },
    region: { ru: "Северо-Казахстанская обл.", en: "North Kazakhstan Region" },
    residentialTariff: 23.4,
    commercialTariff: 30.5,
    utility: "Севказэнергосбыт",
  },
  {
    slug: "temirtau",
    name: { ru: "Темиртау", en: "Temirtau" },
    region: { ru: "Карагандинская обл.", en: "Karaganda Region" },
    residentialTariff: 22.8,
    commercialTariff: 32.1,
    utility: "Окжетпес-Т",
  },
  {
    slug: "turkistan",
    name: { ru: "Туркестан", en: "Turkistan" },
    region: { ru: "Туркестанская обл.", en: "Turkistan Region" },
    residentialTariff: 29.5,
    commercialTariff: 37.1,
    utility: "Энергопоток",
  },
  {
    slug: "kokshetau",
    name: { ru: "Кокшетау", en: "Kokshetau" },
    region: { ru: "Акмолинская обл.", en: "Akmola Region" },
    residentialTariff: 28.2,
    commercialTariff: 36.4,
    utility: "Кокшетау Энерго",
  },
] as const;

export type PrinterBrand =
  | "bambu"
  | "creality"
  | "anycubic"
  | "elegoo"
  | "qidi"
  | "flashforge"
  | "flyingbear"
  | "kingroon"
  | "artillery"
  | "twotrees"
  | "snapmaker"
  | "raise3d"
  | "custom";

export type PrinterId =
  // Bambu Lab (Newest -> Oldest)
  | "h2d"
  | "h2c"
  | "h2s"
  | "p2s"
  | "x1e"
  | "p1s"
  | "a1"
  | "a1_mini"
  | "x1c"
  // Creality (Newest -> Oldest)
  | "ender3_v4"
  | "creality_hi"
  | "k2_plus"
  | "k1c"
  | "k1_max"
  | "k1"
  | "ender3_v3"
  | "ender3_v3_plus"
  | "ender3_v3_ke"
  | "ender3_v3_se"
  | "cr10_se"
  | "cr_m4"
  | "sermoon_d3"
  | "ender5_s1"
  | "sermoon_v1"
  | "ender3_s1_pro"
  | "ender3_v2_neo"
  | "sermoon_d1"
  | "cr6_se"
  | "ender5"
  | "cr10"
  | "ender3_v2"
  | "ender3"
  // Anycubic (Newest -> Oldest)
  | "kobra_s1_max"
  | "kobra3_combo"
  | "kobra2_max"
  | "kobra2_plus"
  | "kobra2_pro"
  | "kobra2"
  | "kobra2_neo"
  | "kobra_plus_max"
  | "kobra_neo"
  | "anycubic_vyper"
  | "anycubic_4max_pro2"
  | "anycubic_mega_x"
  | "anycubic_mega_s"
  | "anycubic_mega_zero"
  | "anycubic_chiron"
  | "anycubic_predator"
  // Elegoo (Newest -> Oldest)
  | "centauri_2"
  | "centauri"
  | "neptune4_max"
  | "neptune4_plus"
  | "neptune4_pro"
  | "neptune4"
  | "neptune3_max"
  | "neptune3_plus"
  | "neptune3_pro"
  | "neptune3"
  | "neptune2s"
  | "neptune_x"
  // QIDI Tech (Newest -> Oldest)
  | "max4"
  | "plus4"
  | "q1_pro"
  | "x_max3"
  | "x_plus3"
  | "x_smart3"
  | "x_cf_pro"
  | "i_fast"
  | "i_mate_s"
  | "x_max_2"
  // Flashforge (Newest -> Oldest)
  | "ad5x"
  | "adventurer5m_pro"
  | "adventurer5m"
  | "guider3_ultra"
  | "guider3"
  | "creator4"
  | "adventurer4"
  | "artemis"
  | "finder3"
  | "creator3"
  | "creator_pro2"
  | "guider2s"
  | "adventurer3"
  | "creator_pro"
  // Flying Bear (Newest -> Oldest)
  | "reborn2"
  | "ghost6"
  | "ghost5"
  // Kingroon (Newest -> Oldest)
  | "klp1"
  | "kp3s_pro_v2"
  | "kp3s_pro"
  | "kp3s"
  // Artillery (Newest -> Oldest)
  | "sidewinder_x4_plus"
  | "sidewinder_x4"
  | "sidewinder_x2"
  | "genius_pro"
  // Two Trees (Newest -> Oldest)
  | "sk1"
  | "bluer_plus"
  | "sapphire_plus"
  // Snapmaker (Newest -> Oldest)
  | "snapmaker_u1"
  | "snapmaker_j1"
  | "snapmaker_2"
  // Raise3D & UltiMaker (Newest -> Oldest)
  | "raise3d_pro3_plus"
  | "raise3d_pro3"
  | "ultimaker_s7"
  | "ultimaker_s5"
  // Custom
  | "custom";

export interface PrinterProfile {
  id: PrinterId;
  brand: PrinterBrand;
  name: string;
  shortName: string;
  enclosed: boolean;
  powerByMaterial: Record<string, number>; // Base active wattage
  defaultPower: number; // Watts
  priceKzt: number;
  amsPriceKzt?: number;
  lifespanHours: number;
  depreciationPerHour: number; // KZT / hour
  multiColorCapable: boolean;
  multiColorSystem: string;
}

export type SupportsType = "none" | "light" | "medium" | "heavy" | "custom";

export interface SupportsOption {
  id: SupportsType;
  name: { ru: string; en: string };
  pct: number;
}

export const SUPPORTS_OPTIONS: Record<SupportsType, SupportsOption> = {
  none: { id: "none", name: { ru: "Без поддержек (0%)", en: "No supports (0%)" }, pct: 0 },
  light: { id: "light", name: { ru: "Лёгкие / древовидные (+10%)", en: "Light / Tree (+10%)" }, pct: 10 },
  medium: { id: "medium", name: { ru: "Стандартные (+20%)", en: "Standard (+20%)" }, pct: 20 },
  heavy: { id: "heavy", name: { ru: "Массивные / сложные (+35%)", en: "Dense / Complex (+35%)" }, pct: 35 },
  custom: { id: "custom", name: { ru: "Свой вес в граммах", en: "Custom weight (g)" }, pct: 0 },
};

export const PRINTER_PROFILES: Record<PrinterId, PrinterProfile> = {
  // ── Bambu Lab (Newest -> Oldest) ──
  h2d: {
    id: "h2d",
    brand: "bambu",
    name: "Bambu Lab H2D",
    shortName: "Bambu H2D",
    enclosed: true,
    powerByMaterial: { pla: 190, petg: 240, abs: 420, tpu: 190, pacf: 450 },
    defaultPower: 380,
    priceKzt: 1_250_000,
    amsPriceKzt: 180_000,
    lifespanHours: 10000,
    depreciationPerHour: 125,
    multiColorCapable: true,
    multiColorSystem: "Dual-Nozzle IDEX + AMS",
  },
  h2c: {
    id: "h2c",
    brand: "bambu",
    name: "Bambu Lab H2C",
    shortName: "Bambu H2C",
    enclosed: true,
    powerByMaterial: { pla: 180, petg: 230, abs: 400, tpu: 180, pacf: 440 },
    defaultPower: 360,
    priceKzt: 1_400_000,
    amsPriceKzt: 180_000,
    lifespanHours: 10000,
    depreciationPerHour: 140,
    multiColorCapable: true,
    multiColorSystem: "Vortek Tool-Changer",
  },
  h2s: {
    id: "h2s",
    brand: "bambu",
    name: "Bambu Lab H2S",
    shortName: "Bambu H2S",
    enclosed: true,
    powerByMaterial: { pla: 170, petg: 220, abs: 380, tpu: 170, pacf: 400 },
    defaultPower: 280,
    priceKzt: 950_000,
    amsPriceKzt: 180_000,
    lifespanHours: 9000,
    depreciationPerHour: 106,
    multiColorCapable: true,
    multiColorSystem: "Bambu AMS",
  },
  p2s: {
    id: "p2s",
    brand: "bambu",
    name: "Bambu Lab P2S",
    shortName: "Bambu P2S",
    enclosed: true,
    powerByMaterial: { pla: 120, petg: 150, abs: 210, tpu: 120, pacf: 220 },
    defaultPower: 145,
    priceKzt: 420_000,
    amsPriceKzt: 180_000,
    lifespanHours: 7000,
    depreciationPerHour: 60,
    multiColorCapable: true,
    multiColorSystem: "Bambu AMS",
  },
  x1e: {
    id: "x1e",
    brand: "bambu",
    name: "Bambu Lab X1E",
    shortName: "Bambu X1E",
    enclosed: true,
    powerByMaterial: { pla: 150, petg: 190, abs: 320, tpu: 150, pacf: 350 },
    defaultPower: 260,
    priceKzt: 1_100_000,
    amsPriceKzt: 180_000,
    lifespanHours: 9000,
    depreciationPerHour: 122,
    multiColorCapable: true,
    multiColorSystem: "Bambu AMS",
  },
  p1s: {
    id: "p1s",
    brand: "bambu",
    name: "Bambu Lab P1S / P1P",
    shortName: "Bambu P1S",
    enclosed: true,
    powerByMaterial: { pla: 105, petg: 135, abs: 190, tpu: 105, pacf: 190 },
    defaultPower: 130,
    priceKzt: 340_000,
    amsPriceKzt: 180_000,
    lifespanHours: 6000,
    depreciationPerHour: 57,
    multiColorCapable: true,
    multiColorSystem: "Bambu AMS",
  },
  a1: {
    id: "a1",
    brand: "bambu",
    name: "Bambu Lab A1",
    shortName: "Bambu A1",
    enclosed: false,
    powerByMaterial: { pla: 85, petg: 110, abs: 140, tpu: 85, pacf: 140 },
    defaultPower: 95,
    priceKzt: 210_000,
    amsPriceKzt: 120_000,
    lifespanHours: 4500,
    depreciationPerHour: 47,
    multiColorCapable: true,
    multiColorSystem: "Bambu AMS lite",
  },
  a1_mini: {
    id: "a1_mini",
    brand: "bambu",
    name: "Bambu Lab A1 mini",
    shortName: "A1 mini",
    enclosed: false,
    powerByMaterial: { pla: 55, petg: 75, abs: 90, tpu: 55, pacf: 90 },
    defaultPower: 65,
    priceKzt: 130_000,
    amsPriceKzt: 95_000,
    lifespanHours: 3500,
    depreciationPerHour: 37,
    multiColorCapable: true,
    multiColorSystem: "Bambu AMS lite",
  },
  x1c: {
    id: "x1c",
    brand: "bambu",
    name: "Bambu Lab X1-Carbon",
    shortName: "X1-Carbon",
    enclosed: true,
    powerByMaterial: { pla: 120, petg: 150, abs: 210, tpu: 120, pacf: 210 },
    defaultPower: 140,
    priceKzt: 550_000,
    amsPriceKzt: 180_000,
    lifespanHours: 7000,
    depreciationPerHour: 79,
    multiColorCapable: true,
    multiColorSystem: "Bambu AMS",
  },

  // ── Creality (Newest -> Oldest) ──
  ender3_v4: {
    id: "ender3_v4",
    brand: "creality",
    name: "Creality Ender-3 V4 Combo / V4",
    shortName: "Ender-3 V4",
    enclosed: false,
    powerByMaterial: { pla: 120, petg: 145, abs: 185, tpu: 120, pacf: 185 },
    defaultPower: 135,
    priceKzt: 225_000,
    amsPriceKzt: 140_000,
    lifespanHours: 4500,
    depreciationPerHour: 50,
    multiColorCapable: true,
    multiColorSystem: "Creality CFS",
  },
  creality_hi: {
    id: "creality_hi",
    brand: "creality",
    name: "Creality Hi Combo / Hi",
    shortName: "Creality Hi",
    enclosed: false,
    powerByMaterial: { pla: 130, petg: 155, abs: 195, tpu: 130, pacf: 195 },
    defaultPower: 145,
    priceKzt: 260_000,
    amsPriceKzt: 140_000,
    lifespanHours: 5000,
    depreciationPerHour: 52,
    multiColorCapable: true,
    multiColorSystem: "Creality CFS",
  },
  k2_plus: {
    id: "k2_plus",
    brand: "creality",
    name: "Creality K2 Plus",
    shortName: "K2 Plus",
    enclosed: true,
    powerByMaterial: { pla: 190, petg: 230, abs: 420, tpu: 190, pacf: 450 },
    defaultPower: 280,
    priceKzt: 580_000,
    amsPriceKzt: 180_000,
    lifespanHours: 6000,
    depreciationPerHour: 97,
    multiColorCapable: true,
    multiColorSystem: "Creality CFS",
  },
  k1c: {
    id: "k1c",
    brand: "creality",
    name: "Creality K1C",
    shortName: "Creality K1C",
    enclosed: true,
    powerByMaterial: { pla: 130, petg: 160, abs: 210, tpu: 130, pacf: 220 },
    defaultPower: 150,
    priceKzt: 310_000,
    amsPriceKzt: 160_000,
    lifespanHours: 5000,
    depreciationPerHour: 62,
    multiColorCapable: true,
    multiColorSystem: "Creality CFS",
  },
  k1_max: {
    id: "k1_max",
    brand: "creality",
    name: "Creality K1 Max",
    shortName: "K1 Max",
    enclosed: true,
    powerByMaterial: { pla: 175, petg: 210, abs: 250, tpu: 175, pacf: 250 },
    defaultPower: 190,
    priceKzt: 420_000,
    amsPriceKzt: 160_000,
    lifespanHours: 5500,
    depreciationPerHour: 76,
    multiColorCapable: true,
    multiColorSystem: "Creality CFS",
  },
  k1: {
    id: "k1",
    brand: "creality",
    name: "Creality K1",
    shortName: "Creality K1",
    enclosed: true,
    powerByMaterial: { pla: 125, petg: 155, abs: 195, tpu: 125, pacf: 195 },
    defaultPower: 140,
    priceKzt: 290_000,
    amsPriceKzt: 160_000,
    lifespanHours: 5000,
    depreciationPerHour: 58,
    multiColorCapable: true,
    multiColorSystem: "Creality CFS",
  },
  ender3_v3: {
    id: "ender3_v3",
    brand: "creality",
    name: "Creality Ender-3 V3 (CoreXZ)",
    shortName: "Ender-3 V3",
    enclosed: false,
    powerByMaterial: { pla: 120, petg: 145, abs: 185, tpu: 120, pacf: 185 },
    defaultPower: 135,
    priceKzt: 165_000,
    amsPriceKzt: 0,
    lifespanHours: 4000,
    depreciationPerHour: 41,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  ender3_v3_plus: {
    id: "ender3_v3_plus",
    brand: "creality",
    name: "Creality Ender-3 V3 Plus",
    shortName: "Ender-3 V3 Plus",
    enclosed: false,
    powerByMaterial: { pla: 130, petg: 155, abs: 195, tpu: 130, pacf: 195 },
    defaultPower: 145,
    priceKzt: 180_000,
    amsPriceKzt: 0,
    lifespanHours: 4000,
    depreciationPerHour: 45,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  ender3_v3_ke: {
    id: "ender3_v3_ke",
    brand: "creality",
    name: "Creality Ender-3 V3 KE",
    shortName: "Ender-3 V3 KE",
    enclosed: false,
    powerByMaterial: { pla: 110, petg: 135, abs: 175, tpu: 110, pacf: 175 },
    defaultPower: 125,
    priceKzt: 145_000,
    amsPriceKzt: 0,
    lifespanHours: 3500,
    depreciationPerHour: 41,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  ender3_v3_se: {
    id: "ender3_v3_se",
    brand: "creality",
    name: "Creality Ender-3 V3 SE",
    shortName: "Ender-3 V3 SE",
    enclosed: false,
    powerByMaterial: { pla: 95, petg: 115, abs: 150, tpu: 95, pacf: 150 },
    defaultPower: 105,
    priceKzt: 105_000,
    amsPriceKzt: 0,
    lifespanHours: 3500,
    depreciationPerHour: 30,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  cr10_se: {
    id: "cr10_se",
    brand: "creality",
    name: "Creality CR-10 SE",
    shortName: "CR-10 SE",
    enclosed: false,
    powerByMaterial: { pla: 135, petg: 160, abs: 200, tpu: 135, pacf: 200 },
    defaultPower: 145,
    priceKzt: 195_000,
    amsPriceKzt: 0,
    lifespanHours: 4500,
    depreciationPerHour: 43,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  cr_m4: {
    id: "cr_m4",
    brand: "creality",
    name: "Creality CR-M4 (450×450)",
    shortName: "CR-M4",
    enclosed: false,
    powerByMaterial: { pla: 350, petg: 420, abs: 550, tpu: 350, pacf: 550 },
    defaultPower: 400,
    priceKzt: 520_000,
    amsPriceKzt: 0,
    lifespanHours: 6000,
    depreciationPerHour: 87,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  sermoon_d3: {
    id: "sermoon_d3",
    brand: "creality",
    name: "Creality Sermoon D3 / D3 Pro",
    shortName: "Sermoon D3",
    enclosed: true,
    powerByMaterial: { pla: 220, petg: 270, abs: 380, tpu: 220, pacf: 400 },
    defaultPower: 320,
    priceKzt: 490_000,
    amsPriceKzt: 0,
    lifespanHours: 7000,
    depreciationPerHour: 70,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  ender5_s1: {
    id: "ender5_s1",
    brand: "creality",
    name: "Creality Ender-5 S1",
    shortName: "Ender-5 S1",
    enclosed: false,
    powerByMaterial: { pla: 120, petg: 145, abs: 185, tpu: 120, pacf: 185 },
    defaultPower: 135,
    priceKzt: 210_000,
    amsPriceKzt: 0,
    lifespanHours: 4500,
    depreciationPerHour: 47,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  sermoon_v1: {
    id: "sermoon_v1",
    brand: "creality",
    name: "Creality Sermoon V1 / V1 Pro",
    shortName: "Sermoon V1 Pro",
    enclosed: true,
    powerByMaterial: { pla: 100, petg: 125, abs: 165, tpu: 100, pacf: 165 },
    defaultPower: 115,
    priceKzt: 190_000,
    amsPriceKzt: 0,
    lifespanHours: 4000,
    depreciationPerHour: 48,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  ender3_s1_pro: {
    id: "ender3_s1_pro",
    brand: "creality",
    name: "Creality Ender-3 S1 Pro / Plus",
    shortName: "Ender-3 S1 Pro",
    enclosed: false,
    powerByMaterial: { pla: 110, petg: 135, abs: 175, tpu: 110, pacf: 175 },
    defaultPower: 125,
    priceKzt: 175_000,
    amsPriceKzt: 0,
    lifespanHours: 4000,
    depreciationPerHour: 44,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  ender3_v2_neo: {
    id: "ender3_v2_neo",
    brand: "creality",
    name: "Creality Ender-3 V2 Neo / Max Neo",
    shortName: "Ender-3 V2 Neo",
    enclosed: false,
    powerByMaterial: { pla: 105, petg: 125, abs: 165, tpu: 105, pacf: 165 },
    defaultPower: 115,
    priceKzt: 125_000,
    amsPriceKzt: 0,
    lifespanHours: 3500,
    depreciationPerHour: 36,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  sermoon_d1: {
    id: "sermoon_d1",
    brand: "creality",
    name: "Creality Sermoon D1",
    shortName: "Sermoon D1",
    enclosed: true,
    powerByMaterial: { pla: 130, petg: 155, abs: 200, tpu: 130, pacf: 200 },
    defaultPower: 145,
    priceKzt: 260_000,
    amsPriceKzt: 0,
    lifespanHours: 4500,
    depreciationPerHour: 58,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  cr6_se: {
    id: "cr6_se",
    brand: "creality",
    name: "Creality CR-6 SE / Max",
    shortName: "CR-6 SE",
    enclosed: false,
    powerByMaterial: { pla: 110, petg: 130, abs: 170, tpu: 110, pacf: 170 },
    defaultPower: 120,
    priceKzt: 140_000,
    amsPriceKzt: 0,
    lifespanHours: 3500,
    depreciationPerHour: 40,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  ender5: {
    id: "ender5",
    brand: "creality",
    name: "Creality Ender-5 Pro / Plus",
    shortName: "Ender-5 Pro",
    enclosed: false,
    powerByMaterial: { pla: 115, petg: 135, abs: 175, tpu: 115, pacf: 175 },
    defaultPower: 125,
    priceKzt: 160_000,
    amsPriceKzt: 0,
    lifespanHours: 4000,
    depreciationPerHour: 40,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  cr10: {
    id: "cr10",
    brand: "creality",
    name: "Creality CR-10 Smart Pro / V3",
    shortName: "CR-10 Smart",
    enclosed: false,
    powerByMaterial: { pla: 140, petg: 165, abs: 210, tpu: 140, pacf: 210 },
    defaultPower: 155,
    priceKzt: 210_000,
    amsPriceKzt: 0,
    lifespanHours: 4500,
    depreciationPerHour: 47,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  ender3_v2: {
    id: "ender3_v2",
    brand: "creality",
    name: "Creality Ender-3 V2",
    shortName: "Ender-3 V2",
    enclosed: false,
    powerByMaterial: { pla: 100, petg: 120, abs: 160, tpu: 100, pacf: 160 },
    defaultPower: 110,
    priceKzt: 110_000,
    amsPriceKzt: 0,
    lifespanHours: 3000,
    depreciationPerHour: 37,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  ender3: {
    id: "ender3",
    brand: "creality",
    name: "Creality Ender-3 / Pro",
    shortName: "Ender-3",
    enclosed: false,
    powerByMaterial: { pla: 95, petg: 115, abs: 155, tpu: 95, pacf: 155 },
    defaultPower: 105,
    priceKzt: 85_000,
    amsPriceKzt: 0,
    lifespanHours: 3000,
    depreciationPerHour: 28,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },

  // ── Anycubic (Newest -> Oldest) ──
  kobra_s1_max: {
    id: "kobra_s1_max",
    brand: "anycubic",
    name: "Anycubic Kobra S1 Max",
    shortName: "Kobra S1 Max",
    enclosed: true,
    powerByMaterial: { pla: 160, petg: 200, abs: 280, tpu: 160, pacf: 300 },
    defaultPower: 220,
    priceKzt: 380_000,
    amsPriceKzt: 120_000,
    lifespanHours: 6000,
    depreciationPerHour: 63,
    multiColorCapable: true,
    multiColorSystem: "Anycubic ACE Pro",
  },
  kobra3_combo: {
    id: "kobra3_combo",
    brand: "anycubic",
    name: "Anycubic Kobra 3 Combo / Kobra 3",
    shortName: "Kobra 3 Combo",
    enclosed: false,
    powerByMaterial: { pla: 140, petg: 170, abs: 210, tpu: 140, pacf: 210 },
    defaultPower: 150,
    priceKzt: 170_000,
    amsPriceKzt: 110_000,
    lifespanHours: 4500,
    depreciationPerHour: 38,
    multiColorCapable: true,
    multiColorSystem: "Anycubic ACE Pro",
  },
  kobra2_max: {
    id: "kobra2_max",
    brand: "anycubic",
    name: "Anycubic Kobra 2 Max",
    shortName: "Kobra 2 Max",
    enclosed: false,
    powerByMaterial: { pla: 280, petg: 340, abs: 420, tpu: 280, pacf: 420 },
    defaultPower: 300,
    priceKzt: 280_000,
    amsPriceKzt: 0,
    lifespanHours: 4500,
    depreciationPerHour: 62,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  kobra2_plus: {
    id: "kobra2_plus",
    brand: "anycubic",
    name: "Anycubic Kobra 2 Plus",
    shortName: "Kobra 2 Plus",
    enclosed: false,
    powerByMaterial: { pla: 180, petg: 220, abs: 280, tpu: 180, pacf: 280 },
    defaultPower: 200,
    priceKzt: 195_000,
    amsPriceKzt: 0,
    lifespanHours: 4500,
    depreciationPerHour: 43,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  kobra2_pro: {
    id: "kobra2_pro",
    brand: "anycubic",
    name: "Anycubic Kobra 2 Pro",
    shortName: "Kobra 2 Pro",
    enclosed: false,
    powerByMaterial: { pla: 130, petg: 155, abs: 195, tpu: 130, pacf: 195 },
    defaultPower: 140,
    priceKzt: 155_000,
    amsPriceKzt: 0,
    lifespanHours: 4000,
    depreciationPerHour: 39,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  kobra2: {
    id: "kobra2",
    brand: "anycubic",
    name: "Anycubic Kobra 2",
    shortName: "Kobra 2",
    enclosed: false,
    powerByMaterial: { pla: 110, petg: 130, abs: 170, tpu: 110, pacf: 170 },
    defaultPower: 120,
    priceKzt: 125_000,
    amsPriceKzt: 0,
    lifespanHours: 3500,
    depreciationPerHour: 36,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  kobra2_neo: {
    id: "kobra2_neo",
    brand: "anycubic",
    name: "Anycubic Kobra 2 Neo",
    shortName: "Kobra 2 Neo",
    enclosed: false,
    powerByMaterial: { pla: 95, petg: 115, abs: 150, tpu: 95, pacf: 150 },
    defaultPower: 105,
    priceKzt: 95_000,
    amsPriceKzt: 0,
    lifespanHours: 3000,
    depreciationPerHour: 32,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  kobra_plus_max: {
    id: "kobra_plus_max",
    brand: "anycubic",
    name: "Anycubic Kobra Max / Plus",
    shortName: "Kobra Max",
    enclosed: false,
    powerByMaterial: { pla: 260, petg: 320, abs: 400, tpu: 260, pacf: 400 },
    defaultPower: 280,
    priceKzt: 220_000,
    amsPriceKzt: 0,
    lifespanHours: 4000,
    depreciationPerHour: 55,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  kobra_neo: {
    id: "kobra_neo",
    brand: "anycubic",
    name: "Anycubic Kobra / Kobra Neo",
    shortName: "Kobra Neo",
    enclosed: false,
    powerByMaterial: { pla: 100, petg: 120, abs: 160, tpu: 100, pacf: 160 },
    defaultPower: 110,
    priceKzt: 105_000,
    amsPriceKzt: 0,
    lifespanHours: 3000,
    depreciationPerHour: 35,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  anycubic_vyper: {
    id: "anycubic_vyper",
    brand: "anycubic",
    name: "Anycubic Vyper",
    shortName: "Vyper",
    enclosed: false,
    powerByMaterial: { pla: 115, petg: 140, abs: 180, tpu: 115, pacf: 180 },
    defaultPower: 130,
    priceKzt: 130_000,
    amsPriceKzt: 0,
    lifespanHours: 3500,
    depreciationPerHour: 37,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  anycubic_4max_pro2: {
    id: "anycubic_4max_pro2",
    brand: "anycubic",
    name: "Anycubic 4Max Pro 2.0",
    shortName: "4Max Pro 2.0",
    enclosed: true,
    powerByMaterial: { pla: 125, petg: 155, abs: 210, tpu: 125, pacf: 220 },
    defaultPower: 145,
    priceKzt: 180_000,
    amsPriceKzt: 0,
    lifespanHours: 4500,
    depreciationPerHour: 40,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  anycubic_mega_x: {
    id: "anycubic_mega_x",
    brand: "anycubic",
    name: "Anycubic Mega X (300×300)",
    shortName: "Mega X",
    enclosed: false,
    powerByMaterial: { pla: 150, petg: 185, abs: 240, tpu: 150, pacf: 240 },
    defaultPower: 170,
    priceKzt: 145_000,
    amsPriceKzt: 0,
    lifespanHours: 4000,
    depreciationPerHour: 36,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  anycubic_mega_s: {
    id: "anycubic_mega_s",
    brand: "anycubic",
    name: "Anycubic Mega S / Mega Pro",
    shortName: "Mega S",
    enclosed: false,
    powerByMaterial: { pla: 95, petg: 115, abs: 150, tpu: 95, pacf: 150 },
    defaultPower: 105,
    priceKzt: 105_000,
    amsPriceKzt: 0,
    lifespanHours: 3500,
    depreciationPerHour: 30,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  anycubic_mega_zero: {
    id: "anycubic_mega_zero",
    brand: "anycubic",
    name: "Anycubic Mega Zero 2.0",
    shortName: "Mega Zero",
    enclosed: false,
    powerByMaterial: { pla: 80, petg: 100, abs: 130, tpu: 80, pacf: 130 },
    defaultPower: 90,
    priceKzt: 75_000,
    amsPriceKzt: 0,
    lifespanHours: 2500,
    depreciationPerHour: 30,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  anycubic_chiron: {
    id: "anycubic_chiron",
    brand: "anycubic",
    name: "Anycubic Chiron (400×400)",
    shortName: "Chiron",
    enclosed: false,
    powerByMaterial: { pla: 270, petg: 330, abs: 420, tpu: 270, pacf: 420 },
    defaultPower: 300,
    priceKzt: 190_000,
    amsPriceKzt: 0,
    lifespanHours: 4000,
    depreciationPerHour: 48,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  anycubic_predator: {
    id: "anycubic_predator",
    brand: "anycubic",
    name: "Anycubic Predator Delta",
    shortName: "Predator Delta",
    enclosed: false,
    powerByMaterial: { pla: 220, petg: 270, abs: 350, tpu: 220, pacf: 350 },
    defaultPower: 250,
    priceKzt: 210_000,
    amsPriceKzt: 0,
    lifespanHours: 4000,
    depreciationPerHour: 53,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },

  // ── Elegoo (Newest -> Oldest) ──
  centauri_2: {
    id: "centauri_2",
    brand: "elegoo",
    name: "Elegoo Centauri Carbon 2 Combo",
    shortName: "Centauri Carbon 2",
    enclosed: true,
    powerByMaterial: { pla: 140, petg: 170, abs: 220, tpu: 140, pacf: 230 },
    defaultPower: 160,
    priceKzt: 340_000,
    amsPriceKzt: 140_000,
    lifespanHours: 6000,
    depreciationPerHour: 57,
    multiColorCapable: true,
    multiColorSystem: "Elegoo Color Module",
  },
  centauri: {
    id: "centauri",
    brand: "elegoo",
    name: "Elegoo Centauri Carbon",
    shortName: "Centauri Carbon",
    enclosed: true,
    powerByMaterial: { pla: 130, petg: 160, abs: 200, tpu: 130, pacf: 200 },
    defaultPower: 150,
    priceKzt: 280_000,
    amsPriceKzt: 140_000,
    lifespanHours: 5000,
    depreciationPerHour: 56,
    multiColorCapable: true,
    multiColorSystem: "Elegoo Multi-Color",
  },
  neptune4_max: {
    id: "neptune4_max",
    brand: "elegoo",
    name: "Elegoo Neptune 4 Max (420×420)",
    shortName: "Neptune 4 Max",
    enclosed: false,
    powerByMaterial: { pla: 270, petg: 330, abs: 410, tpu: 270, pacf: 410 },
    defaultPower: 300,
    priceKzt: 260_000,
    amsPriceKzt: 0,
    lifespanHours: 4500,
    depreciationPerHour: 58,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  neptune4_plus: {
    id: "neptune4_plus",
    brand: "elegoo",
    name: "Elegoo Neptune 4 Plus",
    shortName: "Neptune 4 Plus",
    enclosed: false,
    powerByMaterial: { pla: 210, petg: 250, abs: 320, tpu: 210, pacf: 320 },
    defaultPower: 230,
    priceKzt: 215_000,
    amsPriceKzt: 0,
    lifespanHours: 4000,
    depreciationPerHour: 54,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  neptune4_pro: {
    id: "neptune4_pro",
    brand: "elegoo",
    name: "Elegoo Neptune 4 Pro",
    shortName: "Neptune 4 Pro",
    enclosed: false,
    powerByMaterial: { pla: 125, petg: 150, abs: 195, tpu: 125, pacf: 195 },
    defaultPower: 140,
    priceKzt: 175_000,
    amsPriceKzt: 0,
    lifespanHours: 4000,
    depreciationPerHour: 44,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  neptune4: {
    id: "neptune4",
    brand: "elegoo",
    name: "Elegoo Neptune 4",
    shortName: "Neptune 4",
    enclosed: false,
    powerByMaterial: { pla: 115, petg: 140, abs: 180, tpu: 115, pacf: 180 },
    defaultPower: 130,
    priceKzt: 145_000,
    amsPriceKzt: 0,
    lifespanHours: 3500,
    depreciationPerHour: 41,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  neptune3_max: {
    id: "neptune3_max",
    brand: "elegoo",
    name: "Elegoo Neptune 3 Max",
    shortName: "Neptune 3 Max",
    enclosed: false,
    powerByMaterial: { pla: 260, petg: 310, abs: 390, tpu: 260, pacf: 390 },
    defaultPower: 280,
    priceKzt: 220_000,
    amsPriceKzt: 0,
    lifespanHours: 4000,
    depreciationPerHour: 55,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  neptune3_plus: {
    id: "neptune3_plus",
    brand: "elegoo",
    name: "Elegoo Neptune 3 Plus",
    shortName: "Neptune 3 Plus",
    enclosed: false,
    powerByMaterial: { pla: 180, petg: 220, abs: 280, tpu: 180, pacf: 280 },
    defaultPower: 200,
    priceKzt: 170_000,
    amsPriceKzt: 0,
    lifespanHours: 4000,
    depreciationPerHour: 43,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  neptune3_pro: {
    id: "neptune3_pro",
    brand: "elegoo",
    name: "Elegoo Neptune 3 Pro",
    shortName: "Neptune 3 Pro",
    enclosed: false,
    powerByMaterial: { pla: 100, petg: 120, abs: 160, tpu: 100, pacf: 160 },
    defaultPower: 110,
    priceKzt: 120_000,
    amsPriceKzt: 0,
    lifespanHours: 3500,
    depreciationPerHour: 34,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  neptune3: {
    id: "neptune3",
    brand: "elegoo",
    name: "Elegoo Neptune 3",
    shortName: "Neptune 3",
    enclosed: false,
    powerByMaterial: { pla: 95, petg: 115, abs: 155, tpu: 95, pacf: 155 },
    defaultPower: 105,
    priceKzt: 105_000,
    amsPriceKzt: 0,
    lifespanHours: 3000,
    depreciationPerHour: 35,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  neptune2s: {
    id: "neptune2s",
    brand: "elegoo",
    name: "Elegoo Neptune 2S / 2",
    shortName: "Neptune 2S",
    enclosed: false,
    powerByMaterial: { pla: 90, petg: 110, abs: 150, tpu: 90, pacf: 150 },
    defaultPower: 100,
    priceKzt: 85_000,
    amsPriceKzt: 0,
    lifespanHours: 3000,
    depreciationPerHour: 28,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  neptune_x: {
    id: "neptune_x",
    brand: "elegoo",
    name: "Elegoo Neptune X",
    shortName: "Neptune X",
    enclosed: false,
    powerByMaterial: { pla: 105, petg: 125, abs: 165, tpu: 105, pacf: 165 },
    defaultPower: 115,
    priceKzt: 110_000,
    amsPriceKzt: 0,
    lifespanHours: 3000,
    depreciationPerHour: 37,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },

  // ── QIDI Tech (Newest -> Oldest) ──
  max4: {
    id: "max4",
    brand: "qidi",
    name: "QIDI Max4",
    shortName: "QIDI Max4",
    enclosed: true,
    powerByMaterial: { pla: 240, petg: 300, abs: 480, tpu: 240, pacf: 520 },
    defaultPower: 380,
    priceKzt: 590_000,
    amsPriceKzt: 0,
    lifespanHours: 8000,
    depreciationPerHour: 74,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  plus4: {
    id: "plus4",
    brand: "qidi",
    name: "QIDI Plus4",
    shortName: "QIDI Plus4",
    enclosed: true,
    powerByMaterial: { pla: 180, petg: 220, abs: 350, tpu: 180, pacf: 380 },
    defaultPower: 260,
    priceKzt: 420_000,
    amsPriceKzt: 0,
    lifespanHours: 6000,
    depreciationPerHour: 70,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  q1_pro: {
    id: "q1_pro",
    brand: "qidi",
    name: "QIDI Q1 Pro (Active Chamber 60°C)",
    shortName: "QIDI Q1 Pro",
    enclosed: true,
    powerByMaterial: { pla: 140, petg: 170, abs: 290, tpu: 140, pacf: 320 },
    defaultPower: 200,
    priceKzt: 290_000,
    amsPriceKzt: 0,
    lifespanHours: 5000,
    depreciationPerHour: 58,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  x_max3: {
    id: "x_max3",
    brand: "qidi",
    name: "QIDI X-Max 3 (325×325)",
    shortName: "QIDI X-Max 3",
    enclosed: true,
    powerByMaterial: { pla: 210, petg: 260, abs: 420, tpu: 210, pacf: 450 },
    defaultPower: 300,
    priceKzt: 490_000,
    amsPriceKzt: 0,
    lifespanHours: 6500,
    depreciationPerHour: 75,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  x_plus3: {
    id: "x_plus3",
    brand: "qidi",
    name: "QIDI X-Plus 3",
    shortName: "QIDI X-Plus 3",
    enclosed: true,
    powerByMaterial: { pla: 170, petg: 210, abs: 330, tpu: 170, pacf: 350 },
    defaultPower: 240,
    priceKzt: 360_000,
    amsPriceKzt: 0,
    lifespanHours: 5500,
    depreciationPerHour: 65,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  x_smart3: {
    id: "x_smart3",
    brand: "qidi",
    name: "QIDI X-Smart 3",
    shortName: "QIDI X-Smart 3",
    enclosed: true,
    powerByMaterial: { pla: 110, petg: 130, abs: 170, tpu: 110, pacf: 170 },
    defaultPower: 120,
    priceKzt: 170_000,
    amsPriceKzt: 0,
    lifespanHours: 4000,
    depreciationPerHour: 43,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  x_cf_pro: {
    id: "x_cf_pro",
    brand: "qidi",
    name: "QIDI X-CF Pro (Carbon Fiber 350°C)",
    shortName: "QIDI X-CF Pro",
    enclosed: true,
    powerByMaterial: { pla: 180, petg: 220, abs: 340, tpu: 180, pacf: 370 },
    defaultPower: 250,
    priceKzt: 380_000,
    amsPriceKzt: 0,
    lifespanHours: 5500,
    depreciationPerHour: 69,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  i_fast: {
    id: "i_fast",
    brand: "qidi",
    name: "QIDI i-Fast Dual Extruder",
    shortName: "QIDI i-Fast",
    enclosed: true,
    powerByMaterial: { pla: 220, petg: 270, abs: 380, tpu: 220, pacf: 400 },
    defaultPower: 300,
    priceKzt: 550_000,
    amsPriceKzt: 0,
    lifespanHours: 6000,
    depreciationPerHour: 92,
    multiColorCapable: true,
    multiColorSystem: "Dual Extruder",
  },
  i_mate_s: {
    id: "i_mate_s",
    brand: "qidi",
    name: "QIDI i-Mate / i-Mate S",
    shortName: "QIDI i-Mate",
    enclosed: true,
    powerByMaterial: { pla: 115, petg: 135, abs: 175, tpu: 115, pacf: 175 },
    defaultPower: 125,
    priceKzt: 190_000,
    amsPriceKzt: 0,
    lifespanHours: 4000,
    depreciationPerHour: 48,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  x_max_2: {
    id: "x_max_2",
    brand: "qidi",
    name: "QIDI X-Max / X-Plus (Classic)",
    shortName: "QIDI X-Max",
    enclosed: true,
    powerByMaterial: { pla: 140, petg: 165, abs: 220, tpu: 140, pacf: 220 },
    defaultPower: 160,
    priceKzt: 250_000,
    amsPriceKzt: 0,
    lifespanHours: 4500,
    depreciationPerHour: 56,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },

  // ── Flashforge (Newest -> Oldest) ──
  ad5x: {
    id: "ad5x",
    brand: "flashforge",
    name: "Flashforge AD5X (IFS Multi-Color)",
    shortName: "AD5X",
    enclosed: true,
    powerByMaterial: { pla: 130, petg: 160, abs: 210, tpu: 130, pacf: 210 },
    defaultPower: 150,
    priceKzt: 260_000,
    amsPriceKzt: 100_000,
    lifespanHours: 5000,
    depreciationPerHour: 52,
    multiColorCapable: true,
    multiColorSystem: "IFS (4 цвета)",
  },
  adventurer5m_pro: {
    id: "adventurer5m_pro",
    brand: "flashforge",
    name: "Flashforge Adventurer 5M Pro",
    shortName: "Adventurer 5M Pro",
    enclosed: true,
    powerByMaterial: { pla: 135, petg: 160, abs: 200, tpu: 135, pacf: 200 },
    defaultPower: 150,
    priceKzt: 240_000,
    amsPriceKzt: 0,
    lifespanHours: 5000,
    depreciationPerHour: 48,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  adventurer5m: {
    id: "adventurer5m",
    brand: "flashforge",
    name: "Flashforge Adventurer 5M",
    shortName: "Adventurer 5M",
    enclosed: false,
    powerByMaterial: { pla: 120, petg: 145, abs: 185, tpu: 120, pacf: 185 },
    defaultPower: 135,
    priceKzt: 190_000,
    amsPriceKzt: 0,
    lifespanHours: 4500,
    depreciationPerHour: 42,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  guider3_ultra: {
    id: "guider3_ultra",
    brand: "flashforge",
    name: "Flashforge Guider 3 Ultra (Dual)",
    shortName: "Guider 3 Ultra",
    enclosed: true,
    powerByMaterial: { pla: 320, petg: 380, abs: 520, tpu: 320, pacf: 550 },
    defaultPower: 450,
    priceKzt: 1_400_000,
    amsPriceKzt: 0,
    lifespanHours: 9000,
    depreciationPerHour: 156,
    multiColorCapable: true,
    multiColorSystem: "Dual Extruder",
  },
  guider3: {
    id: "guider3",
    brand: "flashforge",
    name: "Flashforge Guider 3 / 3 Plus",
    shortName: "Guider 3",
    enclosed: true,
    powerByMaterial: { pla: 220, petg: 270, abs: 380, tpu: 220, pacf: 400 },
    defaultPower: 350,
    priceKzt: 850_000,
    amsPriceKzt: 0,
    lifespanHours: 8000,
    depreciationPerHour: 106,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  creator4: {
    id: "creator4",
    brand: "flashforge",
    name: "Flashforge Creator 4 (IDEX Industrial)",
    shortName: "Creator 4",
    enclosed: true,
    powerByMaterial: { pla: 300, petg: 360, abs: 500, tpu: 300, pacf: 550 },
    defaultPower: 420,
    priceKzt: 1_600_000,
    amsPriceKzt: 0,
    lifespanHours: 9000,
    depreciationPerHour: 178,
    multiColorCapable: true,
    multiColorSystem: "IDEX",
  },
  adventurer4: {
    id: "adventurer4",
    brand: "flashforge",
    name: "Flashforge Adventurer 4 / 4 Pro",
    shortName: "Adventurer 4",
    enclosed: true,
    powerByMaterial: { pla: 110, petg: 135, abs: 175, tpu: 110, pacf: 175 },
    defaultPower: 125,
    priceKzt: 260_000,
    amsPriceKzt: 0,
    lifespanHours: 4500,
    depreciationPerHour: 58,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  artemis: {
    id: "artemis",
    brand: "flashforge",
    name: "Flashforge Artemis",
    shortName: "Artemis",
    enclosed: false,
    powerByMaterial: { pla: 110, petg: 135, abs: 175, tpu: 110, pacf: 175 },
    defaultPower: 125,
    priceKzt: 185_000,
    amsPriceKzt: 0,
    lifespanHours: 4000,
    depreciationPerHour: 46,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  finder3: {
    id: "finder3",
    brand: "flashforge",
    name: "Flashforge Finder 3",
    shortName: "Finder 3",
    enclosed: false,
    powerByMaterial: { pla: 95, petg: 115, abs: 150, tpu: 95, pacf: 150 },
    defaultPower: 105,
    priceKzt: 150_000,
    amsPriceKzt: 0,
    lifespanHours: 3500,
    depreciationPerHour: 43,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  creator3: {
    id: "creator3",
    brand: "flashforge",
    name: "Flashforge Creator 3 Pro (IDEX)",
    shortName: "Creator 3 Pro",
    enclosed: true,
    powerByMaterial: { pla: 260, petg: 310, abs: 420, tpu: 260, pacf: 450 },
    defaultPower: 350,
    priceKzt: 1_100_000,
    amsPriceKzt: 0,
    lifespanHours: 8000,
    depreciationPerHour: 138,
    multiColorCapable: true,
    multiColorSystem: "IDEX",
  },
  creator_pro2: {
    id: "creator_pro2",
    brand: "flashforge",
    name: "Flashforge Creator Pro 2 (IDEX)",
    shortName: "Creator Pro 2",
    enclosed: true,
    powerByMaterial: { pla: 160, petg: 190, abs: 260, tpu: 160, pacf: 280 },
    defaultPower: 180,
    priceKzt: 340_000,
    amsPriceKzt: 0,
    lifespanHours: 5000,
    depreciationPerHour: 68,
    multiColorCapable: true,
    multiColorSystem: "IDEX",
  },
  guider2s: {
    id: "guider2s",
    brand: "flashforge",
    name: "Flashforge Guider IIs / Guider II",
    shortName: "Guider IIs",
    enclosed: true,
    powerByMaterial: { pla: 180, petg: 220, abs: 300, tpu: 180, pacf: 320 },
    defaultPower: 220,
    priceKzt: 550_000,
    amsPriceKzt: 0,
    lifespanHours: 6500,
    depreciationPerHour: 85,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  adventurer3: {
    id: "adventurer3",
    brand: "flashforge",
    name: "Flashforge Adventurer 3 / 3 Pro",
    shortName: "Adventurer 3",
    enclosed: true,
    powerByMaterial: { pla: 80, petg: 100, abs: 130, tpu: 80, pacf: 130 },
    defaultPower: 90,
    priceKzt: 140_000,
    amsPriceKzt: 0,
    lifespanHours: 3500,
    depreciationPerHour: 40,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  creator_pro: {
    id: "creator_pro",
    brand: "flashforge",
    name: "Flashforge Creator Pro",
    shortName: "Creator Pro",
    enclosed: true,
    powerByMaterial: { pla: 150, petg: 180, abs: 240, tpu: 150, pacf: 250 },
    defaultPower: 170,
    priceKzt: 220_000,
    amsPriceKzt: 0,
    lifespanHours: 4000,
    depreciationPerHour: 55,
    multiColorCapable: true,
    multiColorSystem: "Dual Extruder",
  },

  // ── Flying Bear (Newest -> Oldest) ──
  reborn2: {
    id: "reborn2",
    brand: "flyingbear",
    name: "Flying Bear Reborn 2",
    shortName: "Reborn 2",
    enclosed: true,
    powerByMaterial: { pla: 180, petg: 220, abs: 290, tpu: 180, pacf: 290 },
    defaultPower: 220,
    priceKzt: 280_000,
    amsPriceKzt: 0,
    lifespanHours: 5000,
    depreciationPerHour: 56,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  ghost6: {
    id: "ghost6",
    brand: "flyingbear",
    name: "Flying Bear Ghost 6",
    shortName: "Ghost 6",
    enclosed: false,
    powerByMaterial: { pla: 110, petg: 130, abs: 170, tpu: 110, pacf: 170 },
    defaultPower: 125,
    priceKzt: 160_000,
    amsPriceKzt: 0,
    lifespanHours: 4000,
    depreciationPerHour: 40,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  ghost5: {
    id: "ghost5",
    brand: "flyingbear",
    name: "Flying Bear Ghost 5",
    shortName: "Ghost 5",
    enclosed: false,
    powerByMaterial: { pla: 100, petg: 120, abs: 160, tpu: 100, pacf: 160 },
    defaultPower: 115,
    priceKzt: 130_000,
    amsPriceKzt: 0,
    lifespanHours: 3500,
    depreciationPerHour: 37,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },

  // ── Kingroon (Newest -> Oldest) ──
  klp1: {
    id: "klp1",
    brand: "kingroon",
    name: "Kingroon KLP1 (CoreXY Klipper)",
    shortName: "KLP1",
    enclosed: true,
    powerByMaterial: { pla: 100, petg: 120, abs: 160, tpu: 100, pacf: 160 },
    defaultPower: 110,
    priceKzt: 130_000,
    amsPriceKzt: 0,
    lifespanHours: 3500,
    depreciationPerHour: 37,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  kp3s_pro_v2: {
    id: "kp3s_pro_v2",
    brand: "kingroon",
    name: "Kingroon KP3S Pro V2",
    shortName: "KP3S Pro V2",
    enclosed: false,
    powerByMaterial: { pla: 95, petg: 115, abs: 150, tpu: 95, pacf: 150 },
    defaultPower: 105,
    priceKzt: 110_000,
    amsPriceKzt: 0,
    lifespanHours: 3000,
    depreciationPerHour: 37,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  kp3s_pro: {
    id: "kp3s_pro",
    brand: "kingroon",
    name: "Kingroon KP3S Pro",
    shortName: "KP3S Pro",
    enclosed: false,
    powerByMaterial: { pla: 90, petg: 110, abs: 140, tpu: 90, pacf: 140 },
    defaultPower: 100,
    priceKzt: 95_000,
    amsPriceKzt: 0,
    lifespanHours: 3000,
    depreciationPerHour: 32,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  kp3s: {
    id: "kp3s",
    brand: "kingroon",
    name: "Kingroon KP3S 3.0",
    shortName: "KP3S",
    enclosed: false,
    powerByMaterial: { pla: 80, petg: 100, abs: 130, tpu: 80, pacf: 130 },
    defaultPower: 90,
    priceKzt: 75_000,
    amsPriceKzt: 0,
    lifespanHours: 2500,
    depreciationPerHour: 30,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },

  // ── Artillery (Newest -> Oldest) ──
  sidewinder_x4_plus: {
    id: "sidewinder_x4_plus",
    brand: "artillery",
    name: "Artillery Sidewinder X4 Plus / Pro",
    shortName: "Sidewinder X4 Plus",
    enclosed: false,
    powerByMaterial: { pla: 140, petg: 170, abs: 215, tpu: 140, pacf: 215 },
    defaultPower: 155,
    priceKzt: 195_000,
    amsPriceKzt: 0,
    lifespanHours: 4000,
    depreciationPerHour: 49,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  sidewinder_x4: {
    id: "sidewinder_x4",
    brand: "artillery",
    name: "Artillery Sidewinder X4",
    shortName: "Sidewinder X4",
    enclosed: false,
    powerByMaterial: { pla: 120, petg: 145, abs: 185, tpu: 120, pacf: 185 },
    defaultPower: 135,
    priceKzt: 165_000,
    amsPriceKzt: 0,
    lifespanHours: 3500,
    depreciationPerHour: 47,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  sidewinder_x2: {
    id: "sidewinder_x2",
    brand: "artillery",
    name: "Artillery Sidewinder X2 (300×300)",
    shortName: "Sidewinder X2",
    enclosed: false,
    powerByMaterial: { pla: 130, petg: 155, abs: 200, tpu: 130, pacf: 200 },
    defaultPower: 145,
    priceKzt: 160_000,
    amsPriceKzt: 0,
    lifespanHours: 4000,
    depreciationPerHour: 40,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  genius_pro: {
    id: "genius_pro",
    brand: "artillery",
    name: "Artillery Genius Pro",
    shortName: "Genius Pro",
    enclosed: false,
    powerByMaterial: { pla: 100, petg: 120, abs: 160, tpu: 100, pacf: 160 },
    defaultPower: 110,
    priceKzt: 130_000,
    amsPriceKzt: 0,
    lifespanHours: 3500,
    depreciationPerHour: 37,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },

  // ── Two Trees (Newest -> Oldest) ──
  sk1: {
    id: "sk1",
    brand: "twotrees",
    name: "Two Trees SK1 (CoreXY 700mm/s)",
    shortName: "Two Trees SK1",
    enclosed: false,
    powerByMaterial: { pla: 135, petg: 165, abs: 210, tpu: 135, pacf: 210 },
    defaultPower: 150,
    priceKzt: 210_000,
    amsPriceKzt: 0,
    lifespanHours: 4500,
    depreciationPerHour: 47,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  bluer_plus: {
    id: "bluer_plus",
    brand: "twotrees",
    name: "Two Trees Bluer Plus (300×300)",
    shortName: "Bluer Plus",
    enclosed: false,
    powerByMaterial: { pla: 125, petg: 150, abs: 195, tpu: 125, pacf: 195 },
    defaultPower: 140,
    priceKzt: 150_000,
    amsPriceKzt: 0,
    lifespanHours: 3500,
    depreciationPerHour: 43,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },
  sapphire_plus: {
    id: "sapphire_plus",
    brand: "twotrees",
    name: "Two Trees Sapphire Plus",
    shortName: "Sapphire Plus",
    enclosed: false,
    powerByMaterial: { pla: 130, petg: 155, abs: 200, tpu: 130, pacf: 200 },
    defaultPower: 145,
    priceKzt: 180_000,
    amsPriceKzt: 0,
    lifespanHours: 4000,
    depreciationPerHour: 45,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },

  // ── Snapmaker (Newest -> Oldest) ──
  snapmaker_u1: {
    id: "snapmaker_u1",
    brand: "snapmaker",
    name: "Snapmaker Artisan / J1s",
    shortName: "Snapmaker Artisan",
    enclosed: true,
    powerByMaterial: { pla: 180, petg: 220, abs: 300, tpu: 180, pacf: 320 },
    defaultPower: 220,
    priceKzt: 650_000,
    amsPriceKzt: 0,
    lifespanHours: 7000,
    depreciationPerHour: 93,
    multiColorCapable: true,
    multiColorSystem: "IDEX Dual",
  },
  snapmaker_j1: {
    id: "snapmaker_j1",
    brand: "snapmaker",
    name: "Snapmaker J1 (IDEX)",
    shortName: "Snapmaker J1",
    enclosed: true,
    powerByMaterial: { pla: 150, petg: 180, abs: 240, tpu: 150, pacf: 260 },
    defaultPower: 180,
    priceKzt: 480_000,
    amsPriceKzt: 0,
    lifespanHours: 6000,
    depreciationPerHour: 80,
    multiColorCapable: true,
    multiColorSystem: "IDEX",
  },
  snapmaker_2: {
    id: "snapmaker_2",
    brand: "snapmaker",
    name: "Snapmaker 2.0 A350T",
    shortName: "Snapmaker A350T",
    enclosed: true,
    powerByMaterial: { pla: 160, petg: 195, abs: 260, tpu: 160, pacf: 280 },
    defaultPower: 200,
    priceKzt: 590_000,
    amsPriceKzt: 0,
    lifespanHours: 6500,
    depreciationPerHour: 91,
    multiColorCapable: false,
    multiColorSystem: "Ручная смена",
  },

  // ── Raise3D & UltiMaker (Newest -> Oldest) ──
  raise3d_pro3_plus: {
    id: "raise3d_pro3_plus",
    brand: "raise3d",
    name: "Raise3D Pro3 Plus (300×300×605)",
    shortName: "Raise3D Pro3+",
    enclosed: true,
    powerByMaterial: { pla: 300, petg: 360, abs: 500, tpu: 300, pacf: 530 },
    defaultPower: 400,
    priceKzt: 3_600_000,
    amsPriceKzt: 0,
    lifespanHours: 12000,
    depreciationPerHour: 300,
    multiColorCapable: true,
    multiColorSystem: "Dual Extruder",
  },
  raise3d_pro3: {
    id: "raise3d_pro3",
    brand: "raise3d",
    name: "Raise3D Pro3 / E2",
    shortName: "Raise3D Pro3",
    enclosed: true,
    powerByMaterial: { pla: 280, petg: 340, abs: 480, tpu: 280, pacf: 500 },
    defaultPower: 380,
    priceKzt: 2_900_000,
    amsPriceKzt: 0,
    lifespanHours: 12000,
    depreciationPerHour: 242,
    multiColorCapable: true,
    multiColorSystem: "Dual Extruder",
  },
  ultimaker_s7: {
    id: "ultimaker_s7",
    brand: "raise3d",
    name: "UltiMaker S7",
    shortName: "UltiMaker S7",
    enclosed: true,
    powerByMaterial: { pla: 240, petg: 290, abs: 400, tpu: 240, pacf: 420 },
    defaultPower: 320,
    priceKzt: 3_700_000,
    amsPriceKzt: 0,
    lifespanHours: 12000,
    depreciationPerHour: 308,
    multiColorCapable: true,
    multiColorSystem: "Dual Print Core",
  },
  ultimaker_s5: {
    id: "ultimaker_s5",
    brand: "raise3d",
    name: "UltiMaker S5",
    shortName: "UltiMaker S5",
    enclosed: true,
    powerByMaterial: { pla: 220, petg: 270, abs: 380, tpu: 220, pacf: 400 },
    defaultPower: 300,
    priceKzt: 3_200_000,
    amsPriceKzt: 0,
    lifespanHours: 12000,
    depreciationPerHour: 267,
    multiColorCapable: true,
    multiColorSystem: "Dual Print Core",
  },

  // ── Custom ──
  custom: {
    id: "custom",
    brand: "custom",
    name: "Свой принтер",
    shortName: "Свой принтер",
    enclosed: false,
    powerByMaterial: { pla: 120, petg: 150, abs: 220, tpu: 120, pacf: 220 },
    defaultPower: 150,
    priceKzt: 250_000,
    amsPriceKzt: 150_000,
    lifespanHours: 5000,
    depreciationPerHour: 50,
    multiColorCapable: true,
    multiColorSystem: "Настраиваемая",
  },
};

export type MaterialId = "pla" | "petg" | "abs" | "tpu" | "pacf" | "custom";

export interface MaterialProfile {
  id: MaterialId;
  name: string;
  defaultPriceKg: number; // KZT
  density: number; // g/cm³
  bedTemp: string;
  abrasive: boolean;
}

export const MATERIAL_PROFILES: Record<MaterialId, MaterialProfile> = {
  pla: {
    id: "pla",
    name: "PLA",
    defaultPriceKg: 7500,
    density: 1.24,
    bedTemp: "55–65 °C",
    abrasive: false,
  },
  petg: {
    id: "petg",
    name: "PETG",
    defaultPriceKg: 5500,
    density: 1.27,
    bedTemp: "70–80 °C",
    abrasive: false,
  },
  abs: {
    id: "abs",
    name: "ABS / ASA",
    defaultPriceKg: 6500,
    density: 1.05,
    bedTemp: "90–100 °C",
    abrasive: false,
  },
  tpu: {
    id: "tpu",
    name: "TPU (Flex)",
    defaultPriceKg: 9000,
    density: 1.21,
    bedTemp: "35–50 °C",
    abrasive: false,
  },
  pacf: {
    id: "pacf",
    name: "PA-CF (Carbon)",
    defaultPriceKg: 19000,
    density: 1.18,
    bedTemp: "90–100 °C",
    abrasive: true,
  },
  custom: {
    id: "custom",
    name: "Другой пластик",
    defaultPriceKg: 7000,
    density: 1.25,
    bedTemp: "60 °C",
    abrasive: false,
  },
};

export type DryerId = "none" | "standard" | "quad";

export interface DryerProfile {
  id: DryerId;
  name: { ru: string; en: string };
  watts: number;
  depreciationPerHour: number; // KZT
}

export const DRYER_PROFILES: Record<DryerId, DryerProfile> = {
  none: {
    id: "none",
    name: { ru: "Без сушилки", en: "No dryer" },
    watts: 0,
    depreciationPerHour: 0,
  },
  standard: {
    id: "standard",
    name: { ru: "1 катушка (Sunlu S2 / Space Pi 55 Вт)", en: "1 spool (Sunlu S2 / Space Pi 55W)" },
    watts: 55,
    depreciationPerHour: 9,
  },
  quad: {
    id: "quad",
    name: { ru: "4 катушки (Sunlu S4 120 Вт)", en: "4 spools (Sunlu S4 120W)" },
    watts: 120,
    depreciationPerHour: 16,
  },
};

export type NozzleId = "brass" | "hardened" | "ruby";

export interface NozzleProfile {
  id: NozzleId;
  name: { ru: string; en: string };
  wearPerHour: number; // KZT
  wearPerHourAbrasive: number; // KZT
}

export const NOZZLE_PROFILES: Record<NozzleId, NozzleProfile> = {
  brass: {
    id: "brass",
    name: { ru: "Латунь 0.4 (Brass)", en: "Brass 0.4" },
    wearPerHour: 4,
    wearPerHourAbrasive: 80,
  },
  hardened: {
    id: "hardened",
    name: { ru: "Закаленная сталь (Hardened Steel)", en: "Hardened Steel" },
    wearPerHour: 5,
    wearPerHourAbrasive: 6,
  },
  ruby: {
    id: "ruby",
    name: { ru: "Рубин / Карбид вольфрама", en: "Ruby / Tungsten Carbide" },
    wearPerHour: 7,
    wearPerHourAbrasive: 7,
  },
};

export type PackagingId = "none" | "bag_bubble" | "kraft_box" | "cdek_box" | "custom";

export interface PackagingOption {
  id: PackagingId;
  name: { ru: string; en: string };
  costKzt: number;
}

export const PACKAGING_OPTIONS: Record<PackagingId, PackagingOption> = {
  none: {
    id: "none",
    name: { ru: "Без упаковки", en: "No packaging" },
    costKzt: 0,
  },
  bag_bubble: {
    id: "bag_bubble",
    name: { ru: "Зип-пакет + пупырчатая пленка", en: "Zip bag + bubble wrap" },
    costKzt: 150,
  },
  kraft_box: {
    id: "kraft_box",
    name: { ru: "Крафт-коробка с наполнителем", en: "Kraft box with cushioning" },
    costKzt: 350,
  },
  cdek_box: {
    id: "cdek_box",
    name: { ru: "Усиленный почтовый бокс / СДЭК", en: "Heavy-duty courier box" },
    costKzt: 700,
  },
  custom: {
    id: "custom",
    name: { ru: "Своя упаковка", en: "Custom packaging" },
    costKzt: 200,
  },
};

export type TaxRegimeId = "none" | "simplified_3" | "retail_4" | "vat_12";

export interface TaxRegimeOption {
  id: TaxRegimeId;
  name: { ru: string; en: string };
  rate: number;
}

export const TAX_REGIMES: Record<TaxRegimeId, TaxRegimeOption> = {
  none: {
    id: "none",
    name: { ru: "Физлицо / Без налога", en: "Individual / No tax" },
    rate: 0,
  },
  simplified_3: {
    id: "simplified_3",
    name: { ru: "ИП на упрощенке (3 % СНР)", en: "Simplified IP (3% tax)" },
    rate: 0.03,
  },
  retail_4: {
    id: "retail_4",
    name: { ru: "Розничный налог (4 %)", en: "Retail tax (4%)" },
    rate: 0.04,
  },
  vat_12: {
    id: "vat_12",
    name: { ru: "С НДС (+12 %)", en: "With VAT (+12%)" },
    rate: 0.12,
  },
};
