import type { Locale } from "@/i18n/config";

/** Strings shared by the media tool UI kit. */
export const UI = {
  ru: {
    chooseVideo: "Перетащите видео сюда или нажмите, чтобы выбрать",
    chooseAudio: "Перетащите аудиофайл сюда или нажмите, чтобы выбрать",
    chooseFiles: "Перетащите файлы сюда или нажмите, чтобы выбрать",
    chooseMedia: "Перетащите видео или аудио сюда или нажмите, чтобы выбрать",
    videoFormats: "MP4, MOV, MKV, WebM, AVI и другие",
    audioFormats: "MP3, WAV, M4A, FLAC, OGG, а также звук из видео",
    change: "Другой файл",
    fileInfo: "Подробнее о файле",
    remove: "Убрать",
    start: "Начать",
    cancel: "Отменить",
    again: "Обработать другой файл",
    edit: "Изменить параметры",
    retry: "Попробовать снова",
    download: "Скачать",
    preparing: "Подготовка…",
    processing: "Обработка",
    downloadingEngine: "Загружаем запасной модуль ffmpeg (до 31 МБ, один раз)",
    ffmpegWork: "Обработка через ffmpeg (медленнее основного движка)",
    cancelled: "Отменено",
    done: "Готово",
    progress: "Прогресс",
    result: "Результат",
    size: "Размер",
    was: "было",
    smaller: "меньше",
    larger: "больше",
    duration: "Длительность",
    resolution: "Разрешение",
    container: "Контейнер",
    video: "Видео",
    audio: "Звук",
    fps: "кадр/с",
    bitrate: "Битрейт",
    kbps: "кбит/с",
    mbps: "Мбит/с",
    channels: "Каналы",
    mono: "моно",
    stereo: "стерео",
    hz: "Гц",
    noTrack: "нет",
    copyMode: "Без перекодирования",
    copyModeHint: "Потоки скопированы как есть — качество не изменилось",
    transcodeMode: "Перекодировано",
    mixedMode: "Частично перекодировано",
    engineWebCodecs: "WebCodecs (аппаратное ускорение)",
    engineFfmpeg: "ffmpeg.wasm (запасной путь)",
    engine: "Движок",
    codecs: "Кодеки",
    detected: "Формат по сигнатуре",
    probing: "Читаем файл…",
    unreadable: "Браузер не читает этот контейнер напрямую — будет использован ffmpeg",
    noWebCodecs: "Ваш браузер не поддерживает WebCodecs, поэтому обработка пойдёт через ffmpeg.wasm — медленнее. Быстрее всего работают свежие Chrome, Edge, Firefox и Safari.",
    bigVideo: "Файл больше 2 ГБ. Браузер может не справиться с таким объёмом памяти — если обработка прервётся, попробуйте файл поменьше или другой браузер.",
    bigAudio: "Запись длинная: для редактирования её нужно распаковать в память (около {mb} МБ). На слабых устройствах это может не получиться.",
    errors: {
      NO_VIDEO: "В файле нет видеодорожки.",
      NO_AUDIO: "В файле нет звуковой дорожки.",
      NO_ENCODER: "Браузер не умеет кодировать нужный формат.",
      MERGE_UNREADABLE: "Один из файлов не удалось прочитать. Сначала сконвертируйте его в MP4.",
      MERGE_UNDECODABLE: "Браузер не может декодировать один из клипов. Сконвертируйте его в MP4 (H.264) и попробуйте снова.",
      MEMORY: "Не хватило памяти браузера. Попробуйте файл поменьше, более низкое разрешение или короткий фрагмент.",
      FFMPEG: "Не удалось обработать файл: формат повреждён или кодек не поддерживается.",
      ASSET: "Не удалось загрузить модуль ffmpeg. Проверьте подключение и обновите страницу.",
      GENERIC: "Не удалось обработать файл.",
    },
  },
  en: {
    chooseVideo: "Drop a video here or click to choose",
    chooseAudio: "Drop an audio file here or click to choose",
    chooseFiles: "Drop files here or click to choose",
    chooseMedia: "Drop a video or audio file here or click to choose",
    videoFormats: "MP4, MOV, MKV, WebM, AVI and more",
    audioFormats: "MP3, WAV, M4A, FLAC, OGG, or the sound of a video",
    change: "Another file",
    fileInfo: "File details",
    remove: "Remove",
    start: "Start",
    cancel: "Cancel",
    again: "Process another file",
    edit: "Adjust and redo",
    retry: "Try again",
    download: "Download",
    preparing: "Preparing…",
    processing: "Processing",
    downloadingEngine: "Loading the ffmpeg fallback (up to 31 MB, once)",
    ffmpegWork: "Processing with ffmpeg (slower than the main engine)",
    cancelled: "Cancelled",
    done: "Done",
    progress: "Progress",
    result: "Result",
    size: "Size",
    was: "was",
    smaller: "smaller",
    larger: "larger",
    duration: "Duration",
    resolution: "Resolution",
    container: "Container",
    video: "Video",
    audio: "Audio",
    fps: "fps",
    bitrate: "Bitrate",
    kbps: "kbit/s",
    mbps: "Mbit/s",
    channels: "Channels",
    mono: "mono",
    stereo: "stereo",
    hz: "Hz",
    noTrack: "none",
    copyMode: "No re-encoding",
    copyModeHint: "Streams were copied as they are — quality is unchanged",
    transcodeMode: "Re-encoded",
    mixedMode: "Partly re-encoded",
    engineWebCodecs: "WebCodecs (hardware accelerated)",
    engineFfmpeg: "ffmpeg.wasm (fallback)",
    engine: "Engine",
    codecs: "Codecs",
    detected: "Format by signature",
    probing: "Reading the file…",
    unreadable: "The browser can't read this container directly — ffmpeg will be used",
    noWebCodecs: "Your browser has no WebCodecs support, so processing falls back to ffmpeg.wasm, which is slower. Recent Chrome, Edge, Firefox and Safari are fastest.",
    bigVideo: "The file is larger than 2 GB. The browser may run out of memory — if processing fails, try a smaller file or another browser.",
    bigAudio: "This is a long recording: editing needs it decoded in memory (about {mb} MB). Low-memory devices may fail.",
    errors: {
      NO_VIDEO: "The file has no video track.",
      NO_AUDIO: "The file has no audio track.",
      NO_ENCODER: "Your browser can't encode the required format.",
      MERGE_UNREADABLE: "One of the files could not be read. Convert it to MP4 first.",
      MERGE_UNDECODABLE: "Your browser can't decode one of the clips. Convert it to MP4 (H.264) and try again.",
      MEMORY: "The browser ran out of memory. Try a smaller file, a lower resolution or a shorter part.",
      FFMPEG: "Could not process the file: it is damaged or uses an unsupported codec.",
      ASSET: "Could not load the ffmpeg module. Check your connection and reload the page.",
      GENERIC: "Could not process the file.",
    },
  },
} as const;

/** Map an engine error to a user-facing message. */
export function errorText(locale: Locale, err: unknown): string {
  const e = UI[locale].errors;
  const code = (err as { code?: string })?.code ?? "";
  const msg = String((err as { message?: string })?.message ?? "");
  if (code in e) return e[code as keyof typeof e];
  if (err instanceof RangeError || /allocation|out of memory|OOM/i.test(msg)) return e.MEMORY;
  if (/^FFMPEG_ASSET/.test(msg)) return e.ASSET;
  if (/^FFMPEG/.test(msg)) return e.FFMPEG;
  return e.GENERIC;
}
