/**
 * Sitemap entry builders — segmented by content type.
 *
 * Indexable URLs are split into three semantic sitemap files so each content
 * type can be monitored independently:
 *
 *   /sitemap.xml             → sitemap INDEX (auto-generated by Next.js)
 *   /sitemap/main.xml        → home + group landing pages
 *   /sitemap/tools.xml       → all implemented tool detail pages
 *   /sitemap/kz.xml          → Kazakhstan index
 *
 * Each entry carries `alternates.languages` (hreflang) for ru/en +
 * x-default → ru. Dates and crawl hints are intentionally omitted unless a
 * future content pipeline can prove them per URL.
 *
 * Google's hard limit per file is 50 000 URLs. We're well under that on every
 * segment, but splitting still gives crawlers easier digest, lets us tag
 * different `changeFrequency` per section, and isolates failures.
 */

import { MetadataRoute } from "next";
import { tools, toolGroups } from "@/src/data/tools";
import { siteConfig } from "@/src/config/site.config";

// ─── Constants ───────────────────────────────────────────────────────────────

export const BASE_URL = siteConfig.baseUrl;
export const LOCALES = ["ru", "en"] as const;
export type Locale = (typeof LOCALES)[number];

// ─── URL helpers ─────────────────────────────────────────────────────────────

function normalizeLogicalPath(path: string): string {
  if (path === "" || path === "/") return "";
  const withLeadingSlash = path.startsWith("/") ? path : `/${path}`;
  return withLeadingSlash.replace(/\/$/, "");
}

function withLocale(path: string, locale: Locale): string {
  return `${BASE_URL}/${locale}${normalizeLogicalPath(path)}`;
}

/**
 * Build the `<xhtml:link rel="alternate" hreflang>` map for one logical
 * page. `x-default` points at the Russian version since traffic is
 * predominantly KZ + RU.
 */
function buildAlternates(
  path: string,
): NonNullable<MetadataRoute.Sitemap[number]["alternates"]> {
  const normalized = normalizeLogicalPath(path);
  return {
    languages: {
      ru: `${BASE_URL}/ru${normalized}`,
      en: `${BASE_URL}/en${normalized}`,
      "x-default": `${BASE_URL}/ru${normalized}`,
    },
  };
}

function makeEntry(
  path: string,
  locale: Locale,
): MetadataRoute.Sitemap[number] {
  return {
    url: withLocale(path, locale),
    alternates: buildAlternates(path),
  };
}

// ─── Sitemap segments ────────────────────────────────────────────────────────

/**
 * `/sitemap/main.xml` — root + tool group landing pages.
 * Smallest segment, refreshed daily. ~30 URLs across both locales.
 */
export function buildMainEntries(): MetadataRoute.Sitemap {
  const entries: MetadataRoute.Sitemap = [];

  for (const locale of LOCALES) {
    // Home
    entries.push(
      makeEntry("/", locale),
    );
    entries.push(
      makeEntry("/privacy", locale),
    );
    entries.push(
      makeEntry("/terms", locale),
    );

    // Group landing pages (e.g. /group/converters, /group/pdf-tools, …)
    for (const g of toolGroups) {
      entries.push(
        makeEntry(`/group/${g.slug}`, locale),
      );
    }
  }

  return entries.sort((a, b) => a.url.localeCompare(b.url));
}

/**
 * `/sitemap/tools.xml` — every implemented tool detail page.
 * Largest stable segment, refreshed weekly.
 */
export function buildToolsEntries(): MetadataRoute.Sitemap {
  const entries: MetadataRoute.Sitemap = [];
  const implementedTools = tools.filter((t) => t.implemented && !t.hidden);

  for (const locale of LOCALES) {
    for (const t of implementedTools) {
      entries.push(
        makeEntry(`/tools/${t.slug}`, locale),
      );
    }
  }

  return entries.sort((a, b) => a.url.localeCompare(b.url));
}

/**
 * `/sitemap/kz.xml` — Kazakhstan hub only. Retired city pages permanently
 * redirect to the hub and are excluded from discovery feeds.
 */
export function buildKzEntries(): MetadataRoute.Sitemap {
  const entries: MetadataRoute.Sitemap = [];

  for (const locale of LOCALES) {
    entries.push(
      makeEntry("/kz", locale),
    );
  }

  return entries.sort((a, b) => a.url.localeCompare(b.url));
}

// ─── Aggregate (legacy / fallback) ───────────────────────────────────────────

/**
 * Concatenate every segment in one big sitemap. Kept for backwards
 * compatibility with anything that imported the old function name. Not used
 * by the runtime sitemap.xml endpoint any more.
 */
export function buildAllSitemapEntries(): MetadataRoute.Sitemap {
  return [...buildMainEntries(), ...buildToolsEntries(), ...buildKzEntries()];
}

// ─── Segment registry (used by app/sitemap.ts generateSitemaps) ─────────────

export type SitemapSegmentId = "main" | "tools" | "kz";

export const SITEMAP_SEGMENTS: {
  id: SitemapSegmentId;
  build: () => MetadataRoute.Sitemap;
}[] = [
  { id: "main", build: buildMainEntries },
  { id: "tools", build: buildToolsEntries },
  { id: "kz", build: buildKzEntries },
];
